### ISSUE TITLE
Search Journal Entries doesn't work

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#1]
tested with foundry 0.8.5, DnD5e 1.3.2

Entering text on the "Search Journal Entries" does not filter the underlying entries (no console errors):

![CleanShot 2021-05-31 at 10 00 15](https://user-images.githubusercontent.com/6490765/120161409-8e18b980-c1f7-11eb-99ab-3e5ec42af08a.png)

**Comment by ironmonk88** [comment]
Fixed, will be in the next release.

**Comment by ironmonk88** [comment]
New Release has been uploaded.
I honestly didn't even think to test this one.  Thank you!
