### ISSUE TITLE
Add bookmark on blank page shouldn't be allowed

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#10]
tested on foundry 0.8.6, DnD5e 1.3.3

At the moment it is possible to add a bookmark on blank pages, the result is a "undefined" bookmark:

![CleanShot 2021-05-31 at 22 19 38](https://user-images.githubusercontent.com/6490765/120239628-f5b61f80-c25e-11eb-81b7-4e291a4b40b3.png)

**Comment by ironmonk88** [comment]
Should be fixed in 1.0.7
