### ISSUE TITLE
Failed to download the file SlideshowSheet.js

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#102]
In my hosted server I get an error when the module tries to download the SlideshowSheet.js file:

<img width="1003" alt="CleanShot 2021-09-25 at 14 21 02@2x" src="https://user-images.githubusercontent.com/6490765/134771423-2643ec19-a789-4216-ae0a-ba9738b134fe.png">

In the directory the file has a name with a different character case:

SlideShowSheet.js

The strange thing is that in my local foundry installation it doesn't happen. It probably depends on the underlying operating system (case insensitive)
however, it is better to align the JS import or file name with the same character case.

**Comment by ironmonk88** [comment]
Changed the character case and it seems to have cleared up.
This should be fixed in the latest release.
