### ISSUE TITLE
Cannot create a Quest Entry

### ISSUE THREAD

**Issue by Brimcon** [ironmonk88/monks-enhanced-journal#103]
Creating a Quest Journal entry gives a blank journal entry that cannot be modified or changed.
Prints these errors in console:
Using 0.8.9 Foundry and 1.0.23 Monk's Enhanced Journal
![image](https://user-images.githubusercontent.com/7198283/134777215-2c0330cd-6ae0-4df5-9b9b-2346c5429c6a.png)

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
