### ISSUE TITLE
Unable to type after "unsaved progress" dialog appeared

### ISSUE THREAD

**Issue by JanHoos** [ironmonk88/monks-enhanced-journal#106]
Hi IronMonk! 

I just installed this fantastic module and have a lot of journal entries from before your epic module. When I edited one, I couldn't find the save button so I clicked on another journal item, thinking there might be some auto-save feature. 

When I did, a dialogue popped up reminding me I had unsaved items. When I click cancel, I lose the ability to edit my item. It's still in the edit mode, but my cursor is gone. Typing on my keyboard does nothing. 

I reproduced it twice.

**Comment by JanHoos** [comment]
It appears I can type again. Not sure why I couldn't the other two times. Thought I encountered a bug, sorry!

**Comment by ironmonk88** [comment]
I'm assuming you're using the client and not the webpage
It is a bug but I think I just inadvertently stumbled into an issue with Foundry.
I've had success with minimizing the client and then restoring it to get the cursor back, but other people have not.
I'm currently looking into it.  To see if there's something I can change or workaround the issue.

**Comment by JanHoos** [comment]
Uh Oh! That would suck if it's a foundry thing I guess? Thanks for checking it out :-) 

Another thing is, the cancel button on the dialogue does not cancel my closing action so I've lost some of my work.

**Comment by ironmonk88** [comment]
Switched to using a Foundry Dialog instead of the javascript confirm box and it looks like that should have solved it.
Changes are int he latest release.
