### ISSUE TITLE
Getting errors in Log when I open a Journal

### ISSUE THREAD

**Issue by jseaz73** [ironmonk88/monks-enhanced-journal#107]
![image](https://user-images.githubusercontent.com/16529812/135259657-cfc5edbb-81f1-434b-9a50-8850e2448ef1.png)

**Comment by SwordofSpirit** [comment]
Same here
![Screenshot 2021-10-01 010653](https://user-images.githubusercontent.com/87603251/135481579-a59ca70d-5b8f-4391-af37-e6119c5ce625.png)
:

**Comment by ironmonk88** [comment]
Closing this as I believe it has been fixed.
