### ISSUE TITLE
[Suggestion] Adding a bookmark to the same page more than once shouldn't be allowed

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#11]
tested on foundry 0.8.6, DnD5e 1.3.3

clicking repeatedly on the bookmark for the same page adds the bookmark repeatedly.
tip: each page should only be able to be bookmarked once.

![CleanShot 2021-05-31 at 22 25 54](https://user-images.githubusercontent.com/6490765/120240830-cf45b380-c261-11eb-93cd-2d0285482e31.png)

**Comment by ironmonk88** [comment]
Fixed and will be in the next release.

**Comment by ironmonk88** [comment]
Should be fixed in 1.0.7
