### ISSUE TITLE
FVTT Data Toolbox compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [ironmonk88/monks-enhanced-journal#113]
When Data Toolbox is run with Monk's Enhanced Journal, Lib: Document Sheet Registrar (Dependency of Monk's Enhanced Journal), and libwrapper, The journal entries all let you view them once, and then show a blank page that just says Recently Viewed when you leave them and return. The below error is also generated in the F12 Console. I had to use Find the Culprit to identify the Data Toolbox module as the problem, as it is not listed in the error message. I also submitted an issue to FVTT Data Toolbox's Github, but I am not at all confident that they will do anything about it, as they have not replied to any issues for the module in several months.
```
VM198466:7 TypeError: Cannot convert undefined or null to object
[Detected 3 packages: _document-sheet-registrar, lib-wrapper, monks-enhanced-journal]
    at Function.entries (<anonymous>)
    at Function.getDocumentSheetHeaderButtons (document-sheet-registrar.js:127)
    at Function._call (eval at <anonymous> (listeners.js:92), <anonymous>:4:14)
    at Function.call (foundry.js:179)
    at EnhancedJournal.renderSubSheet (enhanced-journal.js:182)
    at EnhancedJournal._render (enhanced-journal.js:103)
_call	@	VM198466:7
call	@	foundry.js:179
renderSubSheet	@	enhanced-journal.js:182
_render	@	enhanced-journal.js:103
async function (async)		
_render	@	enhanced-journal.js:96
render	@	foundry.js:2011
updateTab	@	enhanced-journal.js:542
open	@	enhanced-journal.js:751
async function (async)		
open	@	enhanced-journal.js:748
navigateFolder	@	enhanced-journal.js:603
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2
```

**Comment by ironmonk88** [comment]
I believe this has been fixed, or no longer an issue.
