### ISSUE TITLE
Incompatibility with Warhammer Fantasy Module

### ISSUE THREAD

**Issue by Craftzero** [ironmonk88/monks-enhanced-journal#114]
When Monk's Enhanced Journal is activated, most of the text in a journal is unreadable due to the color of the font and the color of the background.

**Comment by mogrogh** [comment]
It wasn't easy GMing today, I 2nd this.
![image](https://user-images.githubusercontent.com/69079040/136672265-ece2a8c1-2f5f-4c63-9c39-b1c8803a11d0.png)

**Comment by ironmonk88** [comment]
This should be better in the latest release.
