### ISSUE TITLE
When journal entry opened as Scene Note, it doesn't support tabs or sidebar

### ISSUE THREAD

**Issue by SwordofSpirit** [ironmonk88/monks-enhanced-journal#115]
I've checked to make sure it is actually opening the sheet as an enhanced journal entry, and it is. However, there is no ability to access the in journal sidebar, and no space for multiple tabs.

I'd really like to open the scene notes and get the full enhanced journal experience, but right now it doesn't seem to be working that way.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
