### ISSUE TITLE
View Items in Shops

### ISSUE THREAD

**Issue by Argonaut13** [ironmonk88/monks-enhanced-journal#116]
So, with the shop entry set to observer, players can buy from the shop and browse it, but they can't see item description. As DM I can double click the icon and open the item entry, but players lack permission. Is there a way around this?

Edit - Also, buying from the shop entries doesn't deduct from the player's available cash.

**Comment by ironmonk88** [comment]
Added an item summary drop down when the name is clicked.

Unfortunately... automatically deducting from the players cash is a very big issue.  Apart from the wide variety of cash systems each system uses, the conversion rates aren't always the easiest to work with and figuring out which pile it comes from first is challenging.  Makes sense to a human reading it, doesn't exactly make sense to a computer.  It's on the list of things to do... but there's other things I want to do before that happens.

**Comment by Gazook89** [comment]
This is an old issue and likely could have been closed, but I'm glad it is still open:   The expanding drop-down method of displaying item details is good, but at least for Savage Worlds (SWADE) system it does not seem to work (for me, at least).  It expands, but shows 'undefined' for what I assume is a text area, and the few icons don't seem attached to any attribute.

If either that could be adapted for SWADE, or add behavior that opens the item document with a right click on the item or on a new icon viewable by both players and GM it would be a boon.  I can imagine that the latter option would be more flexible across different game systems.

**Comment by ironmonk88** [comment]
Fixed for SWADE.
The joys of each system doing things slightly differently.  :-)

**Comment by Gazook89** [comment]
That was fast, and thank you!  The drop-down is fixed, but those little icons are still a mystery to me.  For a weapon, for instance, I see a *shirt*, *shield*, and *ruler*.   I get that the *shield* is an armor's rating, and the *ruler* corresponds to range on a ranged weapon, but I'm not sure what the *shirt* corresponds to?

This is getting way outside the original issue here, but could an update include:
1. Only showing those icons/attributes if the attribute exists/is greater than '0' for a particular item
2. A simple tooltip on hover for those icons with the attribute they link to
3. More item information overall (weight, min strength, Reach (basically range for melee weapons), damage, etc?
  - I can provide more info on the SWADE item attributes if needed
  - one strategy would be to take any unexpected attributes on an item and create an icon box, but with a generic icon (or none at all) for greater flexibility.

**Comment by Gazook89** [comment]
![image](https://user-images.githubusercontent.com/58999374/174211940-afc0404a-78d3-4b0b-9b95-6606db75a22a.png)

Sort of halfway progress on what i'm talking about above.  Need to hide the price, cost, mod, and a few other properties still.  But I have only looked at the swade item properties, and I'm sure that my progress is not flexible to adapt to other systems.  Work in progress (and I really should be writing campaign plots for tomorrow night...).

**Comment by Gazook89** [comment]
I submitted a [merge request](https://gitlab.com/peginc/swade/-/merge_requests/231) to Florads SWADE system that will add more item stats to the item's `properties` key, which addresses all three requests i made above. So everything on this issue is resolved *for me*, but not sure if that means you can close this or not since I was sort of tacking onto another question.

**Comment by ironmonk88** [comment]
Closing this as I believe all issues have been addressed.
