### ISSUE TITLE
Error when reopening journal entry. 

### ISSUE THREAD

**Issue by rmcleveland** [ironmonk88/monks-enhanced-journal#121]
![image](https://user-images.githubusercontent.com/80587028/138187766-a5face47-1768-4ac1-ac7b-6b008b032263.png)

I am receiving an error in the screenshot after closing a journal entry and then reopening the same entry. 

I am on foundry 0.8.9 and PF1 79.6. Refreshing clears the problem until an entry is opened then closed and reopening is attempted again.

**Comment by Ulvtand** [comment]
I have exactly the same problem. Journals in Compendium are also dabbed.

**Comment by Ulvtand** [comment]
#125

**Comment by rmcleveland** [comment]
I used the Find the Culprit module and determined that Data Toolbox for FoundryVTT was causing the issue. I have deactivated that module and it seems to be okay now, though I do not think this is the long-term fix.

**Comment by ironmonk88** [comment]
I've fixed the issues that data toolbox was causing.
This should be fixed in the latest release.
