### ISSUE TITLE
Incompatibility with Ripper Ui

### ISSUE THREAD

**Issue by Orionox** [ironmonk88/monks-enhanced-journal#122]
Small incompatibility which I feel may be easy to fix, but when using the ripper UI there's an issue where the journal names in the side bar are doubled up/blurry making them hard to read. I will attach a picture so that you can see the problem.
![Capture](https://user-images.githubusercontent.com/20059838/138239306-02e1ec21-a320-40ff-96b6-f9004eeb8195.PNG)

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
