### ISSUE TITLE
Unable to open Person/Place Journal Entries - Error

### ISSUE THREAD

**Issue by Olliekins** [ironmonk88/monks-enhanced-journal#125]
I have disabled all modules, and only enabled MEJ with the _document container.

If I select a normal journal entry, I now see the Foundry default entry.
If I select one of the custom MEJ journal entries that I previously had, it doesn't open, and I receive an 'undefined' error

Checking the console, it looks like just trying to open the journal entry, in general, errors.
![journal_error](https://user-images.githubusercontent.com/84098936/139512563-31e8bdde-3b7f-41fb-87ef-6f0207ce9601.JPG)
![journal_error1](https://user-images.githubusercontent.com/84098936/139512564-c189d393-0f98-414b-afb5-59ff3bc10814.JPG)

**Comment by Ulvtand** [comment]
#118

**Comment by Ulvtand** [comment]
#121

**Comment by ironmonk88** [comment]
This was an issue with the type of entry being changed.
This should be fixed in the latest release.
