### ISSUE TITLE
Players with Limited access can still access the content of journal entries

### ISSUE THREAD

**Issue by jcolson** [ironmonk88/monks-enhanced-journal#127]
If a player has limited access to a journal entry that is placed on a scene, the player can double click it and view the entire journal entry.

This overrides Foundry's default which does not allow Players to view journal entry content if they only have Limited access

**Comment by ironmonk88** [comment]
This should be fixed int he latest release.
Limited permissions will give access to the image if there is one attached to the entry.  Otherwise it won't open.

**Comment by jcolson** [comment]
@ironmonk88 although the release notes say that this is fixed in Version 1.0.32, I have 1.0.35 installed and this is still an issue.
