### ISSUE TITLE
Incompatibility with Coriolis Module

### ISSUE THREAD

**Issue by Berytak** [ironmonk88/monks-enhanced-journal#129]
The mod just loads fine an I cannot see any errors in the console. Nevertheless the journal layout is not loaded. It just looks like the vanilla version without using the mod.

![image](https://user-images.githubusercontent.com/85394657/142854987-51116eb2-5118-480e-9f0c-2f95f348ac98.png)

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
