### ISSUE TITLE
[suggestion/impruvement] Assign encounter items to players

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#13]
I don't know if it has already been planned, but it would be useful to be able to assign the items of a journal encounter to the player's PC sheets, either with a drag & drop or with some method to distribute them

**Comment by ironmonk88** [comment]
Definitely planned.  Drag and Drop can be really temperamental.  There was an attempt made, but it didn't work as intended, so I put it off to the side while getting the rest of the module ready.

**Comment by ironmonk88** [comment]
Added to the latest release.
