### ISSUE TITLE
Can't change tabs within quest entry to add objectives, rewards and notes

### ISSUE THREAD

**Issue by nitorinya** [ironmonk88/monks-enhanced-journal#130]
![image](https://user-images.githubusercontent.com/94874654/142947813-b9a9d880-3847-4e99-8e90-11a34b6fc225.png)
actually it doesn't work for the tabs inside any entry

**Comment by bugbeersandflagons** [comment]
I am unable to change the status of a quest (complete/available etc), unable to see rewards I had previously created, and have lost most functionality of the quest entries since the last d&d 5e game system update

**Comment by ironmonk88** [comment]
Try with the latest release.  I did see some issues that might be causing the problems you're experiencing.
I did work on making sure the old rewards will function with the new system, so they should convert properly.
If it's still an issue can you check the console log to see if there are any errors.

**Comment by nitorinya** [comment]
I believe it might not be compatible with the AGE (unofficial) system

**Comment by ironmonk88** [comment]
Closing this as I believe it should be fixed.
