### ISSUE TITLE
Incompatibility with Pathfinder UI v3 - Player Purchasing Drop-Down

### ISSUE THREAD

**Issue by leerhund** [ironmonk88/monks-enhanced-journal#133]
When Pathbuilder UI v3 is enabled, the **Player Purchasing** drop-down disappears.
![image](https://user-images.githubusercontent.com/95336883/144186585-cddcbd51-f7df-41a5-b75d-85deba71b381.png)

**Comment by ironmonk88** [comment]
Should be fixed int he latest release.
