### ISSUE TITLE
Incompatibility with Journal scaler

### ISSUE THREAD

**Issue by montver** [ironmonk88/monks-enhanced-journal#137]
Journal scaler has a utility which is the possibility to zoom the images inside the journal but if monk's enhanced journal is active it does not work.

**Comment by davelacorneille** [comment]
I really would like this enhancement to be considered!  I'm old and reading the tiny font is hard! :)

Thank you.

**Comment by ironmonk88** [comment]
I believe this is working now?
If it's not, please re-open.
