### ISSUE TITLE
Person Role field not updated

### ISSUE THREAD

**Issue by Fair-Strides** [ironmonk88/monks-enhanced-journal#138]
I can enter info in the Role field for a person (I've been using it for the Alignment and classes of NPCs) and then save the journal, but then the Role field is blank. The data _is_ still there, as evidenced by being able to drag the Person to a Place, but the UI doesn't grab the data when rendering.

(I'll keep an eye out for other fields where this happens.)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
