### ISSUE TITLE
FEATURE REQUEST: Module setting or other method of global field types for entities

### ISSUE THREAD

**Issue by Fair-Strides** [ironmonk88/monks-enhanced-journal#139]
I noticed when I began implementing several NPCs as Person entries that the field filters (like showing Gender or hiding DnD 5E fields in PF1E) are saved/registered per-Person instead of a general "these are the field settings for a Person entry".

I can sort of see where you'd want to change things as-needed from Person to Person, but is it possible to allow for changing the default filters for each journal type in the module settings?

**Comment by Clashsoft** [comment]
I was also wondering about this to the point where it was too much of a hassle to tick all the necessary fields and I just didn't bother filling them out for most Persons.

**Comment by ironmonk88** [comment]
Added the option to set default person settings in settings awhile ago, just tidying up tickets.
