### ISSUE TITLE
Can't open journals from previous version

### ISSUE THREAD

**Issue by Quercuas** [ironmonk88/monks-enhanced-journal#147]
Hi,
I recently upgraded from Foundry 8.9 to 9
Did a reinstall and migrated my data to 9. Ran an update on all Modules & game systems.

Unfortunately I can't open any journal entries. When I do this the following error appears:
`libWrapper-wrapper.js:664 Uncaught TypeError: Cannot set property type of #<JournalEntryData> which has only a getter
[Detected 2 packages: monks-enhanced-journal, lib-wrapper]
    at JournalDirectory.clickDocumentName (monks-enhanced-journal.js:150)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:611)
    at JournalDirectory.🎁JournalDirectory.prototype._onClickDocumentName#0 (libWrapper-wrapper.js:184)
    at HTMLOListElement.dispatch (jquery.min.js:2)
    at HTMLOListElement.v.handle (jquery.min.js:2)
clickDocumentName @ monks-enhanced-journal.js:150
🎁call_wrapper @ libWrapper-wrapper.js:611
🎁JournalDirectory.prototype._onClickDocumentName#0 @ libWrapper-wrapper.js:184
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2`

**Comment by ironmonk88** [comment]
Try disabling the module Lib: Document Sheet Registrar.
It was a dependent module in a previous version, but is no longer required by Enhanced Journal.  And it seems to be causing a lot of issues.

**Comment by Quercuas** [comment]
That fixed it!
