### ISSUE TITLE
[Suggestion] Quest objectives with a counter

### ISSUE THREAD

**Issue by aranian** [ironmonk88/monks-enhanced-journal#149]
This would be a great addition for quests that have multiple of the same objectives. Fetch x items, Kill y Goblins or Do z things.
Here is a mockup of the notification list:
![image](https://user-images.githubusercontent.com/731750/147396189-3726cd61-ec9d-4220-b794-1ff1c634c6f6.png)

**Comment by ironmonk88** [comment]
This should be added to the latest release.
