### ISSUE TITLE
Links to compendium / world entities are mistakenly opened as a journal entry

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#15]
tested on foundry 0.8.6, DnD5e 1.3.3

If a Journal Note contains an embedded link to an entity clicking on the link opens an empty page instead of opening the entity sheet.

![CleanShot 2021-06-01 at 23 03 20](https://user-images.githubusercontent.com/6490765/120390913-99223580-c32e-11eb-9237-0424b5c1ef61.png)
![CleanShot 2021-06-01 at 23 04 39](https://user-images.githubusercontent.com/6490765/120390927-9de6e980-c32e-11eb-9265-983c0531d603.png)

**Comment by ironmonk88** [comment]
Updated this so that only Actors or other Journal notes are opened in Enhanced Journal.

**Comment by Turqueso** [comment]
Can't open journal entries from the compendium, I have to import then to the game
