### ISSUE TITLE
PF2e info block styling not worki ng

### ISSUE THREAD

**Issue by Shenanigan83** [ironmonk88/monks-enhanced-journal#151]
When editing a journal entry. info block styling shows properly. The blockquote styling doesnt show properly though

<img width="521" alt="image" src="https://user-images.githubusercontent.com/81721224/147414359-7222118e-155b-4177-b0e3-4bd51bc3492f.png">

When not editing. info block doesnt show neither do the blockquote

<img width="515" alt="image" src="https://user-images.githubusercontent.com/81721224/147414343-e8397ace-f64a-4c66-826f-33c7221c8a2b.png">

I disabled the module and both info block and blockquote works fine.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/81721224/147414285-b38c0c03-1101-4798-b5b7-9cc588baa255.png">

**Comment by ironmonk88** [comment]
This should be added to the latest release.
