### ISSUE TITLE
(5e) Can no longer open journal entries after update to V9

### ISSUE THREAD

**Issue by nirurin** [ironmonk88/monks-enhanced-journal#152]
![Screenshot 2021-12-27 040026](https://user-images.githubusercontent.com/3751273/147433017-481204ca-6114-448b-a3cf-b7f3784455ad.png)

Thats the error that seems to get thrown. If I disable this module, I can then open the entries as just the default journal, but I can't open or create new enhanced journal entries when it is running. 

I saw another issue thread mention that there's a known issue with journals that weren't created using 'enhanced journal', but all my journal entries were originally created using it. (Plus I can't create any new ones now either).

**Comment by ironmonk88** [comment]
Try deselecting Lib: Document Sheet Registrar.
It used to be a dependent module, but since v9 Enhanced Journals can use core functionality.
Unfortunately the library module is causing conflicts.

**Comment by nirurin** [comment]
Not a problem, that fixed the issue :) thankyou

**Comment by ironmonk88** [comment]
Glad it got fixed.  :-)
