### ISSUE TITLE
Header area of entries are broken

### ISSUE THREAD

**Issue by aranian** [ironmonk88/monks-enhanced-journal#153]
The 1.0.38 update broke the styling on the quest availability status box:
![image](https://user-images.githubusercontent.com/731750/147499985-b5cf415e-9da8-4ab0-aac3-b93a0ff801f5.png)
Either the font is too large or the box too small.
In addition, the general alignment seems to be off:
![image](https://user-images.githubusercontent.com/731750/147514645-0224a023-7c63-40bf-8e81-8e19497ef029.png)

Amazing work with the quest improvements otherwise! I'm very happy right now :)

**Comment by ironmonk88** [comment]
Well... I tried to fix it.  But PF2E styling is preventing me from fixing this.
I'll keep working on it.

**Comment by ironmonk88** [comment]
I believe this has been fixed.
