### ISSUE TITLE
in foundry v9.238 and and enhanced journal 1.0.38 - can't open any journal entries

### ISSUE THREAD

**Issue by jcolson** [ironmonk88/monks-enhanced-journal#157]
receive this error in console:
```
Uncaught TypeError: setting getter-only property "type"
[Detected 2 packages: monks-enhanced-journal, lib-wrapper]
    openJournalEntry monks-enhanced-journal.js:581
    clickDocumentName monks-enhanced-journal.js:154
    call_wrapper libWrapper-wrapper.js:611
    _onClickDocumentName#0 libWrapper-wrapper.js:184
    jQuery 2
monks-enhanced-journal.js:581:13
Uncaught TypeError: setting getter-only property "type"
[Detected 2 packages: monks-enhanced-journal, lib-wrapper]
    openJournalEntry monks-enhanced-journal.js:581
    clickDocumentName monks-enhanced-journal.js:154
    call_wrapper libWrapper-wrapper.js:611
    _onClickDocumentName#0 libWrapper-wrapper.js:184
    jQuery 2
monks-enhanced-journal.js:581:13
Uncaught TypeError: setting getter-only property "type"
[Detected 2 packages: monks-enhanced-journal, lib-wrapper]
    openJournalEntry monks-enhanced-journal.js:581
    clickDocumentName monks-enhanced-journal.js:154
    call_wrapper libWrapper-wrapper.js:611
    _onClickDocumentName#0 libWrapper-wrapper.js:184
    jQuery 2
```

**Comment by chturner94** [comment]
Receiving the Same error. I have located the break point in the code as it's registered on my side. 

File: monks-enhanced-journal.js | line: 581
document.data.type = (entrytype == 'journalentry' || entrytype == 'oldentry' ? 'base' : entrytype);

I can verify that the console error I'm receiving matches (In the OP post it indicates line 581 as well).
Additional errors that differ from OP:
clickNote monks-enhanced-journal.js:196

Issue may be with Libwrapper, or an issue with EJ not properly functioning with LibWrapper. here is the entire log in case it's helpful (including the breakpoints with foundry and libwrapper)
Uncaught TypeError: setting getter-only property "type"
[Detected 3 packages: monks-enhanced-journal, lib-wrapper, zoom-pan-options]
    openJournalEntry monks-enhanced-journal.js:581
    clickNote monks-enhanced-journal.js:196
    call_wrapper libWrapper-wrapper.js:611
    _onClickLeft2#0 libWrapper-wrapper.js:184
    callback foundry.js:23985
    _handleClickLeft2 foundry.js:24189
    _handleMouseDown foundry.js:24151
    call_wrapped libWrapper-wrapper.js:502
    _handleMouseDown_Wrapper zoom-pan-options.js:194
    <anonymous> zoom-pan-options.js:341
    call_wrapper libWrapper-wrapper.js:611
    _handleMouseDown#0 libWrapper-wrapper.js:184
    emit index.js:181
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8
    addEvents interaction.min.js:8
    setTargetElement interaction.min.js:8
    r interaction.min.js:8
    initPlugins core.min.js:8
    r core.min.js:8
    create core.min.js:8
    po core.min.js:8
    t app.min.js:8
    initialize foundry.js:19616
    initializeCanvas foundry.js:5614
    setupGame foundry.js:5484
    _initializeGameView foundry.js:6434
    _initializeView foundry.js:6410
    initialize foundry.js:5380
    call_wrapped libWrapper-wrapper.js:502
    libWrapperInit libWrapper-api.js:776
    initialize#0 libWrapper-wrapper.js:182
    <anonymous> foundry.js:62192
    async* foundry.js:62174

**Comment by ironmonk88** [comment]
It's an issue with Lib: Document Sheet Registrar.
It used to be a dependent module, but isn't anymore.  Unfortunately it's causing issues.
Disabling it should clear up the issue.

**Comment by chturner94** [comment]
https://discord.com/channels/170995199584108546/722566083499786352/925114767901851698. The dev posted this in the discord @jcolson . You can fix the issue by disabling the Document sheet Registrar. I believe it's an old dependency that is no longer required.

**Comment by chturner94** [comment]
@ironmonk88 I guess you beat me to it! Thanks Monk!

**Comment by jcolson** [comment]
Thanks, uninstalling that module did the trick.
