### ISSUE TITLE
 Cannot read property 'history' and 'entittyId' of undefined on FoundryVTT 0.8.6

### ISSUE THREAD

**Issue by p4535992** [ironmonk88/monks-enhanced-journal#16]
**Environment Details**

Foundry VTT Version: 0.8.6

Operating System: \[Linux\]

How Are You Using Foundry: \[Linux,Native Application (Electron), Chrome\]

Which Game System: Dungeons and Dragons 5th Edition, version 1.3.4

Modules Enabled?: Yes

Module version: 1.0.6

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

![alt](https://i.imgur.com/ncHNDh7.png)

**Comment by ironmonk88** [comment]
What were you doing when you go the error?

**Comment by p4535992** [comment]
I just try to open a journal (any journal), but i just testedt is some migration issue from a old world 0.7.9 to 0.8.6 the same resources putted in a new world 0.8.6 don't launch the error.
For anyone encounter the same error.
