### ISSUE TITLE
Slideshow Feature / Pop out mode  / Pause Stop button not appearing

### ISSUE THREAD

**Issue by Nostalgia2046** [ironmonk88/monks-enhanced-journal#162]
Hello there

I wanted to know if it was to make the **Slideshow**  work and compatible while in "**Pop Out**" mode https://foundryvtt.com/packages/popout. 

I took a video screenshot. While the slideshow screen is in "pop up" mode, I can see and press the play button. But the pause or stop button doesnt appear. I have to pop in the window back to make them appear :

https://user-images.githubusercontent.com/97110801/148078584-c5eebfc9-7451-4a54-962b-5de84b7c2acf.mp4

Thanks in advance, I really adore this feature as its perfect for my Rp moments with my players.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.

**Comment by Nostalgia2046** [comment]
It's working perfectly, thank you so much @ironmonk88  !
