### ISSUE TITLE
Impossible to create Person or POI in v9

### ISSUE THREAD

**Issue by Clashsoft** [ironmonk88/monks-enhanced-journal#165]
After clicking "Save Entry", it redirects to `https://mydomain.com/game?name=<entry name>&folder=<folder id>&mce_12=<entry description>&submit=`, which looks like a broken version of Foundry as described in #160. After deleting the extra query parameters, it reloads and works again, but the original entry is not saved.

Affected entry types:

- [ ] Person
- [ ] POI
- [ ] Everything with a "Save Entry" button (?)

Unaffected entry types:

- [x] Enhanced Journal entry

Editing a Person is also broken:

<img width="715" alt="Screenshot 2022-01-08 at 17 18 52" src="https://user-images.githubusercontent.com/4145923/148651598-dbd0edeb-6189-48b5-b5f2-4146db7c9fde.png">

```
Chrome v97.0.4692.71
FoundryVTT v9.238
DnD5E v1.5.6
Monks Enhanced Journal v1.0.39
Document Sheet Registrar disabled
```

**Comment by arcanistzed** [comment]
This happens with `Enhanced Journal entry` for me as well on v9 build 242.

**Comment by Clashsoft** [comment]
@ironmonk88 any chance this will be fixed soon? The module is nearly unusable apart from regular journal entries due to this issue and #160.

**Comment by Clashsoft** [comment]
Actually, I just updated from 1.0.43 → 1.0.45 and the issue was fixed.
