### ISSUE TITLE
Can't Duplicate Entries

### ISSUE THREAD

**Issue by webmaster94** [ironmonk88/monks-enhanced-journal#171]
When attempting to use the Foundry duplicate option on a journal that is a special type (not a enhanced journal), the duplicate is made an enhanced journal and loses all information not in the details field. This is apparent if you convert it to the original type as all the info is not filled out. 

Foundry Version: 9 Build 242
Module Version: 1.0.39

**Comment by ironmonk88** [comment]
Closing this as I can no longer replicate, so I'm assuming it's been fixed.
