### ISSUE TITLE
Players can only write notes when they are the owener

### ISSUE THREAD

**Issue by Batziy** [ironmonk88/monks-enhanced-journal#172]
If players have observer permission they can see the note section but what they write wont save. and if they are owner they have access to sections they should not have access too. For example quest rewards and inventory management for shops. Would be nice if players could write their own notes directly on the journal entry instead of creating a separate one.

**Comment by ironmonk88** [comment]
They should be able to.  I think that was a bug that's been fixed.
Can you check to see if this is still an issue?

**Comment by Batziy** [comment]
Its still an issue :(

**Comment by ironmonk88** [comment]
I think that issue was fixed but I introduced another one.
Also locked down the notes if a GM isn't present, since it requires the GM account to actually save the data.
This should be fixed in the next release.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
