### ISSUE TITLE
Add styling for FateX pr Fallout

### ISSUE THREAD

**Issue by ironmonk88** [ironmonk88/monks-enhanced-journal#174]

**Comment by saif-ellafi** [comment]
Thank you for creating this, I will test other Systems I am using. Would love to use this module.
![image](https://user-images.githubusercontent.com/27952699/150391421-a2fc90bc-3eb8-44f5-8cb9-ee2dfe9d7929.png)

**Comment by saif-ellafi** [comment]
It seems any system that overrides .window-contents (very common) seem to have issues. This is for example Star Wars FFG
![image](https://user-images.githubusercontent.com/27952699/150392035-ccbf62f8-6900-42dd-822c-5b9b750f45ca.png)

**Comment by saif-ellafi** [comment]
A fix I would propose is to replicate core Foundry with
`background: url(../../../ui/parchment.jpg) repeat;`

**Comment by saif-ellafi** [comment]
Eh, not a so quick solution. Some systems also apply own font styles and color within the journal. Perhaps also setting some rules about text style will be needed.
![image](https://user-images.githubusercontent.com/27952699/150439050-fd632950-1f40-463e-a2eb-c087e3042e93.png)

**Comment by ironmonk88** [comment]
Closing this, as the original request has been completed.
System stylings need to happen on a per request basis since there's no real consistency.
