### ISSUE TITLE
[Bug] Cannot drag entries to relationship tab of a person entry

### ISSUE THREAD

**Issue by Krigsmaskine** [ironmonk88/monks-enhanced-journal#175]
I am unable to drag person, place or organization entries into the relationship tab of person entries. The console does not seem to output an actual error, this is with the module only enabled.

Foundry v9 242
DnD5e 1.5.7
Monk Enhanced Journal 1.0.40

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
