### ISSUE TITLE
v1.0.40 - ReferenceError: debugEnabled is not defined

### ISSUE THREAD

**Issue by coboye** [ironmonk88/monks-enhanced-journal#176]
on startup in console:
`monks-enhanced-journal.js:24 Uncaught (in promise) ReferenceError: debugEnabled is not defined
[Detected 1 package: monks-enhanced-journal]
    at warn (monks-enhanced-journal.js:24:5)
    at Function.fixType (monks-enhanced-journal.js:1487:17)
    at Function.ready (monks-enhanced-journal.js:869:38)
    at monks-enhanced-journal.js:1576:26
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5547:11)
    at async Game._initializeGameView (foundry.js:6479:5)
    at async Game.initialize (foundry.js:5415:5)`

monks-enhanced-journal.js:24
`export let warn = (...args) => {
    if (debugEnabled > 0) console.warn("monks-enhanced-journal | ", ...args);
};`

module list
`Active Modules:
----------
Advanced Macros v 1.13;
Advanced Spell Effects v 0.9.0.2;
Automated Animations v 1.2.7;
Automatic Journal Icon Numbers v v1.7.2;
Babele v 2.2.2;
Changelogs & Conflicts v 0.7.7;
Cleaner sheet title bar v 1.3.4;
Combat Enhancements v 1.1.0;
Combat Numbers v 1.2.1;
Core Italian Translation v 0.27;
Custom Fonts v 0.2.1;
Danger Zone v 1.3.6;
DFreds Droppables v 1.4.0;
Dice So Nice! v 4.3.1;
Dice Tray v 1.4.2;
Easy Target v 2.14;
FXMaster v 2.2.2;
GM Screen v 2.9.0;
Health Estimate v 2.6.23;
Illandril's Hotbar Uses v 2.3.7;
Illandril's Token HUD scaler v 1.4.3;
Illandril's Token Tooltips v 2.8.2;
Initiative Double Click v 1.5;
Italian Modules Language Pack v 0.5;
JB2A - Patreon Complete Collection v 0.3.4;
Kandashi's Fluid Canvas v 0.3.0;
Koboldworks – Ammo Recovery for PF1 v 1.2.0;
Koboldworks – Item hints for Pathfinder 1e v 1.4.0.5;
Koboldworks – Little Helper for Pathfinder 1e v 0.1.0.2022012113;
Less Fog v 0.9.0;
lib - Color Settings v 2.8.2;
Lib: Document Sheet Registrar v 1.0.0;
Library: DF Hotkeys v 2.3.5;
Library - Find the Path v 1.5.1;
libWrapper v 1.11.4.0;
Loot Sheet NPC Pathfinder1 v 3.0.0;
MiniMap v 0.0.14;
MKAh/Latency v 0.1.7;
MKAh/PF1/Container Contents v 0.1.2.1;
Monk's Active Tile Triggers v 1.0.50;
Monk's Enhanced Journal v 1.0.40;
Monk's Little Details v 1.0.43;
Monk's TokenBar v 1.0.61;
Monk's Wall Enhancement v 1.0.6;
Pathfinder 1e Archetypes and Abilities v 0.2.2;
Pathfinder 1e Content v 0.2.3;
Pathfinder 1e Journals v 0.1.3;
Pathfinder Italian Translation v 0.1.4;
Perfect Vision v 3.5.6;
Permission Viewer v 0.9.3;
PF1 Might Morphin Mod v 0.3.3;
Pings v 1.3.0;
Quick Insert - Search Widget v 2.6.1;
Sequencer v 2.0.9;
Settings Extender v 1.2.0;
Shared (Shared Compendiums) v 1.0;
SmallTime v 1.13.10;
Smart Doors v 1.3.2;
socketlib v 1.0.10;
SortableJS v 1.14.0-fvtt1;
Spellcaster utility for PF1 v 1.0.0;
Splatter v 2.9.3;
Split Journal v 1.1;
Stream View v 0.4.2;
Tagger v 1.2.3;
The Furnace v 2.6.1;
The Rollsmith - Iridescent Rainbow Dice Set v 1.0.0;
Tidy UI - Game Settings v 0.1.30;
TinyMCE toolbar config v 0.0.4;
Token Info Icons v 2.3.5;
Tokenizer v 3.5.0;
Token Magic FX v 0.5.3;
Torch v 1.4.3;
Trigger Happy v 0.8.34;
Tweak Playlist v 0.4.5.11;
Universal Battlemap Importer v 2.2.1;
Wall Height v 3.6.0.2;
Warp Gate v 1.13.4;

**Comment by coboye** [comment]
previous versione work fine (v1.0.39)

**Comment by ironmonk88** [comment]
Error has been fixed.
In the meantime if you disable the module `Lib: Document Sheet Registrar` will go away.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
