### ISSUE TITLE
Problem with quantity when purchasing in shop

### ISSUE THREAD

**Issue by playest** [ironmonk88/monks-enhanced-journal#178]
I tried the Shop sheet with a shop that was selling rations and to my surprise it kind of "duplicates" items.

I had 10 rations in the shop and clicked on purchase and I found myself with 10 rations on my character sheet and 9 in the shop. I think we should set quantity to 1 at [line 290 of ShopSheet.js](https://github.com/ironmonk88/monks-enhanced-journal/blob/c49d8c2b3ae66b07492c18fb4ac4bf7290182185/sheets/ShopSheet.js#L290)

More over, no amount of GP (I'm using DnD5e) has been removed from the game so the item is basically free. I haven't been able to find the source of this problem.

I think this is all very promising :)

**Comment by Killasaurus-Warbear** [comment]
Having the issue with quantity purchased and not removing GP/SP/CP etc. If I set "Player Purchasing" to "Request Purchase", the currency is removed from the player's sheet when approved.

**Comment by ironmonk88** [comment]
I think this should be fixed for the next version.
It ended up being in a lot more places than just that.
So no more amazing deals from the shop keepers.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
