### ISSUE TITLE
[Suggestion] Autosave

### ISSUE THREAD

**Issue by Baxmann** [ironmonk88/monks-enhanced-journal#18]
The amount of times I've swapped tabs and lost my progress is ridiculous. If there's a way to add it in, can you please add it?

**Comment by ironmonk88** [comment]
Should be fixed in 1.0.7
Can't guarantee I caught everything but I definitely found some spots that weren't saving like they should have.

Let me know if it's still an issue and what things aren't being saved.

**Comment by Baxmann** [comment]
Changing Tabs or Opening a different journal entry to be specific. If the changing tab could be saved I'd be happy enough.

**Comment by Baxmann** [comment]
Or if the page gets reloaded, if you could figure that, that would be amazing.

**Comment by ironmonk88** [comment]
This should be fixed with an update to prompt you if you have unsaved changes in the editor window before closing the window.
