### ISSUE TITLE
(incompatibility) Can't access custom styles when using custom jouurnals

### ISSUE THREAD

**Issue by Orionox** [ironmonk88/monks-enhanced-journal#180]
so I like the "read aloud" custom style form enhanced journals, but that can't be accessed while also using custom journals. The entire button for enhanced journals styles is missing when custom journals are activated. I know its not your responsibility to make your stuff compatible, butt it would be nice if they were.

**Comment by ironmonk88** [comment]
I believe this has been fixed.
And MEJ does also have the read aloud style.
