### ISSUE TITLE
Unable to remove relationships

### ISSUE THREAD

**Issue by FadedMaster** [ironmonk88/monks-enhanced-journal#182]
Once someone or something has been dragged onto an entry under relationships, there is no obvious way to remove the relationship.

![image](https://user-images.githubusercontent.com/85941405/151706833-436cb629-6928-48f9-ac13-5b39b94d2c36.png)

**Comment by ironmonk88** [comment]
Huh.  You're right.  I'll get that fixed.  :-)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
Trash can was there, I just set up the check wrong and it was always hiding it.
