### ISSUE TITLE
[Question] Make UI Available to players?

### ISSUE THREAD

**Issue by cswiatek** [ironmonk88/monks-enhanced-journal#183]
Is there a way to have this module function for players (not just DM) so they can navigate public journal entries with the tabbed interface, forward/backward buttons, sidebar, and so on?

**Comment by FadedMaster** [comment]
Go to settings (the gears in the top right), click on the "configure settings" button, then the "module settings" tab, scroll down to the "Monk's Enhanced Journal" and check the box labeled "Allow players"

**Comment by ironmonk88** [comment]
Closing this because FadedMaster pretty much answered the question.  :-)
