### ISSUE TITLE
[Bug] Person Entry: Short Term Goals does not appear

### ISSUE THREAD

**Issue by FadedMaster** [ironmonk88/monks-enhanced-journal#184]
When creating a "person" journal entry and enabling "Short Term Goals" no entry box appears for this.

![image](https://user-images.githubusercontent.com/85941405/151706775-391e3990-54f5-415c-8963-d716afe9a93c.png)

**Comment by ironmonk88** [comment]
Helps if you spell it properly.
Apparently the person had shirt term goals.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
