### ISSUE TITLE
Feature Request: Sort order for Townsfolk, Shops in "Places" journal

### ISSUE THREAD

**Issue by Romaq** [ironmonk88/monks-enhanced-journal#186]
I have a town full of "People of Interest" as well as "Shops/ Points-of-Interest". For sane sorting, I have them in a folder by family name then given name. Unfortunately, as I bring them into the town "location" (the Townsfolk tab), they lose their convenient sorting. This is also true on the Shops tab. Is it possible to add sorting as an option? Or would I be missing something?

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
