### ISSUE TITLE
Bug: Interaction with Monk's Active Tile Triggers while GM is online

### ISSUE THREAD

**Issue by Hemasku** [ironmonk88/monks-enhanced-journal#189]
For reference, all players were given observer level permissions for these journals utilized in these images.

When attempting to utilize the following setup for Monk's Active Tile Triggers: 
![image](https://user-images.githubusercontent.com/98923739/152253388-dfdff620-de72-4697-b67f-0c326e5f8c2e.png)

While the GM is online, a player who interacts with the tile will be shown the following journal (note that the sidebar is missing):
![image](https://user-images.githubusercontent.com/98923739/152253492-8a841026-1c47-43a1-8deb-50343a26ed95.png)

However, if the GM is not online on the world, the tile then generates the correct Monk Enhanced Journal:
![image](https://user-images.githubusercontent.com/98923739/152253608-1f297d53-e387-42ab-9d48-219c90bcad2d.png)

**Comment by ironmonk88** [comment]
I believe this has been fixed.
