### ISSUE TITLE
Fix for this._onShowPlayers is not a function

### ISSUE THREAD

**Issue by Dizzie42** [ironmonk88/monks-enhanced-journal#192]
Currently on updated versions (Monk's version 1.0.21) and (Foundry version 9) this error shows up in the console when trying to 'Right click -> Show Players' any picture in the journal.  This can be duplicated in Foundry games (locally) and hosted games such as The Forge

**Comment by ironmonk88** [comment]
Can you screenshot for me how you're trying to Show to Player?

**Comment by Melephisance** [comment]
![FVTT Screenshot 2022-03-12 064917](https://user-images.githubusercontent.com/96983231/158007529-1c95a2ce-b58f-41f9-be5c-1b9338754b73.jpg)

Here you go.

**Comment by ironmonk88** [comment]
I'd completely forgotten that I'd added that feature!
Should be fixed for the next release.
