### ISSUE TITLE
Feature Request Support of Journal Anchor Links

### ISSUE THREAD

**Issue by Ulvtand** [ironmonk88/monks-enhanced-journal#193]
https://github.com/aMediocreDad/jal

**Comment by cadowtin** [comment]
I second this

**Comment by jobyburk** [comment]
+1. I posted about this in Issue #177 .

**Comment by superseva** [comment]
It would be a great feature. Implementing this as JAL module does it would definitely bring even more enhancement to the already enhanced journal entries.

**Comment by ironmonk88** [comment]
Latest version has support for anchor links.
![image](https://user-images.githubusercontent.com/75920956/163219389-35341f8a-b845-4d26-805a-9bf5e7754840.png)

**Comment by jobyburk** [comment]
You are truly the king of Foundry modules. Thank you for all that you do!

**Comment by Allmight** [comment]
Not been able to get that one to work, and it looks more line an html anchor link, not a foundry anchor link. Not been able to figure out how it works in conjunction with foundry's @ links.

**Comment by jobyburk** [comment]
> Okay, this is HTML a links, and i kind of got it to work within the same journal entry. Now, how do i open another journal entry that takes me to a tag within that entry, from the first journal entry?
> 
> And i think the request was to use foundry links, like so... @JournalEntry[tmp2#anchorname]{anchorname in the tmp2 journal entry}

Does the anchor need to stay within the <a> tag that the Bookmark button creates? (I'm assuming you can just make an <a> tag to do this as well.)
