### ISSUE TITLE
Conflict with PdfToFoundry (PF2E)

### ISSUE THREAD

**Issue by Weissrolf** [ironmonk88/monks-enhanced-journal#194]
Hello.

When I import a PDF via PF2E's PdfToFoundry module then MEJ opens its window to display each imported journal entry the moment it is imported. This seems to slow down importing and may get slower and slower by time. Not entirely sure about the latter, though.

**Comment by ironmonk88** [comment]
I believe this was fixed.
But also closing due to cleaning up tickets, and not sure PDFoundry is really being supported since v10 has PDF support.
