### ISSUE TITLE
Odd numbers of coins left

### ISSUE THREAD

**Issue by Melephisance** [ironmonk88/monks-enhanced-journal#195]
Hello there - a small item but I wanted to rasie. If the amount of currency is odd, splitting the coins will leave a single coin undistributed by type.

Also a possible feature for the future would be a form that would allow the currency to be split in less regular / precise ways other than equal split. E.g. specify amounts by character, or a percentage calculation etc.

Thanks for the wonderful mod!

**Comment by ironmonk88** [comment]
Technically that's how I'd set it up.
For various reasons I'm not inclined to do conversions, and prefer to leave it up to the GM to make a conversion if they want to.

That being said, I've changed the way coins are split now, with a much better interface for seeing where the money is going, and the option to drop the remainder on an individual character.

Closing the ticket as changes have made it a moot point.
