### ISSUE TITLE
Journal Notes cross links doesn't work

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#2]
tested on foundry 0.8.5, DnD5e 1.3.2

If a Journal Notes contains a reference to another journal notes, clicking on that reference opens to a blank page. In addition, if you click on the history, you do not return to the previous page from which you clicked on the reference

![CleanShot 2021-05-31 at 10 06 30](https://user-images.githubusercontent.com/6490765/120162731-fae08380-c1f8-11eb-8dd2-d50f8306beb1.png)
![CleanShot 2021-05-31 at 10 06 56](https://user-images.githubusercontent.com/6490765/120162758-00d66480-c1f9-11eb-8d1f-5226950e509b.png)

**Comment by ironmonk88** [comment]
Fixed, will be in the next release.

**Comment by ironmonk88** [comment]
New Release has been uploaded.
