### ISSUE TITLE
[Feature Request] Compatibility with PDFoundry

### ISSUE THREAD

**Issue by bklick** [ironmonk88/monks-enhanced-journal#205]
Currently, PDFoundry PDF links are not clickable in Monk's Enhanced journal. (Alternatively, I am experiencing a strange bug?)

**Comment by ironmonk88** [comment]
Closing this... because I'm clearing out tickets, and in v10 PDFoundry is kind of obsolete?
Please re-open if you think it deserves to be looked into.
