### ISSUE TITLE
[Bug?] Following the upgrade to V1.0.46 all new Journal types default to the "default template"

### ISSUE THREAD

**Issue by pwatson100** [ironmonk88/monks-enhanced-journal#213]
Just updated and tried to create an Encounter (on The Forge) but the journal created seems to be the default journal no matter what Journal type I select without the usual header icons.   
![image](https://user-images.githubusercontent.com/19948257/155543583-b075c830-b45f-4824-a1d4-8b1c055e8919.png)

But if I leave it at the default (Enhanced Journal Entry) I get the expected layout and header: 
![image](https://user-images.githubusercontent.com/19948257/155543895-339e93ed-3974-4eb7-a61e-70c134a2541a.png)

Also converting an Enhanced Journal Entry to something else results in the default journal. 
Checking the console I am seeing these errors:
![image](https://user-images.githubusercontent.com/19948257/155545244-bc475334-b430-431a-8f0c-248c5a4f78fb.png)

I have really embraced the flexibility his module gives.  Many thanks for making and supporting it.

**Comment by ironmonk88** [comment]
I'm not getting any of those errors.
Can you check to see if there's a module interaction causing this?
Try it with a fresh world, with only Enhanced Journals installed.
Also... what system are you using?

**Comment by pwatson100** [comment]
Thank you for the fast response.  Good point.  Sorry I did not mention.  It's using the Coriolis system (2.6.12).  I tried it with all the modules disabled and still get the error.  Created a new (Coriolis) world and with only Enhanced Journals enabled get the error.  
I have also tried on my Alien RPG system and it works fine so it looks like there is something in the Coriolis system.  
It's odd because V1.0.45 worked fine with Coriolis.  

I think I have found the issue...  https://github.com/winks-vtt/yze-coriolis/issues/139  
Sorry for the false alarm.  Please feel free to close this issue.
