### ISSUE TITLE
Opening Journal Entries in Locked Compendiums Causes Errors

### ISSUE THREAD

**Issue by Armandeus66** [ironmonk88/monks-enhanced-journal#214]
I keep compendiums locked because I assume that will prevent problems.
When using Enhanced Journal and opening a journal entry in a locked compendium, an error similar to the following appears on screen, usually 3 times. Why is Enhanced Journal attempting to modify locked compendium journal entries?

`Uncaught (in promise) Error: You may not modify the dww-battlemaps.credits Compendium which is currently locked.
[No packages detected]
    at Function._canModify (/home/ubuntu/foundry/resources/app/dist/database/backend/server-compendium.mjs:1:752)
    at o.canUserModify (/home/ubuntu/foundry/resources/app/common/abstract/document.mjs:277:44)
    at ServerDatabaseBackend._updateDocuments (/home/ubuntu/foundry/resources/app/dist/database/backend/server-backend.mjs:1:3005)
    at async Semaphore._try (/home/ubuntu/foundry/resources/app/common/utils/semaphore.mjs:99:17)`

**Comment by ironmonk88** [comment]
I'm having a hard time replicating this issue.
What System you're using?
Have you tried with just Enhanced Journal enabled to make sure it isn't a module conflict?
Are you opening from an embedded link, or straight from the compendium?

**Comment by Armandeus66** [comment]
I am using Pathfinder 2E.
I will try with only Enhanced Journal and get back to you.

**Comment by ironmonk88** [comment]
Thank you!  I couldn't figure out where this was coming from, but once you mentioned that it was a document sheet registrar issue, I tracked down what was happening.
Enhanced Journal originally needed the sheet registrar but has since moved on to using core Foundry code to register sheets.  So it's probably a left over from that.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
