### ISSUE TITLE
Foundry v9 build 251 display issue

### ISSUE THREAD

**Issue by bnp800** [ironmonk88/monks-enhanced-journal#219]
After updated to foundry 9.251, the buttons are displaying strangely.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/69395973/156307568-e64fecf8-587f-4295-9223-6e3ccbde2f74.png">

**Comment by ironmonk88** [comment]
Shadow of the Demon Lord is going to need a complete make-over for all of the stylings at some point.

**Comment by bnp800** [comment]
> Shadow of the Demon Lord is going to need a complete make-over for all of the stylings at some point.

This happens not only in SoDL , but also in Pathfinder 1. 
I just used one of my clean world as a example.

**Comment by ironmonk88** [comment]
Styling should be fixed in the latest release.
