### ISSUE TITLE
Option to disable actor in enhenced journal or compatibility with pf2e actor

### ISSUE THREAD

**Issue by Shepardkx** [ironmonk88/monks-enhanced-journal#22]
The journal is not compatible with pf2e actor sheet. A quick fix for this would be to have a setting to deactivate this feature if possible. 

![image](https://user-images.githubusercontent.com/82629405/120837029-3c906780-c534-11eb-9ebc-fba589cb6f7e.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
I'm letting the sheet render itself instead of trying to copy the rendered data.
