### ISSUE TITLE
Currency Isn't Deducted From Shop Journal When Request Purchase Is Enabled

### ISSUE THREAD

**Issue by GameCrazed** [ironmonk88/monks-enhanced-journal#221]
Very much what the title says. If the Player Purchasing dropdown is set to Anyone then players can purchase anything they like and the currency is deducted accordingly. When it's set to 'Request Purchase' however, when I approve the transaction it gives the player the item but doesn't deduct their funds. No errors are reported in the console of either my browser (GM) or the player's. The only potentially suspicious thing I noticed was that the dialog window that appears in the chat log specifies "___ wants to **take** an item" not buy/purchase.

![image](https://user-images.githubusercontent.com/7393464/156455818-13a71ac2-4f7c-4026-88b7-e6fd9d4fc716.png)

I've tested this on a separate Foundry instance with no other modules (just the 5e game system module) and it also occurs there. If any other info is needed I'm happy to oblige.

**Comment by Tam1974** [comment]
Yes. This. I was about to ticket this very same issue myself. I like the "request purchase", better than "Anyone", because I get to see what the Players are buying and I get to modify the prices if the shop keeper likes them, and it's great Role Playing, and bartering. The "Anyone" works as per what GameCrazed states, and that's what I'm using until this is resolved. It is brilliant though - so keep up the great work.

**Comment by ironmonk88** [comment]
Could you check to see if this is still an issue in the latest version?

**Comment by GameCrazed** [comment]
Hi Ironmonk88. I've just tested again now and as of version 1.0.39 the ability to request purchase items from the shop appears to be working as intended. The popup in chat now reads "[PLAYER] wants to **purchase** an item" and the money looks to be getting deducted correctly from their character sheet for all currency types in the 5e game system.

Thanks for getting this sorted. Should be good to close the ticket now :)

**Comment by ironmonk88** [comment]
Yayyyy!!!
Closing the ticket.  :-)
