### ISSUE TITLE
On Loot Journals, the Invisible function is reversed

### ISSUE THREAD

**Issue by rtschaefer** [ironmonk88/monks-enhanced-journal#222]
When right-clicking onto the Loot Entry Item on the canvas, whenever I choose to make the item invisible (I activate the icon by making it orange), it actually becomes visible to players, and conversely, when I change it back to visible (turn off the orange activation on the right-click icon option), the players can no longer see it.  

This is easy to navigate around so it isn't a critical bug, just something to add to the list at some point. I double checked and all other assets (Monsters, tiles, drawings, etc.) all toggle invisible correctly, so it is isolated to this module.  By the way.... the module is AWESOME!

**Comment by ironmonk88** [comment]
Should have been fixed in the last release.
