### ISSUE TITLE
Shop addition/subtraction is reversed in 1.0.48

### ISSUE THREAD

**Issue by Tam1974** [ironmonk88/monks-enhanced-journal#225]
When Players purchase from the shop in "Request Purchase", or "Anyone", they receive the goods but the costs for those goods, are added to their cash inventory, not deducted. So they are getting the goods, plus what the goods cost.
And vice versa - when a Player sells goods, instead of gaining the purchase of the sale of the goods, it is being deducted from their cash inventory - so they are losing the goods and losing the cost of them as well.
Hope this makes sense.
For now I have reverted back to 1.0.47 and using "Anyone" - this works.

**Comment by ironmonk88** [comment]
This should have been fixed in 1.0.49
