### ISSUE TITLE
[Feature Request] Add more options to the Drag and Drop of a faction's relationships.

### ISSUE THREAD

**Issue by turboraton** [ironmonk88/monks-enhanced-journal#227]
![image](https://user-images.githubusercontent.com/70917100/157271464-b1fe21d8-954b-4ad8-8a82-7ee5e49c09a3.png)

I believe adding the option to drag an ORGANIZATION for example (among others) to the Relationships tab would be cool.

Also, many, MANY thanks for your great modules!

**Comment by ironmonk88** [comment]
This should be added to the latest release.
