### ISSUE TITLE
Can't save changes to Enhanced or Regular Journal Entries

### ISSUE THREAD

**Issue by Thuckenstein** [ironmonk88/monks-enhanced-journal#228]
This worked fine before the newest Foundry VTT update, and hotfix to v255.
After the update to v255, cannot save any changes made to regular, or enhanced journals.
I can creature a new regular journal and click the text tab. When closed it will retain anything entered the first time, but then re-opening the journal will no longer save any changes made. Enhanced journal entries will save blank and not record any changes right from creation.

All other journal entries types, for example, encounter, person, location, and every other types tried so far work fine and save the changes.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
