### ISSUE TITLE
Converting a journal entry to a Place makes entry unusable

### ISSUE THREAD

**Issue by jjhritz** [ironmonk88/monks-enhanced-journal#229]
All the text goes away, the UI elements of a Place fail to appear. 

Normal journal entry:
![image](https://user-images.githubusercontent.com/17412506/157815461-3c82f280-e7a2-4ced-91fd-e8d568ca16cb.png)

After clicking Convert > Place
![image](https://user-images.githubusercontent.com/17412506/157815584-e5ce5a83-26b6-4b9f-83a8-adc22bf93970.png)

All of the buttons disappear, too, so there's no way to convert the entry back to normal.

The entry still exists, and if you copying it using the context menu in the organizer, the new copied entry retains all the original text. So this isn't a _destructive_ issue, but it does require relinking all instances of the entry as you come across them.

-------------

Foundry version: 0.9.255
Game: DnD 4th Edition 0.2.69
Monk's Enhanced Journal 1.0.49

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
