### ISSUE TITLE
add configuration for other system currency (feature request)

### ISSUE THREAD

**Issue by patrickmohrmann** [ironmonk88/monks-enhanced-journal#230]
Hi, 

I would like to request the possibility to change check data path for the currency in the loot sheet to some other data than the D&D path. Other systems have (sadly) a different structure and data. it would be nice to have it configurable

**Comment by ironmonk88** [comment]
Closing this, as it's a dangerous thing to add customizability for people who don't know what they're doing.
MEJ does add support for other systems currency, but it needs to be coded into it.  And usually done on a per request basis.
That way it's not up to the individual to edit their currency every time, but up to MEJ to handle it.
If there's a system you'd like to support, please open a ticket for that system and I'll add currency details for it.
