### ISSUE TITLE
Add option to open actor links in a different tab instead of inside Monk's enhanced journal

### ISSUE THREAD

**Issue by etriebe** [ironmonk88/monks-enhanced-journal#236]
Since Tidy5e is completely broken inside Monk's, I think having this as an option would be preferrable and possibly easier to implement.

**Comment by etriebe** [comment]
Note, this is broken when in popout mode.

**Comment by ironmonk88** [comment]
Hold down Alt while clicking on the Actor to open in it's own window.

**Comment by ironmonk88** [comment]
Closing this as there is a workaround.
