### ISSUE TITLE
Encounter items dragged from a Compendium cannot be assigned to PC due by error

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#24]
tested on foundry 0.8.6, DnD5e 1.3.2.

In a Journal Encounter, dragging the elements from a compendium (which is more typical than using items from the world), the assignment of these items to the PC via drag & drop returns an error:

![CleanShot 2021-06-07 at 10 04 45](https://user-images.githubusercontent.com/6490765/120981280-d136d780-c777-11eb-96fe-3cddb022c06e.png)

The problem is due to the absence of the origin pack info in the dragged data, necessary for Foundry to import the item and copy it on the sheet:

![CleanShot 2021-06-07 at 10 07 35](https://user-images.githubusercontent.com/6490765/120982967-8b7b0e80-c779-11eb-8601-dd555eec701d.png)

if I drag from a compendium onto the sheet:
![CleanShot 2021-06-07 at 10 08 19](https://user-images.githubusercontent.com/6490765/120983595-2378f800-c77a-11eb-81bc-b99535def259.png)

**Comment by ironmonk88** [comment]
pack was added to Quest... but was left off of Encounters.
Will be fixed int he next release.

**Comment by ironmonk88** [comment]
Added to the latest release.
