### ISSUE TITLE
Loot journal item list doesn't fit in the window and can't scroll to bottom

### ISSUE THREAD

**Issue by madcatprimary** [ironmonk88/monks-enhanced-journal#240]
The loot list inside a loot journal entry cannot display all items once there are more items than the window can fit. The scroll handle disappears below the bottom of the window, and the last few items are obscured beyond the bottom of the pane. Resizing the window doesn't help. The only way to retrieve the items is to start moving the things above them to another location until the item count is below the display limit for the pane.

**Comment by madcatprimary** [comment]
Here's an example. This loot journal has another section that can't be displayed. If I back out a bunch of items you can see that there's a weapon subsection containing another item. As I add items back in, I find that I don't get a scroll bar handle until the bottom subsection has been pushed off the screen. When the grab handle appears, I'm not able to see more that the first item in the next section of the journal. If I add items to other subsections, those subsections will show up, but the bottommost subsection will always be hidden, and most of the items from the second bottommost subsection will be hidden. 

![Loot_Journal_Snip](https://user-images.githubusercontent.com/67210079/162774722-1e274ee0-57ff-41d5-8ea6-084fae46d169.jpg)
![Loot_Journal_Snip_2](https://user-images.githubusercontent.com/67210079/162776199-b4dec3d6-3850-4f76-b1c1-faa422eb5c6a.jpg)
![Loot_Journal_Snip_3](https://user-images.githubusercontent.com/67210079/162776201-b9912e7b-9f28-438e-8f8c-47c40c31a583.jpg)
![Loot_Journal_Snip_4](https://user-images.githubusercontent.com/67210079/162776204-795426bb-9c0b-4ba6-aabc-85ec4b6d9c88.jpg)
![Loot_Journal_Snip_5](https://user-images.githubusercontent.com/67210079/162776205-8802bb26-98af-4ef1-891d-d79dbf977c5e.jpg)

**Comment by madcatprimary** [comment]
I'm using PF1E for that game.

**Comment by ironmonk88** [comment]
Thank you!  :-)  Looks like it's a strange styling in PF1E.
That should also be fixed in the next patch.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
