### ISSUE TITLE
Linked Actors in Journal Entries are only visible if the player has Observer or higher permissions. Basic journal entries allow visibility at Limited or higher.

### ISSUE THREAD

**Issue by Masterfuzzfuzz** [ironmonk88/monks-enhanced-journal#242]
So I use several actor links in most of my journal entries. They work as normal if the player has "Observer" level permissions. However, this is too high of permissions to give my players. Basic journals allow linked actor visibility at "Limited" or higher permissions. Is this a limitation of the module or something that can be fixed? I do not want to make "Person" journal entries as I have several other modules that interact with NPCs and require them to be actors.

Here is the source of the journal from the DM's perspective
![JE - Source](https://user-images.githubusercontent.com/12419144/159603972-f3bf417c-4595-4c8a-9656-4ebafe58545b.PNG)

Here is what the player sees if they have "Observer" permissions
![JE - Player as Observer](https://user-images.githubusercontent.com/12419144/159603970-314c0c9d-8bae-400b-ba1b-4d01d6202fbf.PNG)

Here is what the player sees if they have "Limited" permissions
![JE - Player as Limited](https://user-images.githubusercontent.com/12419144/159603969-18d3ae2b-dd3c-4d89-a2cb-5ef156e3a7f6.PNG)

**Comment by BenChand** [comment]
@Masterfuzzfuzz Did you resolve this somehow in your settings? I'm having the same issue
