### ISSUE TITLE
Improvement: Open monster details from encounter

### ISSUE THREAD

**Issue by FreyrGudmundsson** [ironmonk88/monks-enhanced-journal#243]
In the Encounter journal entry, on the Monster tab, after adding a monster to the encounter, it would be great to be able to open the monster details page by clicking on the monster. Currently click, doubleclick, and right click all do nothing.

**Comment by ironmonk88** [comment]
That used to work.  Tracked down the bug, and should be fixed in the next release.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
