### ISSUE TITLE
[Enhancement suggestion] Force unequipped and non-proficient items into Loot/Shop conversion

### ISSUE THREAD

**Issue by lucaspicerni** [ironmonk88/monks-enhanced-journal#249]
When converting combat actor to loot or dragging items from an actor's inventory to the shop note, the item is added as the current state (eg proficient and equipped). This can infringe on PCs' proficiencies, in addition to automatically equipping items. Would it be possible to force an item to be "unequipped" and marked as non-proficient when converted/placed in the Loot/Shop?

**Comment by ironmonk88** [comment]
Should be added to the latest release.
Although there's issues with it in PF2E.
