### ISSUE TITLE
[Compatibility suggestion] MEJ and Hide Player UI

### ISSUE THREAD

**Issue by lucaspicerni** [ironmonk88/monks-enhanced-journal#250]
MEJ shop sheet has a visual bug when used with [Hide Player UI module](https://github.com/gsimon2/hide-player-ui): when the Foundry  items tab is hided for players and you show a enhanced shop journal to players, the item session in the shop disappears, leaving only description, relationships and notes, so players cannot buy.

![image](https://user-images.githubusercontent.com/95550238/161879768-248e6a67-4b7e-4bec-8d97-27a341c52253.png)

**Comment by ironmonk88** [comment]
I think that should be an issue with Hide Player UI.
The css it's using is pretty broad and should probably be limited to just the sidebar directory.  Since MEJ wouldn't be the only one affected by the setting.

**Comment by ironmonk88** [comment]
Closing this as it's an issue with Hide Player UI.
