### ISSUE TITLE
Sidebar pushed out of visible area when saving from journal buttons

### ISSUE THREAD

**Issue by QuantumBob** [ironmonk88/monks-enhanced-journal#251]
When I edit the journal description text but don't change anything and then "save" with the button in the journal bar (<div class="nav-button edit" title="Edit Description"><i class="fas fa-pencil-alt"></i></div>) the sidebar is pushed out of the visible part of the window by the subsheet.
This doesn't happen when new text is added and either save button is presses.
See attached video for a better description!
PS thanks for all your great work.

https://user-images.githubusercontent.com/12417271/162422408-b7327fb2-da0b-4935-8dd5-664a58485acf.mp4

**Comment by ironmonk88** [comment]
What system are you using?

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
