### ISSUE TITLE
Compatibility with Shadowrun 5E Journal

### ISSUE THREAD

**Issue by madcatprimary** [ironmonk88/monks-enhanced-journal#255]
When Enhanced Journal is enabled in SR5, the journal entries lose the "Edit" button, and nothing can be seen in the entries. None of the custom journal types display any fields or tabs. You just get a blank entry with no ability to edit. While it doesn't seem like the Loot journal would overall be too compatible with SR5, the rest of the journal types seem like they would work well with the system.

**Comment by ironmonk88** [comment]
Closing this as I believe it has been fixed.
The edit button is visible and the Journal Entry contents appear.
If they still aren't for you, please run Find the Culprit to see if it's another module interfering and re-open the ticket.
