### ISSUE TITLE
Feature Request: Roll Requests Embedded in Journal Text

### ISSUE THREAD

**Issue by acd-jake** [ironmonk88/monks-enhanced-journal#259]
It would be great to be able to define and execute roll requests directly in the text of a journal entry, similar to what is already possible with DCs in encounters.

By having the dice prompt directly in the text, you have a powerful tool to make descriptions of rooms or story driven passages interactive with skill checks.

For example, when describing a statue, you could directly define the checks you can use to examine it (Arcane to investigate its Magic Aura, Craftsmanship to determine if parts are movable, Athletics to try to knock the statue over, and so on).

**Comment by ironmonk88** [comment]
You mean like...
`@Request[perception dc:15 silent fastForward rollmode:selfroll]{flavor text}` 
`@Contested[strength strength silent fastForward rollmode:selfroll]{flavor text}`

It requires using Monk's Tokenbar though to make the request.

**Comment by acd-jake** [comment]
That's more or less how I had imagined it. I was not aware that this is already possible. Is this already included in the documentation?

The icing on the cake would now be if the request could be defined UI-supported, e.g. via a button in the toolbar of the editor to insert it into the text, displaying the dialog for the DCs.

In any case, thanks for the quick reply.

**Comment by ironmonk88** [comment]
Added a button in the toolbar in a previous release.
Closing as I believe this has been covered.
