### ISSUE TITLE
Feature Request: Allow line breaks in Quest Objectives

### ISSUE THREAD

**Issue by GameCrazed** [ironmonk88/monks-enhanced-journal#261]
Just a little quality of life request to allow for some way to insert line breaks into a quest's objectives so that the text can be formatted nicer than a big ol' block of text. Could be via HTML styling like <br> or just inferred through double- carriage returns in the text.

It's probably something that'll end up waaay down the list but thanks in advance for looking at it all the same :)

**Comment by ironmonk88** [comment]
Changed it to using the text editor.  So you should have a lot more control over objectives.
