### ISSUE TITLE
Items pulled from rolltables fail to add more than 1 type of item at once

### ISSUE THREAD

**Issue by crazycalya** [ironmonk88/monks-enhanced-journal#263]
**Expected:** Drawing from a table with multiple shared results populates every item rolled. 

**Actual:** When rolling a table with multiple results for a single roll the shop-journal will only populate the first item. This was also tested on a fresh world (only Enahnced Journal active) with a fresh table, same result. 

_(This screenshot has BetterTables enabled but the bug occurs with fresh worlds too.)_
![Screenshot (64)](https://user-images.githubusercontent.com/9976394/163658537-af3911ee-34a3-4015-b80a-bc4e5e00e1ba.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
