### ISSUE TITLE
Shop permissions set to anyone but only GM can purchase.

### ISSUE THREAD

**Issue by sigshot552** [ironmonk88/monks-enhanced-journal#264]
Hello, I have been working on my shops for my campaign. I as the GM am able to purchase items for my players from the shop. However, If they try it wont even let them drag and drop the item. Shop permissions are set to open and anyone and the journal permissions are set to observer. 

I tried setting journal permissions to owner to see if there was a change but it was the same issue. Only the GM can currently purchase.

**Comment by sigshot552** [comment]
solved. Needed to have a GM present along with player

**Comment by ironmonk88** [comment]
Due to certain restriction within Foundry, a GM is required.
Closing as there is a solution.
