### ISSUE TITLE
Feature Request: Only Show Tabs Containing Information

### ISSUE THREAD

**Issue by patrickburk1988** [ironmonk88/monks-enhanced-journal#265]
It would be cool if tabs were only visible to players whenever they contained actual information. For example: if I have a Place journal entry that contains no shops, then the entry wouldn't display the "Shops" tab to players at all.

Alternatively, an "Edit Tabs" option (similar to "Edit Fields") would also allow us to manually remove tabs that aren't pertinent.

**Comment by Havoclivekiller** [comment]
This would be nice. I don't use tabs Details or Offerings on Person type journals. Would like to have the option to not be displayed (even for GM).

**Comment by ironmonk88** [comment]
You can now customize which tabs are shown in general and in specific to each Journal entry.
