### ISSUE TITLE
Journal links embedded in an entry remain a text string after saving entry

### ISSUE THREAD

**Issue by amcvfx** [ironmonk88/monks-enhanced-journal#27]
I find that Journal links in a journal entry don't automatically turn into clickable links right after saving the entry, I have to navigate away from the journal entry then come back to it for the link to work:

![image](https://user-images.githubusercontent.com/35099081/121189471-0cadd080-c862-11eb-938d-ecf82d57c261.png)

You can see the link hasn't updated in the screenshot.

**Comment by ironmonk88** [comment]
This should be fixed now.
