### ISSUE TITLE
Place Journal Entries not displaying correctly after last update.

### ISSUE THREAD

**Issue by Thuckenstein** [ironmonk88/monks-enhanced-journal#270]
When opening or creating a 'place' journal entry, items from the 'details' tab are displaying in the upper right corner of the 'description' tab. They appear in a undersized window with a scroll bar at the bottom. The usual icons for setting type style and text entry options are also not displaying. As well, the items that are supposed to display under the 'details' tab are not displaying properly.

![monk's-enhanced-journal-issues](https://user-images.githubusercontent.com/101313341/164878491-e8c15e1d-293a-4245-a1ae-e5075196f65b.png)

**Comment by ironmonk88** [comment]
What system are you using?  It's working correctly in DnD5e for me, so I suspect it might be an issue with another system's stylings.

**Comment by Thuckenstein** [comment]
Apologies, I didn't know it could react different to different systems. I have a number of them I run and use enhanced journals for them all. I was working in the Open Legend RPG system, which I realize is not a common one.

**Comment by ironmonk88** [comment]
Should be fixed in the next release.
The styling still needs some work.  There's always a lot of fiddling needed when adding a new system, but it should be usable.
I'm not sure when the next release will be, but I'd be more than happy to give you a link to my Discord server, where I announce when modules have been updated.

**Comment by Elio-87** [comment]
I think this is what happends when it interact with custom journal also; as my image is now a error link icon only.
