### ISSUE TITLE
[static getPrice(item, name)] Calculations incorrect for item templates with generic price value <1 when using currency conversion

### ISSUE THREAD

**Issue by DevConFox** [ironmonk88/monks-enhanced-journal#273]
## Settings
Foundry: v9.269 (latest stable)
System: dnd5e v1.5.7 (latest stable)
MEJ: 1.0.52

## Description
Altering the conversion settings to set a different currency (e.g. silver) as the default currency results in incorrect calculation of prices and currency when adding items to a shop, if the item template has a price < '1' (e.g. SRD items 'Torch' or 'Club').

I was able to narrow it down to this part of the getPrice function in the EnhancedJournalSheet.js:

` price = Math.floor(price * (10 ** (idx2 - idx)));`

If the item template uses a fixed currency (e.g. '1 cp' instead of '0.01'), getPrice works as expected.
In my example with SP as the standard currency, to have the 'Torch' show up with the correct calculation (= 1 cp), I had to change the code as follows:

` price = Math.floor(price * (100 ** (idx2 - idx)));`

So far, I was unable to find a generic solution that would work reliable with variable conversion rates and currencies.

## Additional screenshots
(left side: shop items, right side: item templates)
###### Custom Silver Standard (bugged)
Items, prices and cosst, after adding to the shop:
![image](https://user-images.githubusercontent.com/93077838/166105971-90ca6b5d-e893-4ba1-88e2-db7ff4b9fa61.png)

Items, prices and costs, after adjusting by 10x :
![image](https://user-images.githubusercontent.com/93077838/166106024-5e19cc1e-df26-46d3-b504-811fcd98356f.png)

###### For comparision: default dnd5e
Items, prices and cosst, after adding to the shop:

![image](https://user-images.githubusercontent.com/93077838/166106239-eeca052a-f024-45d9-88ea-0f7a5a9eb08f.png)

Items, prices and costs, after adjusting by 10x :
![image](https://user-images.githubusercontent.com/93077838/166106286-2320b622-08b0-4c2e-baeb-cbbdd96b4e58.png)

**Comment by ironmonk88** [comment]
Should be fixed in the next release.
Some leftover code when I wasn't allowing players to edit currencies.
Needed to be completely re-written.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
