### ISSUE TITLE
Purchasing fails in PF2E

### ISSUE THREAD

**Issue by Ro4m3r** [ironmonk88/monks-enhanced-journal#275]
Purchasing an item from a shop journal entry creates an invalid object under PF2E.

PF2E version 3.9.2.11293
FVTT version 9.268

![error](https://i.imgur.com/VkReyqk.png)
![error](https://i.imgur.com/UpMnRaX.png)

**Comment by Ro4m3r** [comment]
I'm not sure what went wrong initially, but after more testing and trying to attempt to fix the bug myself, it seems to work now. I have no idea what triggered it in the beginning, but maybe the stacktrace can help.

One thing I noticed was that originally while I was having the bug, the weapon (a greatsword in this case) appeared under the "Item" part of the shop, not under weapon. After deleting and reimporting the item, it now properly appears in the "weapon" tab, and purchasing works fine.

Maybe something broke during the import, I have no idea.

**Comment by Ro4m3r** [comment]
It seems the same issue (the carryType field being malformed) also prevents the object from being edited on the shop sheet. This error is thrown when I attempt to edit an item on the shop sheet, and nothing opens. Effects work fine.

![error](https://i.imgur.com/p43MwUh.png)

**Comment by ironmonk88** [comment]
I suspect that PF2E changed something about their item data structure.  And the item data in the shop was a snapshot of a previous version of the data structure.  And since technically items aren't items in a Journal Entry, PF2E didn't know to update them.  So deleting the item and re-adding it probably updated the item data with the correct data structure.

That's my best guess.  Has it occurred since you re-imported?

**Comment by Ro4m3r** [comment]
I just tried creating a new shop journal entry, and imported a greatsword from the compendium, added it to the shop items tab and attempted to edit the item. The item's cost and price are set to 0, even though a greatsword is worth 2 gp.

It throws 3 separate type errors:

![image](https://user-images.githubusercontent.com/21060784/168495707-1e6eb1cf-c7d3-4d60-b096-94e008a318a2.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
