### ISSUE TITLE
MEJ & Kult System incompatability

### ISSUE THREAD

**Issue by abcdeed7** [ironmonk88/monks-enhanced-journal#276]
When using MEJ & kult the style sheet of MEJ clashes with the style of kult such that some text is very very hard to read, pergaps a config option would help?

![image](https://user-images.githubusercontent.com/8314822/166407404-d98fff42-c77d-4a93-a99b-c5ebc93f87a3.png)

**Comment by abcdeed7** [comment]
hey! I learned some basic CSS and was able to fix the issue w/ the custom CSS module, here's what I used (it's messy & uses some personal pref things)
`/* Custom CSS */
:root {
  --color-text-dark-primary: #968c6a;
  --color-text-dark-secondary: #877E5F;
}
.monks-journal-sheet.sheet .form-group label {
    color: #968c6a;
}
.monks-journal-sheet.sheet .items-list .item .item-name {
    color: #968c6a;
}
.monks-enhanced-journal .tab-bar .journal-tab {
    background: rgba(34, 32, 33, 0.5);
    border: 1px solid #b5b3a4;
    font-family: "IM Fell Pica DW";
}
.monks-enhanced-journal .tab-bar .journal-tab.active {
    background-color: #000000;
}
#journal-directory .subdirectory {
    border-left: 4px solid rgba(0, 0, 0, 0.3);
    border-bottom: 4px solid rgba(0, 0, 0, 0.3);
    margin-bottom: 0px;
    width:100%;
}
#journal-directory li.folder > .folder-header {
    background: rgba(0, 0, 0, 0.8);
}
.monks-enhanced-journal .directory-sidebar {
    background: url(systems/D35E/ui/parchment-dark.jpg) repeat;
    border-left: 1px solid rgba(0, 0, 0, 0.1);
}
#journal-directory li.folder:not(.collapsed) > .folder-header {
    background: rgba(0, 0, 0, 0.6);
}
#journal-directory li.folder .folder-header h3,
#journal-directory li.folder > .folder-header .create-folder,
#journal-directory li.folder > .folder-header .create-document {
    color: #877E5F;
}
.tox.tox-tinymce .tox-edit-area__iframe {
  background: #391c18;
  border-top: 1px solid #968c6a;
}
.wound-name {
  background-color: #391c18;
}
.wound-section select {
  background-color: #391c18;
}.stability-section select {
  background-color: #391c18;
}
.monks-journal-sheet.sheet .editor .tox-toolbar-overlord {
  background-color: #391c18;
}
.tox :not(rect){
  background-color: #391c18;
}
.tox .tox-tbtn__select-label {
  background-color: #00000000;
}
.tox .tox-tbtn__select-chevron {
  background-color: #42160f;
}
.tox .tox-split-button svg {
  background-color: #391c18;
}
.tox .tox-split-button .tox-tbtn {
  background-color: #391c18;
}
textarea {
  color: #968c6a;
}
.monks-journal-sheet.sheet .recent-link {
    color: #968c6a;
}`

**Comment by ironmonk88** [comment]
Styles have been added to the latest version.
