### ISSUE TITLE
Infinite money glitch when selling (Shop journal)

### ISSUE THREAD

**Issue by XiaoKe89** [ironmonk88/monks-enhanced-journal#279]
When selling an item that has a qty greater than 1 but only selecting 1 to sell, after it is approved by the GM, the button to accept appears like normal but the button does not disappear and allows the player to press the button an infinite amount of times effectively duping it and selling it each time and it will not remove the item from the inventory even if the player clicks "cancel" or the GM clicks "Reject". Also the item does not get added to the shop, the player is left with as much money as they please and the item left over still. If the player offers the whole stack of items initially or the GM manually changes the qty to be the whole stack before sending the offer the behavior is normal and only sells once and removes from player inventory.

I have a lot of other mods but I tested this in a fresh world with only Enhanced Journal enabled and got the same error.
Using D&D 5e 1.5.7
Foundry V9 build 269
Using latest version of Enhanced Journal 1.0.56

and this message gets posted to the console:

"Uncaught (in promise) ReferenceError: actorItem is not defined
    at ChatMessage.acceptItem (monks-enhanced-journal.js:1847:59)
acceptItem
@
monks-enhanced-journal.js:1847
await in acceptItem (async)
dispatch
@
jquery.min.js:2
v.handle
@
jquery.min.js:2"

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
