### ISSUE TITLE
Suggestions: double-click to edit entries and others

### ISSUE THREAD

**Issue by amcvfx** [ironmonk88/monks-enhanced-journal#28]
I realise I'm posting a lot about this module and that's because I love it! I've switched over to it from OneJournal because of the awesome tabs and bookmark features but there are a couple of things I liked about OneJournal which would be awesome to see in this module:

- double click to edit a journal entry
- see permissions from Permission Viewer in the sidebar
- some options to control the size of the sidebar
- be able to change the colour of the journal Folder text. The dark grey is hard to read with some backgrounds and it doesn't follow the custom text colours in the actual Journal tab.

**Comment by ironmonk88** [comment]
I love all the suggestions.  The feedback is awesome!

**Comment by ironmonk88** [comment]
Permissions should now be visible.

**Comment by Shenanigan83** [comment]
I was about to write a suggestion about the font color text on the folder.. its hard to read, puting it back by default to white would be better in my opinion

![monk enhanced journal font color](https://user-images.githubusercontent.com/81721224/124191072-38069280-da91-11eb-9c86-691f6a5ec664.jpg)

I love this module.. so much stuff you can do with it :)

**Comment by ironmonk88** [comment]
font colour defaults back to white if there's a custom colour added.
