### ISSUE TITLE
Currency conversion not returning correct amount of currency in PF1E

### ISSUE THREAD

**Issue by Killasaurus-Warbear** [ironmonk88/monks-enhanced-journal#280]
When purchasing an item in PF1E the currency deducts properly from the larger denomination, but doesn't give the correct remainder after the purchase. In the images below purchasing 2 sp worth of an item while having 751 gp and 1 sp it should have finished with 750 gp and 9 sp. Instead it finished with 750 gp and 1 sp. I haven't been able to find a pattern in how much it returns to the smaller denomination, but it doesn't seem to be correct as far as I can tell.

Conversion Rate:

![Conversion Rate](https://user-images.githubusercontent.com/50350483/166873731-d039d23f-aa4d-4af2-980d-972c58b10dc9.PNG)

Before Purchase:
![Before purchase](https://user-images.githubusercontent.com/50350483/166873788-09ec7641-5cd6-4df2-a385-7a44a0fc5174.PNG)

After Purchase:

![After purchase](https://user-images.githubusercontent.com/50350483/166873809-fdf43cd1-da2f-433c-8a36-61819464c62e.PNG)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
