### ISSUE TITLE
Dropdow menu not appearing in shop journal

### ISSUE THREAD

**Issue by Darshyne** [ironmonk88/monks-enhanced-journal#282]
Hello there is a bug with the RPG UI (https://foundryvtt.com/packages/rpg-styled-ui)
The dropdown menu of the shop journal disappear.
![Capture d’écran 2022-05-06 à 15 10 37](https://user-images.githubusercontent.com/47222495/167152543-f713bbd2-02a9-4353-84a2-cab7affa3178.png)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
