### ISSUE TITLE
Option to remove folder navigation on the read journal window footer. 

### ISSUE THREAD

**Issue by jacksands** [ironmonk88/monks-enhanced-journal#284]
first thank you for the amazing module!

when using it with the Alien the rpg system the area with folder navigation became very large, making it difficult to use... 

since it seems to be only with alien system, could you look for the possibility to just hide this footer on the settings? 

anyway thank you for your time. 

Erich 

![Screenshot_2022-05-22-20-26-12-083_pl solidexplorer2_1](https://user-images.githubusercontent.com/7229143/169720650-2029150b-4b54-4f8c-b5f6-0c8b778dda1b.jpg)

**Comment by jacksands** [comment]
just a note...
 I used custon css module to add
 
 .monks-enhanced-journal .collapse footer {
    display: none;
}

and it is solved... I don't know if that mess with anythink else, but for the moment seens to be ok!

once again tks for your time!

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
Footer is still there, but it's sized properly.

**Comment by jacksands** [comment]
tks!!!
