### ISSUE TITLE
Permission Viewer Visual Conflict

### ISSUE THREAD

**Issue by pixelswirl** [ironmonk88/monks-enhanced-journal#285]
I'd really like a setting to show player permissions _only_ in the Enhanced Journal Entry pop-up, but not the default Journal Sidebar.  I use the Permission Viewer module since it shows permissions across all object types, but the two images overlap in the default sidebar when they are both turned on and it bugs me.  And of course if I turn off MEJ's permissions, it doesn't show in the Enhanced Journal entires.

**Comment by ironmonk88** [comment]
Added the option to view in both, just MEJ, and in neither.
