### ISSUE TITLE
DC rollable buttons broken

### ISSUE THREAD

**Issue by BarnabyssJones** [ironmonk88/monks-enhanced-journal#289]
In the Pathfinder 2e system, trying to insert DC rollable buttons and some other code into the journal doesn't work. For example, when entering " @Check\[type:fortitude|dc:20|basic:true] ", instead of popping up with a clickable button for a DC20 fortitude save in-line, it enters that phrase verbatim. The version is 3.10.4.11747

**Comment by Shenanigan83** [comment]
Yeah same issue. if I disable the module, it works fine.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/81721224/170874369-90255596-46ac-46fc-b7d6-d431f4f9f428.png">

**Comment by LonePaladin** [comment]
Any links generated by dragging items into a journal entry still work. It's only manually-created links (like the skill check above) that aren't converting correctly.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
