### ISSUE TITLE
Renaming Journals causes Foundry to reload

### ISSUE THREAD

**Issue by Baxmann** [ironmonk88/monks-enhanced-journal#29]
If I rename a Journal Entry, the website changes, and the name of the webpage link adds "?name=[Name+of+Journal]". Is this a foundry issue, an Issue with MEJ, or a thing on my side?

**Comment by ironmonk88** [comment]
Looks like it happens when you hit the enter key while in the text box.
If you just click off, it will save.
But I'll look into the issue to prevent that.

**Comment by ironmonk88** [comment]
Fixed in latest release.
