### ISSUE TITLE
[Feature Request] Shop/Currency support in Starfinder system

### ISSUE THREAD

**Issue by Grizwold53** [ironmonk88/monks-enhanced-journal#290]
Currently shops in the Starfinder system only work if a custom currency is used, and weapon attributes are not displaying (picture below). It would be great if this module could natively support the "credit" currency in Starfinder, and display weapon attributes on the shop screen.

![shop](https://user-images.githubusercontent.com/88157602/170752951-001a35f5-0466-499a-bdb4-e0c50e6f0331.PNG)
Shop is on the left, actor sheet showing weapon attributes on the right.

https://github.com/wildj79/foundryvtt-starfinder

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
