### ISSUE TITLE
BUG: Sound file in shop entry not working properly

### ISSUE THREAD

**Issue by Berytak** [ironmonk88/monks-enhanced-journal#292]
If you link a sound file to a shop entry, it only plays on "autoplay".

With autoplay active, you:

- can toggle play button off -> sound stops
- can toggle play button on again -> no sound
- can't toggle play button off again

With autoplay off, you cannot toggle the play button at all.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
