### ISSUE TITLE
[Enhancement] Make option to generate NPC chat bubble into configurable keybind

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-enhanced-journal#294]
Currently, all players must click a token if they wish to see chatter generated from a MEJ journal entry for the token. This makes it impossible for the GM to test. Furthermore, it conflicts with Smart Target's option to allow players to target tokens by clicking. Now that Foundry v9 has configurable keybinds, it would be great if we could set the keybind for triggering chat bubbles to whatever we wanted.

**Comment by ironmonk88** [comment]
Added a control to the token menu, so you can toggle it on and off.

**Comment by weepingminotaur** [comment]
That's a nice feature, but I don't quite understand how it will provide the enhancement I requested. :)
