### ISSUE TITLE
PF2's custom formats break

### ISSUE THREAD

**Issue by LonePaladin** [ironmonk88/monks-enhanced-journal#295]
PF2's system includes a set of custom formats for journal entries -- formats for things like traits, stat blocks, section headers. And MJE's own formatting overrides almost every one of these.

We get this...
![image](https://user-images.githubusercontent.com/37523352/171268251-0e4a9a81-a471-4f8e-b932-1b7d86ab06c6.png)

...when we're expecting this...
![image](https://user-images.githubusercontent.com/37523352/171268348-bcb872da-20a8-4765-b269-6c6599c60123.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
