### ISSUE TITLE
[Feature Request] Template Spawner for Encounters (similar to Stochastic, Fantastic!)

### ISSUE THREAD

**Issue by That-Italian-Guy** [ironmonk88/monks-enhanced-journal#296]
When spawning a MEJ Encounter from a Note on the battlemap, all the creatures spawn around the note itself. It would be nice to have a "spawner template" similar to what [Stochastic, Fantastic!](https://foundryvtt.com/packages/dnd-randomizer) uses, so that the creatures would spawn in a random unoccupied point within the template. It could be an option toggled in the Module Settings (spawn with template yes/no) or a separate button on the MEJ Encounter Note on the battlemap.

Current MEJ spawner
![Untitled-1](https://user-images.githubusercontent.com/106380880/171359623-8deff248-567e-4e5c-bc57-23b23e6ace43.jpg)

SF spawner
![Untitled-3](https://user-images.githubusercontent.com/106380880/171360057-d0abdcb2-5d3e-42c7-89b8-dad5b0f24678.jpg)

**Comment by ironmonk88** [comment]
Added the feature in the latest release.
