### ISSUE TITLE
BUG: Edit/Delete buttons on Simple Calendar Note journal entries crash Foundry

### ISSUE THREAD

**Issue by zk-sn** [ironmonk88/monks-enhanced-journal#297]
When using both Simple Calendar [2.0.20] with Monk's Enhanced Journal, if the Simple Calendar journal note opens in Monk's Enhanced Journal tab, clicking the "Edit" or "Delete" buttons in the journal entry seem to completely crash Foundry requiring a restart or browser reload.

Steps to Duplicate:
Install modules Simple Calendar and Monk's Enhanced Journal
Create a Note in Simple Calendar
If Enhanced Journal is enabled for current user (GM or if "Allow Players" checked in Monk's Enhanced Journal Settings), the note will open in both the Simple Calendar note edit window and the Monk's Enhanced Journal window.  In the Monk's Enhanced Journal window, clicking either the "Edit" and "Delete" buttons from Simple Calendar will crash Foundry, and the reload will be potentially missing UI elements until Foundry is closed and reopened or the full browser tab is reloaded.

Additionally, if "Show Notes Folder" is enabled in Simple Calendar preferences, Simple Calendar Notes appear in a folder _simple_calendar_notes_directory in the Journal.  If Enhanced Journal is enabled for the current user, opening a note from there will open it in the Enhanced Journal view, and clicking the Edit or Delete buttons will result in a crash as above.

**Comment by XpPlayer845** [comment]
In addition:
When using Enhanced Journal [1.0.60] + [Simple Calendar](https://github.com/vigoren/foundryvtt-simple-calendar) [2.0.20] + [Window Controls](https://github.com/saif-ellafi/foundryvtt-window-controls.git) [1.9.8] together
1) Select a Taskbar setting for "Window Controls" > "Organized Minimize"
2) Enable "Show Notes Folder" for "Simple Calendar"

When creating a new calendar note the Note-edit-window will appear in the taskbar (in addition to the Enhanced Journal window), but this handle is not connected to the actual window and stays there indefinitely, even after all windows are closed (you have to manually remove the entry from the taskbar).

If "Show Notes Folder" option is disabled the entry in the taskbar will close itself once the Enhanced Journal window is closed.

![Screenshot](https://user-images.githubusercontent.com/106908641/172051456-b75c27cd-c7f6-4786-85c0-bb568696f223.jpg)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
