### ISSUE TITLE
Entering in the edit mode loose the original style

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#3]
tested on foundry 0.8.5, DnD5e 1.3.2

When you enter in the edit mode, the original style is lost, replaced by a completely different style:
![CleanShot 2021-05-31 at 10 26 52](https://user-images.githubusercontent.com/6490765/120164781-35e3b680-c1fb-11eb-984b-d92d6646dac9.png)
![CleanShot 2021-05-31 at 10 27 05](https://user-images.githubusercontent.com/6490765/120164797-3a0fd400-c1fb-11eb-84b9-c4fa18bddbdd.png)

**Comment by ironmonk88** [comment]
Fixed in the next release.

**Comment by ironmonk88** [comment]
Should be fixed in 1.0.7
