### ISSUE TITLE
clicking on actor link gets a poorly displayed page

### ISSUE THREAD

**Issue by wmve** [ironmonk88/monks-enhanced-journal#302]
when i click on an actor link i get something like this

![image](https://user-images.githubusercontent.com/55966777/173592306-f4a778ae-8c62-4078-8e95-6b3912d70a0b.png)

i could be mistaken, but i thought it used to open the character sheet outside the editor window, which is what i want and need.

**Comment by wmve** [comment]
i can't even scroll down, btw, and the layout of what shows is so distorted as to be unusable.  i looked for an option for "use external character sheet for links" or some such thing... am i missing it?

**Comment by ironmonk88** [comment]
Alt-Click to open a link outside of the browser.
Ctrl-Click to open in a new tab.

What system are you using?

**Comment by wmve** [comment]
D35E (D&D 3.5e)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
