### ISSUE TITLE
Linked actors in journals should be visible to players when the permission level is Limited or higher

### ISSUE THREAD

**Issue by BenChand** [ironmonk88/monks-enhanced-journal#303]
Reopens this issue:
https://github.com/ironmonk88/monks-enhanced-journal/issues/242

A vanilla journal entry allows players to see actor links if the permission level for that actor is LIMITED or higher. For Monk journals, it's set as OBSERVER or higher.

**Comment by ironmonk88** [comment]
Added to the latest release.
