### ISSUE TITLE
Error when linking to merchantsheet actor

### ISSUE THREAD

**Issue by hitokiri1337** [ironmonk88/monks-enhanced-journal#304]
Clicking a merchantsheet actor link works fine the first time. But when I try to go back, it loads a page with the description to edit and a blank Character name.

![image](https://user-images.githubusercontent.com/38703108/173802567-d0b6a7ef-2a4a-4059-8f57-fa366d7f3319.png)

If I close out, I get the error below. I have to refresh the game to get it to work once more, but then it starts erroring again.

![image](https://user-images.githubusercontent.com/38703108/173801902-b7570a05-c32b-4d77-b3a8-bab83b747ce6.png)

**Comment by hitokiri1337** [comment]
Here's a video of error in action in a fresh world with all other modules disabled except for MerchantSheet and MEJ.

https://user-images.githubusercontent.com/38703108/173900311-b12f032c-0b3c-4afc-8af3-f992056fd3ac.mp4

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
