### ISSUE TITLE
[BUG] Players cannot "accept" an item from a loot sheet: "cls.canAfford is not a function"

### ISSUE THREAD

**Issue by Z8MB1E** [ironmonk88/monks-enhanced-journal#306]
Hey there! I'm having an issue with attempting to give players items from a loot sheet (specifically, when I attempt to accept a requested receipt.) Clicking "Reject" or having the player "Cancel" the request works no problem, but if I try to click "Accept" to give the player the item, nothing happens in-game and I receive a console error that looks like this:

![image](https://user-images.githubusercontent.com/5430887/173995547-1070cdca-0fbe-487d-a45d-ad36390914fe.png)

Any ideas what might be causing this? Any help would be appreciated!

**Comment by ironmonk88** [comment]
That's a bug.
Fixed for the next release.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
