### ISSUE TITLE
[pf2e] Inline rolls not working in Enhanced Journal Entry sheet

### ISSUE THREAD

**Issue by TehT** [ironmonk88/monks-enhanced-journal#307]
when using the Pf2e system and using the Enhanced Journal Entry sheet, inline rolls using the @check syntax and templates using @template will not correctly convert to buttons. Issue is not present in the Default or PF2e journal entry sheets.

**Comment by ironmonk88** [comment]
I think it's fixed, but can you give me the syntax for the @check and @template?  And I'll make sure it's working.

**Comment by TehT** [comment]
Thanks for the quick response, here are some extended syntax

@Check[type:flat|dc:4]

@Template[type:emanation|distance:2]

**Comment by TehT** [comment]
Issue is resolved as of 1.0.67, thank you!

**Comment by ironmonk88** [comment]
Closing as the issue has been resolved
