### ISSUE TITLE
[Bug][D&D 5e] Issue when placing Foundry into Dark Mode

### ISSUE THREAD

**Issue by Olathurl** [ironmonk88/monks-enhanced-journal#308]
When utilizing Foundry-wide Dark Mode via the module [D&D5e Dark Mode](https://foundryvtt.com/packages/dnd5e-dark-mode), the Loot and Shop sheets do not properly display the Item Names list. The names of the items appear as Black text on a Black background. All other sheet types work fine, at least from the limited use ive had with them.

**Comment by ironmonk88** [comment]
Should be updated in the latest version
