### ISSUE TITLE
Compatibility with Forien's Quest Log

### ISSUE THREAD

**Issue by Baxmann** [ironmonk88/monks-enhanced-journal#31]
FQL adds a folder that the DM isn't really supposed to see name _fql_quests, and MEJ makes it visible. It'd be nice to not have to see that folder, as my OCD brain is bothered by the folder name.
FQL also adds a button to the bottom of the journals tab, it'd be nice to have that button also be in MEJ.

**Comment by ironmonk88** [comment]
Of course I totally had that folder turned on because of debugging.  Forgot that it gets hidden.
Folder should be hidden with the next release.
.....But.... I'm holding off on adding the button for the time being.

**Comment by ironmonk88** [comment]
Fixed in latest release.
