### ISSUE TITLE
[Bug] Starfinder - Shops set to "Request Purchase" do not allow GM to approve purchase

### ISSUE THREAD

**Issue by Grizwold53** [ironmonk88/monks-enhanced-journal#311]
In the Starfinder system, if a player has the appropriate amount of currency to purchase an item from a store, and the store is set to "Request Purchase", when the GM clicks "approve" the sale does not go through. F12 errors show:

![image](https://user-images.githubusercontent.com/88157602/174872707-14afa395-468c-426f-9de2-5b324f185400.png)

If the shop is set to "Anyone", the players can purchase the items as expected.

**Comment by ironmonk88** [comment]
This should have been fixed in the latest release.
