### ISSUE TITLE
[Bug] Starfinder- Players cannot purchase from shops, gives "Cannot drag items from actors not on the active scene" error.

### ISSUE THREAD

**Issue by Caboozles** [ironmonk88/monks-enhanced-journal#313]
Akin to the error in https://github.com/ironmonk88/monks-enhanced-journal/issues/311#issue-1278880899, except unable to purchase at all.

Fresh world with only Monk's Enhanced Journal, all latest update has the error as well.

**Comment by ironmonk88** [comment]
This should have been fixed in the latest release.
