### ISSUE TITLE
[Bug] Advanced 5E - Shops set to "Request Purchase" do not allow GM to approve similar to Issue #311

### ISSUE THREAD

**Issue by jhathawaytn** [ironmonk88/monks-enhanced-journal#314]
F12 shows similar if not same error message as issue #311 points out.
![image](https://user-images.githubusercontent.com/13384957/175109035-1b81ec32-36cd-471f-9ac2-e718ab21c70b.png)

**Comment by ironmonk88** [comment]
Should have been fixed in the latest release.
