### ISSUE TITLE
[Bug] PF1e - Loot journal sheet does not use the unidentified name of the item when posting to chat

### ISSUE THREAD

**Issue by overdox** [ironmonk88/monks-enhanced-journal#317]
On pathfinder 1e system you have identified and unidentified names on items.
When a item with the state "unidentified" is given to a player, it posts the identified name of the item to the chat log.

**Comment by Klaesstus** [comment]
I can confirm that this occurs with pathfinder 2e as well. The description however works as intended. 
Screenshot:
https://ibb.co/jfV6bhD

**Comment by ironmonk88** [comment]
Fixed in latest release.
