### ISSUE TITLE
Libwrapper conflict found between Grape Juice Isometrics and module Monk's Enhanced Journal

### ISSUE THREAD

**Issue by crystopper** [ironmonk88/monks-enhanced-journal#318]
The error is causing non-isometric scenes to have distorted tokens.

Console error report:

foundry.js:319 LibWrapperAlreadyOverriddenError: Conflict detected between module Grape Juice Isometrics and module Monk's Enhanced Journal.

This is *not* a libWrapper bug.

Find information about these packages here:
- Module Grape Juice Isometrics: https://gitlab.com/jesusafier/grape_juice-isometrics/
- Module Monk's Enhanced Journal: https://github.com/ironmonk88/monks-enhanced-journal

Report this conflict here:
- Module Monk's Enhanced Journal: https://github.com/ironmonk88/monks-enhanced-journal/issues

Ask the community for support:
- FoundryVTT Discord's #modules-troubleshooting channel: https://discord.gg/foundryvtt
- FoundryVTT Reddit: https://www.reddit.com/r/FoundryVTT

== Technical Details:
Detected by libWrapper.
Package IDs= grape_juice-isometrics, monks-enhanced-journal
Error= Failed to wrap 'NotesLayer.prototype._onDropData' for module grape_juice-isometrics with type OVERRIDE. An OVERRIDE wrapper for the same method has already been registered by module monks-enhanced-journal.

[Detected 2 packages: grape_juice-isometrics, perfect-vision]
    at 🎁register [as register] (libWrapper-api.js:558:12)
    at config.js:30:20
    at Hooks._call (foundry.js:294:14)
    at Hooks.callAll (foundry.js:253:12)
    at Canvas.draw (foundry.js:20094:13)
    at async 🎁Canvas.prototype.draw#perfect-vision (canvas.js:415:9)
    at async Scene.view (foundry.js:17859:7)

**Comment by ironmonk88** [comment]
I can switch to overriding create preview.
Should be fixed in the next release.

**Comment by ironmonk88** [comment]
Fixed in latest release.
