### ISSUE TITLE
Issues with creating new entries and switching entries.

### ISSUE THREAD

**Issue by amcvfx** [ironmonk88/monks-enhanced-journal#32]
I'm having trouble with creating new journal entries, in particular pictures as there doesn't seem to be any way of saving them. After the picture is created I have to navigate off the entry then back to it to be able to edit it and when I have selected the image it shows up in the entry but it doesn't save. Ctrl+S doesn't work and there is no save button so when I navigate away then return it shows the hooded face vector image.

There is also another issue when switching entries. Sometimes journal appears as another? The title stays as the correct journal entry but it displays something else entirely. I get this error when moving between journals and I'm not sure if it is related.

![image](https://user-images.githubusercontent.com/35099081/121425164-03a82680-c96a-11eb-8abc-e10bf97ce60c.png)

**Comment by ironmonk88** [comment]
I fixed the issues with creating a new entry.
And I fixed some issues when switching entries... but I'm not sure I fixed this issue.
I think you've found a couple of bugs here.

**Comment by amcvfx** [comment]
Thanks for all the fixes!

**Comment by ironmonk88** [comment]
I think there are more bugs in this comment, but I'm closing it because the main ones have been fixed.
