### ISSUE TITLE
[5E System] [Change request] White title when opening Picture Journals from Tile

### ISSUE THREAD

**Issue by SirZeel** [ironmonk88/monks-enhanced-journal#325]
![image](https://user-images.githubusercontent.com/96880264/176557638-cb0a4ae5-87f6-4199-b798-673ec007c10a.png)

Creating a tile with MATT and using it to open a journal, the title appears white. It's kinda hard to read.

**Comment by ironmonk88** [comment]
Fixed in latest release.
