### ISSUE TITLE
Custom icons for map notes change to Acid icon when changing font or font size. 

### ISSUE THREAD

**Issue by bklick** [ironmonk88/monks-enhanced-journal#327]
Foundry Version 9, Build 269
DnD 5e - Fifth Edition System, 1.6.3
Forge Server

![ezgif-5-c8e10652d1](https://user-images.githubusercontent.com/3947702/176591666-d2904448-c0a1-4201-bb4c-5fb5435c5c34.gif)

In the MEJ discord, Crowguard could not replicate this. I used to have a module called Pincushion that had this functionality. Is it possible that an old mod left something behind that is causing this?

**Comment by ironmonk88** [comment]
Fixed in latest release.
