### ISSUE TITLE
Shops dont like 6cp? :D

### ISSUE THREAD

**Issue by Kurokasa** [ironmonk88/monks-enhanced-journal#330]
Foundry ver.: 9 Build 269
DnD5e ver.: 1.6.3
Mink´s Enhanced Journal ver.: 1.0.64

Hi, i dont know why and it took me quit some time to find out what it is, but when i add a consumable that has a cost of exactly 6cp (0.06) the journal cant read the item. I get the error i linked below and the journal wont open again (its just empty).
I tried it with multiple items and even changed working items to the cost of 6cp, every time the journal crashes and the error shows.
![Screenshot 2022-07-04 150539](https://user-images.githubusercontent.com/102412559/177160905-b664b464-08a3-4921-9252-a6950f9cca65.jpg)
If i can help with further information let me know. Thx for the awesome modules :)

**Comment by ironmonk88** [comment]
Closing this as I believe it has been fixed.
Please re-open if this is not the case.
