### ISSUE TITLE
[Feature Request] New Relationship: Point of Interest - Organization

### ISSUE THREAD

**Issue by Havoclivekiller** [ironmonk88/monks-enhanced-journal#335]
**Is your feature request related to a problem? Please describe.**
Add the ability to drop Organizations to Point of Interest. As organizations, for example, could control such places that aren't Places.

**Describe the solution you'd like**
Drag/Drop Organization to Point of Interest Relationship tab.

**Comment by FreyrGudmundsson** [comment]
Came to create this issue. I'd even expand it and say, just allow every type to have a relationship to every type.

**Comment by ironmonk88** [comment]
Fixed in latest release.
