### ISSUE TITLE
[BUG] Cannot split journal after latest update

### ISSUE THREAD

**Issue by jackkerouac** [ironmonk88/monks-enhanced-journal#337]
[BUG] Cannot split journal after latest update
After latest update, splitting journal results in the following error:

enhanced-journal.js:925 Uncaught TypeError: Cannot read properties of undefined (reading 'splitJournal')
[Detected 1 package: monks-enhanced-journal]
    at JournalEntrySheet.splitJournal (enhanced-journal.js:925)
    at HTMLDivElement.dispatch (jquery.min.js:2)

**To Reproduce**
1. Open Journal Entry
2. Highlight section of text
3. Click on the split journal button
4. No profit!

 - Browser: Chrome
 - Foundry: Version 9
 - System: D&D5e
 - Module: version 1.0.65

NOTE: Right-clicking and splitting the journal DOES work, however.

**Comment by gabr1el111** [comment]
When I try to use the 'extract to a new entry' functionality it doesn't work

**Comment by ironmonk88** [comment]
Fixed in latest release.
