### ISSUE TITLE
Adding organization to quest relationships

### ISSUE THREAD

**Issue by TazztheMonster** [ironmonk88/monks-enhanced-journal#341]
**Is your feature request related to a problem? Please describe.**
At the moment it is not possible to add organizations to the relationship tab for quests.

For example:
In my campaign, some of the quests are given by local guilds.

**Comment by Crowguard** [comment]
[BUG] Organizations not adding to relationship tab in Shop-type journals.

![image](https://user-images.githubusercontent.com/99844555/179826145-512298ff-bec9-4b90-8892-92b2c311ca2c.png)

Tested in D&D 5e.

**Comment by ironmonk88** [comment]
I believe this was fixed.
Is it still an issue?

**Comment by TazztheMonster** [comment]
Yes, this is done.
Thanks a lot for your great work, and sorry for "not updating" without a reminder.
