### ISSUE TITLE
[BUG] Font Sizes & Scrolling

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#342]
![image](https://user-images.githubusercontent.com/99844555/179053903-a6400d03-d770-4503-bb5b-17a8ae11f029.png)

![image](https://user-images.githubusercontent.com/99844555/179054612-c97a30fe-1f0f-495a-803b-2334f7080233.png)

Core setting for font size 7+ is messing up the scroll on MEJ. Tested in CoC7 & DnD5e.

MEJ 1.0.65

**Comment by ironmonk88** [comment]
I believe this has been fixed.
Is this still an issue?

**Comment by Crowguard** [comment]
Not an issue anymore.
