### ISSUE TITLE
[BUG] Pathfinder 2e - Loot and shop journals do not use the unidentified name and image of items

### ISSUE THREAD

**Issue by Klaesstus** [ironmonk88/monks-enhanced-journal#343]
**Describe the bug**
Pathfinder 2e - Loot and shop journals do not use the item names and images marked as unidentified through the Mystification tab of the item sheet.

**To Reproduce**
1. Open an item's sheet. (For example, Potion of Tongues)
2. Navigate to the Mystification tab.
3. Change the name and description to something else. (For example, "Unusual Liquid" and "The nature of this liquid is unclear")
4. Change the dropdown from "identified" to "unidentified".
5. Add item to loot or shop sheet, it will have the original name and image, rather than the unidentified ones. The description is however correct.

**Expected behavior**
The item shown in the loot/shop sheet should have the unidentified name, image and description.

**Screenshots**
https://imgbb.com/jfV6bhD

**Please complete as much of the following information as possible:**
 - Tested with Chrome and Opera GX.
 - Foundry Version 9 Build 269
 - System Pathfinder 2e Version 3.12.2.10
 - Module Version 1.0.65
 - No errors while adding an unidentified item to the journal.
 - Used "Find the culprit" with only this module, issue persists.

**Additional context**
N/A

**Comment by ironmonk88** [comment]
Fixed in latest release.
