### ISSUE TITLE
[BUG] AGE System on Foundry VTT - Impossible to sell items

### ISSUE THREAD

**Issue by Dragonail** [ironmonk88/monks-enhanced-journal#353]
**Describe the bug**
Hello ! 
I'm new to FoundryVTT and I have add the monk's modules. I'm using the AGE System for DMing Dragon Age. I've created an interactive shop with Monk's Journal where my players can buy and sell items. But, when they want to sell the item, it stays in there inventory + they get no money + the item is duplicated in the shop. I'm sorry if I've missed something very obvious but I've watched and re-watched some videos and I still have this problem 

**To Reproduce**
1. Go to the player and the shop inventory
2. Drag and drop the items you want to sell
3. See if the item is still in the player inventory and watch the amount of money

**Expected behavior**
I think the item should disappear from the player's inventory when they drag and drop the item to sell it and that they get the amout of money when they sell it and that the item is not duplicated

**Screenshots**
Before selling battle axe : 
![image](https://user-images.githubusercontent.com/103593328/183296262-8ef032ee-1d44-4711-bf6a-4619492392c5.png)

After selling battle axe : 
![image](https://user-images.githubusercontent.com/103593328/183296294-510cf84a-5e1d-4ead-a0fd-7207a3dd9ca1.png)

**Please complete as much of the following information as possible:**
 - Browser [chrome
 - Foundry Version [v9]
 - System [AGE System]
 - Module 1.0.65
 - Are there any errors in the console 
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

Note : A find the culprit! test has been done but seems the only problem is with my compendium folders. But I've tried to create an item out of the compendium, add it to the rolltable and tried to sell it, same issue

**Comment by ironmonk88** [comment]
Currency details added for AGE system.
