### ISSUE TITLE
[BUG] Pressing Enter Forwards to another Page and distorts UI 

### ISSUE THREAD

**Issue by Schlachi** [ironmonk88/monks-enhanced-journal#356]
**Describe the bug**
If you enter a Title in a new Journal Entry and Press Enter you somehow land on another "webpage". On the new Page the UI is distorted and if you press back in the browser all is normal again. 

**To Reproduce**
1. Create a new Journal Entry
2. Enter a Text in the Title and Press Enter
3. See error

**Expected behavior**
I guess normally nothing should happen. 

**Screenshots**
Before I hit Enter
![image](https://user-images.githubusercontent.com/13168272/184543194-b960dc58-22b6-4741-86ae-588cd0559f9c.png)

After hitting Enter in title bar the Title seems to get added to URL? UI all over the Place in randomized Positions
![image](https://user-images.githubusercontent.com/13168272/184543310-757db4ff-8c58-4e37-8280-7905f6f41199.png)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version v9
 - System Pathfinder 2e (Tried in GURPS 4e didn't happen there) 
 - Module version 1.0.65
- Happens  even with no other Modules loaded other than Tidy UI
![image](https://user-images.githubusercontent.com/13168272/184543441-7714fd58-ceb5-4108-bf64-e24b5e494985.png)

**Comment by ironmonk88** [comment]
Fixed in latest release.
