### ISSUE TITLE
Ability to overwrite currency data location.

### ISSUE THREAD

**Issue by JasonSunday** [ironmonk88/monks-enhanced-journal#359]
I am currently running two games 13th Age and Pathfinder for Savage Worlds for Savage Worlds in Foundry VTT. 13th Age currency variable is at data,coins.gold.value and PfSW points to data.currency. I would like be able to configure were the currency is in the data. This would allow me to use stores and distribute loot in a lot more systems.

**Comment by ironmonk88** [comment]
currency details added for 13th age and swade.
