### ISSUE TITLE
Resolved: Monk's Enhanced Journal prevents ANY journal from opening in V10 running on Forge

### ISSUE THREAD

**Issue by iamthecrave** [ironmonk88/monks-enhanced-journal#360]
In newest version of Foundry, V10 Testing 5 Build 279, running on Forge, journals will NOT open when module is running. You can created Enhanced Journals, but journals do NOT open. 

**To Reproduce**
1. Go to Any Journal entry.
2. Click on it
3.  See error: Nothing Happens

**Expected behavior**
I expect the journal to open and nothing opens at all! 

**Please complete as much of the following information as possible:**
 - Chrome - latest
 - Foundry Version V10Test5
 - System D&D5e
 - Module version 10.0.65
 - Are there any errors in the console [e.g. press F12 and look for red text] Tons. It's clear that the new journal structure is causing the problem.

**Additional context**
I'm guessing this is just an update issue. Will Monk's Journal's be updated?

**Comment by WizardForHire123** [comment]
thats because it's not ready yet my dude. It says that on his discord.

**Comment by iamthecrave** [comment]
Thanks. I’ll be more patient.

**Comment by ironmonk88** [comment]
Closing as I believe this has been resolved
