### ISSUE TITLE
Reveal Quest Rewards Tab

### ISSUE THREAD

**Issue by drakzul** [ironmonk88/monks-enhanced-journal#365]
I want players to be able to view potential rewards for Quest entries. 

Ideally, I would want the Rewards tab to be viewable (either through a Module setting toggle, like Objectives, or baseline) with the ability to toggle a revealed/hidden status for each Reward entry. 

The more difficult ask is that within each Reward entry we could toggle a revealed/hidden status for each individual item and currency within the Reward entry. However, the initial request could handle this for the most part (sectioning Rewards behind different Entries).

**Comment by ironmonk88** [comment]
Added to the latest release.
You'll need to check the box that says to make it visible to players.
