### ISSUE TITLE
[BUG] V9.280 (Pathfinder 1e) - selecting text with Enhance Journal and using show in chat removes text from journal

### ISSUE THREAD

**Issue by happydevil37** [ironmonk88/monks-enhanced-journal#367]
**Describe the bug**
Selecting text when using MEJ and the show in chat window, removes the text from the journal. seems to be a cut rather than a paste.
Find the culprit indicates MEJ is the cause.
Curiously if you close that journal, open a different journal and then reopen the first the text will be back...

**To Reproduce**
1. WIth MEJ enabled, select text in the journal
2. Right click and select "Show in Chat"
3. Text will be removed every time
4. Close that journal window, reopen it and the text will be back.
5. No errors reported in console.

**Expected behavior**
Text shouldn't be removed

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser [e.g. chrome, safari] - Foundryvtt
 - Foundry Version [e.g. v9] V9.280
 - System [e.g. D&D5e, Pathfinder 2e] Pathfinder 1e
 - Module Verison : 1.0.65
 - No Errors
 - Find the Culprit - says its MEJ.

**Additional context**
Annoying more than serious - first few times I thought I had lost text but now I realise it doesnt... a work around is possible..

![mej after](https://user-images.githubusercontent.com/28553250/189005921-fab980f0-7b36-4788-83fd-76366924a9be.png)
![mej during](https://user-images.githubusercontent.com/28553250/189005926-91de3c5a-e334-47fb-9ce1-c5600d0caaa8.png)
![mej before](https://user-images.githubusercontent.com/28553250/189005928-913f2fa4-744b-4cce-b708-e8279f2d37fd.png)

**Comment by ironmonk88** [comment]
Fixed in latest release.
