### ISSUE TITLE
Prices in the shop are not calculated correctly if the price is in copper or silver pieces. 

### ISSUE THREAD

**Issue by Huwbohobo** [ironmonk88/monks-enhanced-journal#368]
**Describe the bug**
Prices in the shop are not calculated correctly if the price is in copper or silver pieces. Either dragged from the item menu onto the shop or sold by a player. Items will either list as 0 gp or given a semi random gp value. Using chrome, foundry version 9 build 280.
**To Reproduce**
Create a shop journal entry and drag an item with less than 1 gold in value.
Item will be listed as price and cost 0 most of the time or cost 1 gp.
Item sold buy a player to the shop has a semi random value and cost added to it.
Items with an increased value (such as cold iron) list as the original value when placed in the shop. Cold iron dagger lists as 1 gp instead of 44gp.
**Expected behavior**
I drag an item from the item tab into the store and it's cost matches the value under details.
Items sold by players to have a similar result.
**Screenshots**
![image](https://user-images.githubusercontent.com/113116823/189143285-47e0fcb0-59b9-44f3-8ddc-53175d4a8f9e.png)

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version  v9 build 280
 - System Pathfinder 2e
 - Module version 1.0.65

**Additional context**
I have not edited any values in the currency section of the module, might this have caused an error?

**Comment by Huwbohobo** [comment]
![image](https://user-images.githubusercontent.com/113116823/189138357-c874bee6-e9ac-47a3-aac6-ef068304e1da.png)

**Comment by ironmonk88** [comment]
Fixed in latest release.
