### ISSUE TITLE
Loot[BUG] Unable to give currency to players.

### ISSUE THREAD

**Issue by Huwbohobo** [ironmonk88/monks-enhanced-journal#369]
Loot table doesn't have a split currency button for my pf2e game, workaround atm is adding treasure with a value or gold/silver as an item.

**To Reproduce**
Create a loot table with currency filled in.
click show to players to allow them to see/request items from said loot table.
items are fine for players to take but the currency section lacks any way of dispensing coin.

**Screenshots**
gm view
![image](https://user-images.githubusercontent.com/113116823/189140336-20343076-7601-4afd-be99-0bb2ae3bdd39.png)
player view
![image](https://user-images.githubusercontent.com/113116823/189140441-ae87cf43-983b-4d50-9a3b-283d3b324dc3.png)

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version v9 build 280
 - System  Pathfinder 2e
 - Module version 1.0.65
 - Are there any errors in the console [none]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Not yet will try.

**Additional context**

**Comment by ironmonk88** [comment]
Fixed in latest release.
