### ISSUE TITLE
[Feature Request] Allow shops to sell services

### ISSUE THREAD

**Issue by humburg** [ironmonk88/monks-enhanced-journal#371]
**Is your feature request related to a problem? Please describe.**
Sometimes I would like shops to offer things for sale that aren't physical goods, like accommodation or training. While it is possible to create items that correspond to these services, this will result in that item being transferred to the character's inventory, which doesn't make sense.

**Describe the solution you'd like**
It would be nice if shops supported some form of *Service* entry. This could take the form of an option to prevent item transfer, for example.

**Comment by Weskernation** [comment]
When a service is being purchased, At least a notification to  the DM and Buyer (selectable option who can see the purchase) for when "Player Purchasing: Anyone" is selected

**Comment by ironmonk88** [comment]
Current version of MEJ has the consumable option for items sold.  This will allow players to purchase something without it being put in their inventory.  Usually used for things like food at a tavern, this can be used for services too.

And any item purchased should generate a Chat Message to let the player and GM know it was purchased.
