### ISSUE TITLE
[BUG] Create New Page (Player-Side)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#373]
With MEJ active, the New Page button is missing for players when they have ownership of a journal.

### MEJ Off

![image](https://user-images.githubusercontent.com/99844555/189560123-98b8abb9-c812-4390-9539-8b243e032c9f.png)

New page button is available.

### MEJ On
![image](https://user-images.githubusercontent.com/99844555/189557978-4c6fef09-590a-45fd-9159-8b2b09ab0e1f.png)

New page button is missing in the new location.

**Comment by ironmonk88** [comment]
Fixed in latest release.
