### ISSUE TITLE
[BUG] Sidebar Folder Text Color

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#374]
The text color and folder icon are a dark grey now and harder to see with custom folder colors.
![image](https://user-images.githubusercontent.com/99844555/189558341-3a0590da-eebe-4d76-ab2d-11b7d0f13678.png)

### V9
![image](https://user-images.githubusercontent.com/99844555/189558245-100330fa-b47c-4f39-822d-3d45dc295d86.png)

### V10
![image](https://user-images.githubusercontent.com/99844555/189558264-dd7e7ecc-1db1-49af-b2b2-f5d9f8113cf7.png)

D&D 5e 2.0.3
Foundry 10.286
MEJ 10.1

**Comment by Crowguard** [comment]
Closing this. It seems to have solved itself with the newest Foundry update.

**Comment by Crowguard** [comment]
Nevermind. I just checked the wrong folders.

**Comment by Truncated** [comment]
It's still a problem with v10.3 and Foundry 10.288 (Pathfinder 1e in my case).

The folders can have backgrounds set, but not font color set.
![image](https://user-images.githubusercontent.com/14208325/196768518-909d843d-cf36-4430-9597-e053b04d69ed.png)

In v10 right now, you cannot modify the font color but you can modify the background color. Given that Foundry sets it as white throughout, users will set background colors to be readable vs. white. Having the same background deal for both is nearly impossible, from a usability standpoint.

In a perfect world, the text would be programmed to use conditional CSS to detect the background and provide a high-contrast font color globally.
https://css-tricks.com/switch-font-color-for-different-backgrounds-with-css/
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html
https://www.msfw.com/Services/ContrastRatioCalculator

If the point of changing color is to show that a folder is opened or closed, perhaps instead using div-box outlines, bolding and/or italics on the labels would be more effective and less likely to become contrast issues regardless of the colors used.

The approach above should make it pretty future-proof, regardless of how styling goes for core foundry and 3rd party styling.

**Comment by Truncated** [comment]
Had a chance to dig into this some more, found it's due to the style.css for Foundry - the collapsed style for h3 has "color: inherit", which is blocking the normal non-collapsed color that usually gets inherited which implements the variable contrastI was mentioning above.

I made a bug entry for Foundry; hopefully they will just fix it there and it will magically resolve itself.
https://github.com/foundryvtt/foundryvtt/issues/8538

**Comment by ironmonk88** [comment]
Honestly... folders should allow for the font colour to be changed.  Not just the background colour.
Since, in Foundry, if you use a really light colour for the folder the text will be hard to read.

**Comment by ironmonk88** [comment]
That actually looks like an introduced bug.  It should have been switching the colour when the folder colour changed... but I guess it got dropped off during an update.
Restored the code and it should be working now.
