### ISSUE TITLE
[BUG] Wands in Shop and Loot journal entries always show 0/0 charges in summary.

### ISSUE THREAD

**Issue by Truncated** [ironmonk88/monks-enhanced-journal#375]
**Describe the bug**
In the expandable summary of the wands when you click on the text in each row, the box tips that show at the bottom for each show 0/0 charges instead of # / 50, as expected.

**To Reproduce**
Add a wand with any number of charges to a Shop or Loot journal page.
Summary display shows 0/0, as shown in screenshots

**Expected behavior**
Display should show the correct number of charges from the Limited Use section for Consumables --> Wands.

**Screenshots**
![image](https://user-images.githubusercontent.com/14208325/189575060-97067a1c-f1d6-41a8-acc3-be3dd4b01f3b.png)
![image](https://user-images.githubusercontent.com/14208325/189575101-6b11fe6b-96df-433f-bd23-c850dbb74abc.png)

**Please complete as much of the following information as possible:**
 - Browser - Chrome
 - Foundry Version - 9.280
 - System - PF1e 0.81.3
 - Module version - 1.0.65
 - Are there any errors in the console [e.g. press F12 and look for red text]
 This error is probably a different issue. No errors when expanding the summary and opening the journal page in question, but when editing the wand, I get this:
![image](https://user-images.githubusercontent.com/14208325/189575530-ac762818-ffab-4d0b-954c-420cc0150f38.png)

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
Yes. Module Management+ and MEJ were the only ones on and it still showed the same.
![image](https://user-images.githubusercontent.com/14208325/189575968-d6e1d7bf-f400-4f50-bcd1-96c7a3f20195.png)

**Comment by Crowguard** [comment]
This seems to be a Pathfinder 1e issue; the charges display properly in D&D 5e. 
![image](https://user-images.githubusercontent.com/99844555/190232896-71dc5ab5-2cab-424b-80c1-06f23eae8a0c.png)

**Comment by Truncated** [comment]
> This seems to be a Pathfinder 1e issue; the charges display properly in D&D 5e. ![image](https://user-images.githubusercontent.com/99844555/190232896-71dc5ab5-2cab-424b-80c1-06f23eae8a0c.png)

Yea, I'm expecting this to be a "after v10 has settled for everyone if it's still a problem on the other side" thing. :)

**Comment by ironmonk88** [comment]
This is an issue with the PF1 system.
It's in the code that if the item isn't attached to an Actor then it won't display its charges.
I've added a really awful workaround, that MEJ will read through all the properties and if it encounters one that starts with `Charges:` it will attempt to do the calculation itself.

**Comment by ironmonk88** [comment]
Closing as it should be reasonably fixed.
