### ISSUE TITLE
[BUG] Items with blank descriptions

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#376]
![image](https://user-images.githubusercontent.com/99844555/189706680-aaddf0b4-026b-4e17-97a1-d8b1dcdcf25f.png)

Items with no description show [object Object] when examined within journals.

MEJ 10.1
![image](https://user-images.githubusercontent.com/99844555/189707062-642cf563-dee9-4ab9-a83b-c6bcc501469b.png)

**Comment by ironmonk88** [comment]
Fixed in latest release.
