### ISSUE TITLE
[BUG] (Foundry v10)(seems fixed) - Monks Enhanced Journal breaks page navigation for Mercenary Marketplace journal.

### ISSUE THREAD

**Issue by mazirian** [ironmonk88/monks-enhanced-journal#377]
With Monks enhanced journal enabled the Mercenary Marketplace journal navigation does not work. Using the page forward and back button will sometimes display the next page and reenable page navigation for that section. but changing to a new section things break again.

Mercenary Marketplace journal works as expected with Monks Enhanced Journal disabled.

**Comment by mazirian** [comment]
Seems to be fixed with latest version of both modules and Foundry.

**Comment by ironmonk88** [comment]
Closing this if it seems like it's been fixed.
