### ISSUE TITLE
[BUG] map pins do not open on the correct journal page

### ISSUE THREAD

**Issue by patrickmohrmann** [ironmonk88/monks-enhanced-journal#378]
**Describe the bug**
I created a map pin out or one page of my journal, when i click on the map pin, the journal will open, but not on the page the pin is linked to. Without the modul this works.

**To Reproduce**
1. create a journal with several pages
2. create a map pin from any page other than the first
3. open the journal by clicking th map pin

**Expected behavior**
the journal should open at the correct page

**Screenshots**
NA

**Please complete as much of the following information as possible:**
 - Browser CHrome
 - Foundry Version [V10.285]
 - System [Earthdawn4e]
 - Module version 10.1
 - Are there any errors in the console [e.g. press F12 and look for red text] - No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. no

**Additional context**

**Comment by RinVindor** [comment]
Yeah I'm having this issue as well its kind of a vital feature of the Pages too 😂

**Comment by ironmonk88** [comment]
Fixed in latest release.
