### ISSUE TITLE
[BUG] v10. Loot Sheets not decreasing actor inventory

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#380]
Dragging an item from an actor to a loot sheet no longer reduces/removes the item from the actor's inventory. 

https://user-images.githubusercontent.com/99844555/190457464-e625704f-a126-4155-b4fc-62ee32e1d580.mp4

MEJ 10.1
![image](https://user-images.githubusercontent.com/99844555/190456848-b532a5c6-37ca-4985-882a-67b87d0df36d.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
