### ISSUE TITLE
[BUG] v10. Item Quantity

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#381]
Adding a single item to a MEJ sheet using the quantity select prompt will add that many of the item, but each of those items in the shop equals the original quantity of the item added. 

https://discord.com/channels/862414864692281386/862421185211924540/1020016525547159682

https://user-images.githubusercontent.com/99844555/190466618-3c8a1e12-b36a-458e-bec7-54f5e48da4c4.mp4

**Comment by ironmonk88** [comment]
Open up the item and you'll see the item has a quantity of 5.
![image](https://user-images.githubusercontent.com/75920956/192200114-6d93b4e3-0097-4b6b-a6a3-c4000ef39fa1.png)
This is so you can sell bundles of arrows.

**Comment by ironmonk88** [comment]
Closing this as I think it was just a miscommunication.
If it's not... please re-open.
