### ISSUE TITLE
[Feature Request] Allow Quest Logs/Tracker to Stay On Screen Outside of Journal Notes

### ISSUE THREAD

**Issue by Volksters** [ironmonk88/monks-enhanced-journal#382]
**Is your feature request related to a problem? Please describe.**
My players find it an additional step to go to journal notes tab to see their quest logs. 

**Describe the solution you'd like**
Similar to what Forien's Quest Logs do, it would be great to have quest logs appear all the time, outside of the Journal Notes.

**Comment by ironmonk88** [comment]
Added to the latest release.
