### ISSUE TITLE
Some "uuid" Type Errors after updating to V10

### ISSUE THREAD

**Issue by pfeiffermit3f** [ironmonk88/monks-enhanced-journal#383]
Hi,
after updating Foundry VTT to stable version 10.285 (I did not try earlier versions, so do not know if the error is just with this version) I receive the following error:

![image](https://user-images.githubusercontent.com/110412137/190853993-96efdc7e-7bb6-4e0d-90b2-ad5116fe35ad.png)

Thanks for looking into it!
Lars

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
