### ISSUE TITLE
[BUG] v10. Open Journal via MATT

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#385]
### V9
![image](https://user-images.githubusercontent.com/99844555/191120149-7bab7c1c-9520-4010-869d-457cd4492220.png)

Opening a MEJ picture journal via a MATT trigger without the "Use MEJ" checkbox active would show the image to players using the Show to Players window format. 

In v10, its opening it in a non-MEJ journal.
![image](https://user-images.githubusercontent.com/99844555/191118550-ddaf8ecf-0bb3-452e-a209-ff2dc2440670.png)

**Comment by ironmonk88** [comment]
Technically it's a MATT issue.  Will update when that module releases.

**Comment by ironmonk88** [comment]
Should be fixed now.
