### ISSUE TITLE
[Feature Request] Shadowrun 5 price import

### ISSUE THREAD

**Issue by Jergeric** [ironmonk88/monks-enhanced-journal#386]
Aloha and thanks for this great mod. 

Would it be possible to implement a "Shadowrun 5 Edition" support? It would be great if you can use the imported database from Chummer, currently no prices are imported. Oh yes, Shadowrun unfortunately only runs on version 9 of Foundry.

If I saw it right, the mod looks for item.data, "price" when importing the dice list but apparently Shadowrun uses item.data, "cost". No idea if that's correct, just had a layman's attempt to change it myself and failed. 🙈

Shadowrun is not DnD but it would be great if you could fix it. The Shadowrun 5 chummer database is quite big and entering all prices by hand would be just too much.

**Comment by ironmonk88** [comment]
This is *possibly* fixed.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
