### ISSUE TITLE
[BUG] Cannot add rewards on quests or add items to loot sheets. V10. PF2e

### ISSUE THREAD

**Issue by ShogunKing** [ironmonk88/monks-enhanced-journal#387]
**Describe the bug**
The Quest journal entry and the Loot sheet journal entry do not allow you to press the buttons to add fillable options. You cannot add rewards or objectives to the Quest entry and you can only add items to the Loot sheet by dragging and dropping

**To Reproduce**
Open a Quest or Loot sheet
Attempt to press add button
Nothing happens

**Expected behavior**
You are able to add objectives and rewards to the quest entry and you are able to add loot to the loot sheet. 

.

**Please complete as much of the following information as possible:**
 - I was running it on the installed app version of Foundry
 - Foundry V10-build 285
 - Pathfinder 2e
 - 10.1
 -I did not see any errors when I checked
 - I didn't attempt to use Find The Culprit, but I did attempt it in an environment without other mods, and by turning off other mods. 

**Additional context**
It seems to only be an issue with PF2E, as I tried it using the Blades In The Dark system and it worked as expected.

**Comment by ironmonk88** [comment]
The Add button works for both objectives and rewards.  And loot sheet doesn't have an add button.  You can only add items to the Loot sheet by dragging and dropping them.

Can you post a screen shot of the buttons you're trying to click, and run FTC to see if it's a module conflict.

**Comment by ShogunKing** [comment]
You used to be able to populate from a Rollable table on the loot sheet, which is not currently working for me. These are the buttons I was attempting to press and were not working. I ran FTC with everything turned off but the Enhanced Journal and It came back with the same result of not working.
![find_the_culprit](https://user-images.githubusercontent.com/113961066/192193104-1eed1300-85ca-4eab-a181-dfdcb099f67e.png)
![quest_log_bug_1](https://user-images.githubusercontent.com/113961066/192193105-d673bdcb-976a-49c5-925e-e59109a1ba7c.png)
![quest_log_bug_2](https://user-images.githubusercontent.com/113961066/192193107-9ff7e27d-b310-409d-95ef-d4758afd07ed.png)
I found this error while checking logs, which I probably should have done earlier. 
![error_log](https://user-images.githubusercontent.com/113961066/192194158-33f55233-ec7f-4a61-93ac-5f00e29389fe.png)

**Comment by tiraminsan** [comment]
I also have this problem, also using Pathfinder 2e as a system. Not only that, but the UI looks really messed up if you use custom currency. Additionally, I can drag and drop items to an existing quest reward, but I cannot delete them. Here's a quest I created before v10:

![dyVlMon](https://user-images.githubusercontent.com/114499823/192553661-07fae59a-2e27-4b1e-93b4-6cc0e97fe99b.png)

The custom currency is misaligned, I cannot add rewards and cannot change rewards tab. Creating a new journal entry also disallows me from adding rewards.

![image](https://user-images.githubusercontent.com/114499823/192554797-dc64db9d-a7c5-407a-a3eb-96945ce47d3f.png)

After reseting the custom currency, it becomes aligned again but errors persist.

**Comment by BladeFireLight** [comment]
Having similar issue. Can't drag items into the rewards.  I get an error in the logs every time I try
![image](https://user-images.githubusercontent.com/8352828/198497374-97590835-9e6a-4e53-8e54-428934f2e455.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
