### ISSUE TITLE
Journal Style with "narrow margin" changeable?

### ISSUE THREAD

**Issue by pfeiffermit3f** [ironmonk88/monks-enhanced-journal#388]
Hello,
is there a way to use more of the currently blank space in the Journal Entries by Monks Enhanced Journal? This kind of "narrow margin" style was already present when I started using MEJ in V9, so despite other issues after updating to V10 I do not think this is linked to the version itself.
I am running Foundry on an Oracle Cloud, accessing through Google Chrome. 
My current Foundry Version is V10.
The system in question is Vaesen.
The module version is 10.1
I tried "find the culprit" and there is no module interaction.
The console does not give errors when only activating MEJ.

![image](https://user-images.githubusercontent.com/110412137/191374065-dc6b51d1-b8c6-4b8b-bebb-5b1e92461553.png)

**Comment by ironmonk88** [comment]
That would be an issue with the system changing styles.
Should be fixed for the next release.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
