### ISSUE TITLE
Quest reward

### ISSUE THREAD

**Issue by Pecomica** [ironmonk88/monks-enhanced-journal#39]
I am trying out the quest journal part and can't provide xp or reward to the party after the completion of the quest

I made a test quest with 1 objective. I put in xp as reward and I had a token on the map. 
I then tried to reward the token the xp, and the token do show up in the list, but when I press the button to give xp nothing happens.
I then tried ticking the object, no change, I changed the quest to in progress, no change, I changed to completed, no change. I added coin as reward as well, no change. 

I tried having the token selected and deselected in all the scenarios, but no xp was rewarded, nor was the coins distributed. I changed from no split to full split on the xp, but still nothing would work

**Comment by ironmonk88** [comment]
Do you have Monk's Tokenbar enabled?  I have a feeling I forgot to disable that unless that module is enabled.

It's on the list of things to do to assign Gold, but not available yet.

**Comment by Pecomica** [comment]
It does give the xp, but it isn't automatic. What happens is, that it output the xp and other reward in the chat tab, from there I have to click to distribute it. I was in the journals tab and thought it would be distributed automatically. My bad
