### ISSUE TITLE
[BUG] Individual page links do not work in v10

### ISSUE THREAD

**Issue by Red5Phil** [ironmonk88/monks-enhanced-journal#392]
**Describe the bug**
Individual page links do not work in v10

**To Reproduce**
1. Drag a link for an individual page from the new Adventure Book style Journal Entries into another text editor.
2. Save Entry and click on the resulting link.
3. Try to click on the resulting link
4. You might see "Text Entry" or something similar pop up in the tooltip, but nothing will open.

**Expected behavior**
Expect the link to open when clicked, but only does so for full Journal Entry links. Individual pages within a Journal Entry do nothing instead. When Enhanced Journal module is disabled, it functions as normal.

**Please complete as much of the following information as possible:**
 - Foundry Version 10, Build 286
 - System D&D5e
 - Module version 10.1
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction - Yes, seems to be limited to Enhanced Journal by itself.

**Comment by ironmonk88** [comment]
Fixed in latest release.
