### ISSUE TITLE
[BUG] v10. Unable to Open Journals via Rolltable Messages

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#394]
Clicking a chat card link from a rolltable result doesn't open the journal. No errors.

https://user-images.githubusercontent.com/99844555/192426750-6df52575-ec5c-4e18-a8d8-aadd9ea96eea.mp4

MEJ 10.1
![image](https://user-images.githubusercontent.com/99844555/192426721-2ada4dd3-941e-4a0f-946b-e67e240ff7e0.png)

**Comment by MrZwij** [comment]
I have the same issue. My versions are identical to the original reporter.

**Comment by Crowguard** [comment]
Fixed in MEJ 10.3

**Comment by ironmonk88** [comment]
Fixed in latest release.
