### ISSUE TITLE
[BUG] V10. Players Can Access Revoked Journals

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#395]
Players can access previously owned journals via the back button/recently viewed tab.

https://user-images.githubusercontent.com/99844555/192427813-10cc74dc-3bc7-413b-8be0-b08014d0b595.mp4

MEJ 10.1

![image](https://user-images.githubusercontent.com/99844555/192427871-e3ceac63-4ada-4edc-b8e4-4c6cc09ca99e.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
