### ISSUE TITLE
[BUG] V10, PF2e. Error When Opening MEJ Journals.

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#396]
https://user-images.githubusercontent.com/99844555/192631039-89cd6031-8d95-445a-ba87-ab57efa0bd3d.mp4

![image](https://user-images.githubusercontent.com/99844555/192631056-77cc64fd-b179-4202-b80e-9542bd61b3de.png)

MEJ 10.1
Foundry 10.286
PF2e 4.1.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
