### ISSUE TITLE
[BUG] v10. PF2e. Can't use Delete/Edit/Players/Distribute buttons

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#397]
https://user-images.githubusercontent.com/99844555/192632366-2ff6a8cd-ad17-40e9-8948-25164fedee4b.mp4

No errors.

MEJ 10.1
Foundry 10.286
PF2e 4.1.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
