### ISSUE TITLE
[BUG] v10, PF2e: Checklists

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#398]
Uploading Foundry_Virtual_Tabletop_6qeD8h62aW.mp4…

Electron app
MEJ 10.1
Foundry 10.286
PF2e 4.1.3

**Comment by Crowguard** [comment]
Seems to be fixed with Pf2 4.2.1? Won't close this yet in case you want to keep an eye on it.

**Comment by ironmonk88** [comment]
Closing the ticket.
