### ISSUE TITLE
[BUG] D&D 5e Rules

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#399]
Attempting to navigate some chapters results in this error. Chapters 7, 8, 9, and 11 all error.

![image](https://user-images.githubusercontent.com/99844555/192682796-601dfec6-ed78-458d-be84-f14c81895a02.png)

https://user-images.githubusercontent.com/99844555/192682730-d311fccd-553c-4883-84bf-3ef8ea2500ad.mp4

Foundry 10.286
D&D 5e 2.0.3
MEJ 10.1

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
