### ISSUE TITLE
Error on drag items on Quest Journals

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#4]
tested on foundry 0.8.5, DnD5e 1.3.2.

When trying to drag an item to a quest journal, an error is raised:

![CleanShot 2021-05-31 at 10 34 35](https://user-images.githubusercontent.com/6490765/120166387-cec70180-c1fc-11eb-80a2-edfbba49c633.png)

**Comment by ironmonk88** [comment]
Fixed, will be in the next release.

**Comment by ironmonk88** [comment]
New Release has been uploaded.
