### ISSUE TITLE
[BUG] Dragging Quest Reward to Player Inventory

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#400]
Dragging a quest reward item from a Quest journal to an actor sheet errors and fails to add the item.

https://user-images.githubusercontent.com/99844555/192880120-b0347a51-85cc-4677-87f6-4712c426c4d8.mp4

![image](https://user-images.githubusercontent.com/99844555/192880206-b2ffa71f-9b6a-4842-b4be-0a7831dc41ff.png)

Foundry 10.286
D&D 5e 2.0.3
MEJ 10.1

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
