### ISSUE TITLE
[BUG] PF2E Issues (Text Links, Journal Configuration Icon)

### ISSUE THREAD

**Issue by Armandeus66** [ironmonk88/monks-enhanced-journal#401]
1. Links within a journal that go to another page in that journal do nothing when clicked, and all that happens is a tooltip saying, "Text Link" is shown. This can be seen when using the PF2E rules journal that is provided with the PF2E system. When using the default Foundry journal, these links work as expected.
2. The sheet configuration gear icon is not visible, making it impossible to set the type of journal sheet per journal. If you wanted to use the vanilla Foundry v10 journal for Journal A and this module for Journal B (because it has encounters, merchants, quests, etc.) you cannot. This is mainly needed as workaround for issue 1 above.

**Expected behavior**
1. Text links inside a journal should display the linked page when clicked, like default Foundry v10 behavior.
2. The configuration gear should be visible, allowing you to choose what journal (default or this module) you want to use for a particular journal. Why is this disabled?

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version v10.286
 - System Pathfinder 2e v4.1.3
 - Module version 10.3

**Comment by ironmonk88** [comment]
Text links should be working now.
The configuration gear is still there, I can't replicate it not showing up.
