### ISSUE TITLE
[BUG] PF2E Rollable buttons from Journal pages not working

### ISSUE THREAD

**Issue by SebastianH17** [ironmonk88/monks-enhanced-journal#403]
**Describe the bug**
In PF2 you can have rollable buttons that ask for skill checks or saves on chat or in handouts, unfortunately, if I turn on the module pushing or clicking those buttons does nothing.

**To Reproduce**
1 open a journal page with such a button
2 click it 

**Expected behavior**
Once such a button is clicked it either executes it for the token selected or gives an error message that the user needs to select a token. 

**Screenshots**
Added screenshots of a couple of buttons that work without the module active
![image](https://user-images.githubusercontent.com/84858570/193348019-b1e1654f-0a6a-4f01-8534-a794c4af2610.png)

**Please complete as much of the following information as possible:**
 - Browser Foundry Software
 - Foundry Version v10.286
 - System Pathfinder Second Edition v4.1.2
 - Module version 10.3
 - Are there any errors in the console [e.g. press F12 and look for red text] - no
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction? - no, but I tested it with just Monk's enhanced journal active

**Comment by ironmonk88** [comment]
Fixed in latest release
