### ISSUE TITLE
[BUG] Narrator Tools context options don't work in MEJ entries

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-enhanced-journal#405]
With normal Foundry v10 journal entries, (like text), you can select text, right-click, and choose either Describe or Narrate if you have the Narrator Tools module installed. For MEJ journals, those options aren't there and seem to have been overridden by MEJ's context options.

**Comment by amcvfx** [comment]
I can confirm that this happens in 9.269 as well!
I love both of these modules and it would be perfect if they could work together nicely.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release

**Comment by amcvfx** [comment]
Thanks! Works nicely
