### ISSUE TITLE
[BUG] PF2e Coins Distribution doesn't work, message in chat is a mess

### ISSUE THREAD

**Issue by Erfar** [ironmonk88/monks-enhanced-journal#406]
1. Coins distribution doesn't work (maybe because in PF2 system coins are items not some "GP" value)
2. Look Picture

**To Reproduce**
1.
• Enter number of Gold
• Add player to "character"
• Press "Distribute"
• Press "Split"
• Press "Distribute"

2.
• Enable "show chat message" in module setting
• Add item to Loot
• Drag from list to character

**Expected behavior**
1. Player actor recieve money
2. Message show art and name and not show "scroll"

**Screenshots**
2.
![image](https://user-images.githubusercontent.com/77942879/193933609-f4fcbe08-45f9-4a08-83ca-77854980a543.png)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version 10.286
 - System Pathfinder 2e 4.2.1
 - Module version 10.3
Error Message for first one:
EnhancedJournalSheet.js:559 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'update')
    at LootSheet.addCurrency (EnhancedJournalSheet.js:559:39)
    at LootSheet.addCurrency (EnhancedJournalSheet.js:626:33)
    at LootSheet.doSplitMoney (LootSheet.js:158:32)
    at DistributeCurrency._updateObject (distribute-currency.js:164:19)
    at DistributeCurrency._onSubmit (foundry.js:5874:18)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
