### ISSUE TITLE
Feature Request: Page Permissions Icons

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#407]
Just wondering if it might someday be possible to have the permission icon show up on the pages that aren't currently being viewed as well as the active page.

![image](https://user-images.githubusercontent.com/99844555/193971913-fbc6940e-6ea6-4d57-824b-c01fef26f3ef.png)

**Comment by joetheory** [comment]
Came here for the same reason.  Good show.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
