### ISSUE TITLE
Change SideBar Color

### ISSUE THREAD

**Issue by Eonagon** [ironmonk88/monks-enhanced-journal#409]
![image](https://user-images.githubusercontent.com/60485939/194320136-0b1207fc-7ebb-48aa-b5dc-591de7db6810.png)

The orange highlight on the Sidebar Tab is unflattering. Can this easily be changed?

Perhaps a dark red like DND5e uses in the line beneath the Heading Text.

**Comment by ironmonk88** [comment]
Yes, and no.
Honestly... I don't think the orange is the issue.  It's that it's completely lost what it means.
So I added a darker background to the active entries that make them stand out a little better, and the orange fits a little nicer with the darker background.
![image](https://user-images.githubusercontent.com/75920956/196834218-f8a5468c-9c7a-4e5a-b32e-617461ccebf5.png)

**Comment by ironmonk88** [comment]
Closing this as I think the spirit of the request has been fixed.
