### ISSUE TITLE
Scene Linked Notes Won't Open

### ISSUE THREAD

**Issue by Mist-Hunter** [ironmonk88/monks-enhanced-journal#41]
Hello,

I'm very excited to use this module. It looks great. (I'm also a big fan of your other modules). Just noticed that the built-in functionality of FVTT to link journal note to scene, and then recall it
![image](https://user-images.githubusercontent.com/6420684/123693914-80ae1980-d80d-11eb-8cfb-39e10b0eebaf.png)

Seems to just bring up a blank journal

![image](https://user-images.githubusercontent.com/6420684/123693942-87d52780-d80d-11eb-899d-c395e2ba595a.png)

I'm using FVTT 0.8.8, and 5e 1.3.6. I've disabled all other modules and verified that this issue persists with only this module enabled. I also tried creating a new scene, and re-linking an existing note with the same fault occurring.

Thanks again for the awesome modules!

**Comment by ironmonk88** [comment]
There's so many ways to open a journal entry, I'm always missing one.
This should be fixed in the latest release.

**Comment by Mist-Hunter** [comment]
Thanks!
