### ISSUE TITLE
[BUG] Newly Created Page Locations

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#411]
**Describe the bug**
Newly created adventure pages are created as the first page when MEJ is active.

https://user-images.githubusercontent.com/99844555/195228802-04ca53d3-acb2-4e51-9b6f-b66d2ab215ff.mp4

**Expected behavior**
Newly created pages are created as the last page with MEJ off.

https://user-images.githubusercontent.com/99844555/195228543-e2935712-7392-4d89-8bc4-cee7a13e767b.mp4

Might be worth a module option for some users?

Forge
Foundry 10.288
MEJ 10.3
D&D 5e 2.0.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
