### ISSUE TITLE
[BUG] Journal Entries Not Saving

### ISSUE THREAD

**Issue by ZBell** [ironmonk88/monks-enhanced-journal#412]
**Describe the bug**
When a player opens a journal entry and writes some amount of text, then tries to save it appears to save on their end but the data is not actually saved.  Errors appear in the console and if they close and reopen the journal the text they added to the entry and saved is not there.

**To Reproduce**
1. Go to the Journal directory and select an entry as a player.
2. Click on the edit button to edit the journal entry.
3. Click on the save button to try to save the entry.
4. See error in the console.  Sometimes the journal entry saves as expected, sometimes it does not.

**Expected behavior**
Expected the journal entry to save 100% of the time without throwing an error in the console.

**Screenshots**
I've uploaded a TXT file that contains the errors from the console.

**Please complete as much of the following information as possible:**
 - Browser: Chrome Version 106.0.5249.119 (Official Build) (64-bit)
 - Foundry Version: v10 288
 - System: D&D5e 2.0.3
 - Module version: 10.3
 - Are there any errors in the console: Provided in included TXT file.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Happens when only EnhancedJournal is active, as well as when other modules are active.

**Additional context**
During my testing today the entries saved normally, but the other day at the end of a session two of my players lost all of the notes they had taken, because the entries appeared to be saving on their end, but upon closing the journal and reopening it they noticed everything they'd typed up was gone.
[Monk'sJournalErrors.txt](https://github.com/ironmonk88/monks-enhanced-journal/files/9779442/Monk.sJournalErrors.txt)

**Comment by ZBell** [comment]
I'm glad to see the issue is fixed, you're awesome!  Thanks for all the hard work with all your different modules, they're great!

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
