### ISSUE TITLE
[BUG] Non-GM journal owner can’t add pages

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-enhanced-journal#414]
Describe the problem: A non-GM player with ownership permissions on a non-MEJ journal is unable to add pages to that journal. Have reproduced this issue in a test Foundry world with no modules except MEJ installed. When MEJ is disabled, adding pages works normally.

FTC verified
Foundry v10, build 288
D&D 5e system 2.0.3
MEJ 10.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
