### ISSUE TITLE
[BUG] Delete Checklist Entry

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#415]
The UI prompt for deleting a checklist entry calls it a folder despite not being a folder.

https://user-images.githubusercontent.com/99844555/197379109-365452a7-e1c2-4e80-99e6-efd18ada8ebe.mp4

![image](https://user-images.githubusercontent.com/99844555/197379187-e1f9ba33-a74a-437f-b44d-7ae35b83fc0d.png)

MEJ 10.3 and whatever the last one in V9 was.

**Comment by ironmonk88** [comment]
I think this was fixed in 10.4?

**Comment by Crowguard** [comment]
Yep; displaying correctly in 10.6.
