### ISSUE TITLE
[Feature Request] Ability for Players to delete checklist entries

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#416]
Currently deleting checklist entries in owned checklist journals is limited to GMs/assistant GMs; it seems players aren't given the right-click context menu (I'll confirm next time I have a test player logged in).

**Comment by ironmonk88** [comment]
I think this was fixed in 10.4?

**Comment by ironmonk88** [comment]
Closing as I believe it was fixed and I can't replicate.
