### ISSUE TITLE
[BUG] Write to Journal, Undefined.

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#417]
The first time this action writes to a journal, it always adds "undefined" at the end of the text. Subsequent actions are fine, even after clearing the journal text.
![image](https://user-images.githubusercontent.com/99844555/197467113-a42355ac-d01a-43ed-88f0-365e98dad67f.png)

MEJ 10.4

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
