### ISSUE TITLE
[BUG] Place Journal Entries breaking with Images

### ISSUE THREAD

**Issue by Ralxyr** [ironmonk88/monks-enhanced-journal#420]
**Description of the issue**
In v10.4 of the module, on any journal entry of the Place type, the image assigned to the entry loads on top of the header section with the title, thumbnail and other details that cannot be scrolled past.  If the image is small enough, or the dimensions of the journal are played so that the image shrinks, the rest of the entry can be seen and interacted with as normal, but the image cannot be interacted with in any way and gets in the way of using the journal.  Screenshots 1-3 demonstrate this.  

Old Place journals from prior to the update show the placeholder thumbnail above, as pictured in screenshot 4.  Newly created Place journals only have a tiny dot above the header, as shown in screenshot 5, but once an image is added it has the same issue described above, pictured in screenshot 6.

Interestingly, when a place journal is called by Enhanced Tiles, it can be scrolled past along with the header as shown in screenshot 7.

I rolled back to v10.3 to verify that this was not an issue there, and Place journals were displaying correctly in that version of the module.

**Screenshots**
Screenshot 1
![Screenshot (1)](https://user-images.githubusercontent.com/116758887/198121106-08f5be6e-f7c7-45e8-95f5-c3436b137165.png)
Screenshot 2
![Screenshot (2)](https://user-images.githubusercontent.com/116758887/198121109-7a7403af-705a-44c3-b211-c564febab5b1.png)
Screenshot 3
![Screenshot (3)](https://user-images.githubusercontent.com/116758887/198121112-15cb5d92-8b92-421e-b679-90e176131d61.png)
Screenshot 4
![Screenshot (4)](https://user-images.githubusercontent.com/116758887/198121120-7bc487d4-84f0-45a7-93da-335b254bf71f.png)
Screenshot 5
![Screenshot (5)](https://user-images.githubusercontent.com/116758887/198121126-fa5029e5-7461-4dec-bf8a-a8a11698092b.png)
Screenshot 6
![Screenshot (6)](https://user-images.githubusercontent.com/116758887/198121128-316585b1-2f20-41de-b265-44d1a28f13d5.png)
Screenshot 7
![Screenshot (7)](https://user-images.githubusercontent.com/116758887/198121309-edada2ac-e985-4d09-9da4-839c2243fc0d.png)
Screenshot 8
![Screenshot (8)](https://user-images.githubusercontent.com/116758887/198129137-45c4a0a6-de86-4d93-aa35-af161c296608.PNG)

**Please complete as much of the following information as possible:**
 - Tested in Foundry Client and Chrome v106.0.5249.119
 - Foundry Version 10.228
 - Pathfinder 2e v4.2.6 and v4.3.0
 - Enhanced Journal v10.4
 - I get the console error displayed in screenshot 8 when clicking on an Active Tile set to call the journal entry, but not when accessing the journal through the sidebar.
 - The issue persisted even when Enhanced Journal was the only module enabled through Find the Culprit.

**Comment by LtDerek** [comment]
I am having the same issue with DND 5e since the v10 update.

**Comment by Draigus** [comment]
same issue on Chrome and Edge Version 106.0.1370.52 
Foundry 10.288
DND 5e 2.0.3
Enhanced Journal 10.4

**Comment by tigue54** [comment]
Same thing for me
Foundry 10.288
DND 5e 2.0.3
Enhanced Journal 10.4

**Comment by Lannder13** [comment]
Same thing for me
Foundry 10.284
Tormenta20 1.4.006
Enhanced Journal 10.4

**Comment by PChur** [comment]
I am having the same issue for me too.
Foundry 10.288
DND 5e 2.0.3
Enhanced Journal 10.4

**Comment by DerJJ** [comment]
> I am having the same issue for me too. Foundry 10.288 DND 5e 2.0.3 Enhanced Journal 10.4

+1

**Comment by tigue54** [comment]
Always same with last 10.290 update

**Comment by tedesque** [comment]
Same behavior on browser Opera GX (core: 91.0.4516.106)
Foundry: 10.290 
Monk's Enhanced Journal: 10.4
System: World of Darkness 5e (Vampire) 2.0.2

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
