### ISSUE TITLE
[BUG] Sidebar menu drifts with each new image page added to any adventure book in journal section

### ISSUE THREAD

**Issue by ShimaHonnou** [ironmonk88/monks-enhanced-journal#422]
**Describe the bug**
The right-hand sidebar drifts towards center of the screen with each new image page or entry added to an adventure book in the Journal section. When it reaches about midway it will drift off screen, necessitating a program reboot as it is entirely inaccessible.

**To Reproduce**
1. Go to Journals
2. Go into an adventure book entry or create a new one
3. Add a page as an image page
4. Menu will drift upon page creation.

**Expected behavior**
The menu to remain locked where it should be.

**Screenshots**
![112](https://user-images.githubusercontent.com/117003799/198869664-d522617c-a8cc-427b-934c-2666e212ce7b.png)

**Please complete as much of the following information as possible:**
 - Browser: N/a, happening in Foundry itself
 - Foundry Version: 10.288
 - System: D&D 5e
 - Module version: 10.4
 - Are there any errors in the console [e.g. press F12 and look for red text]: No red errors, however testing shows that there are a bunch of lines of <div class="no-file-notification"><i class="fas fa-image-slash"></i> No image</div>, each one seeming to correspond with the location the menu drifts to and being added with each image page created. These may be at the end of the code list or nested under the line <div id="slideshow-canvas" class="monks-journal-sheet flexrow"><div class="slideshow-container flexcol playing"><div class="slide-showing"></div></div><div class="slide-padding"></div></div>, and deleting them drifts the menu back towards where it should be.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Unsure where this is as I've not had to troubleshoot Foundry before.

**Additional context**
Full module list:
Ace Library (1.8.3)
D&D Beyond Importer (3.1.22)
Dice Tray (1.5.2)
Dungeon Draw (1.0.1)
lib - Color Settings (2.9.0)
libWrapper (1.12.10.0)
Monk's Enhanced Journal (10.4)
Monk's Wall Enhancement (10.2)
Ownership Viewer (0.10.0)
Tokenizer (3.9.5)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
