### ISSUE TITLE
WFRP (warhammer fantasy roleplaying) color adjustment

### ISSUE THREAD

**Issue by Woche** [ironmonk88/monks-enhanced-journal#424]
Hi. 
Im using the journal and i like what it brings to foundry. unfortunatly it does not play well with WFRP
The colors when using different settings menus is almost unreadable. (See example picture)
![image](https://user-images.githubusercontent.com/11705420/199533244-d6c170dc-58b9-4b5b-93be-029eca05b046.png)

It would be great if you could fix the colors for warhammer so it become readable so more people can enjoy this module

Best regards. 
Fredrik

**Comment by ironmonk88** [comment]
Fixed in latest release
