### ISSUE TITLE
[BUG] Fallout 2d20 - Players selling to Shop yields 0 caps.

### ISSUE THREAD

**Issue by theMagius0** [ironmonk88/monks-enhanced-journal#429]
**Describe the Bug**
Players in the Fallout 2d20 system can successfully _purchase_ items from an Enhanced Journal shop.  but they cannot _sell_ items to an Enhanced Journal shop.

**To Reproduce**
1. Equip a Fallout 2d20 player character with any item that has a "COST" field value of "10" or "10 cap" or "10 caps".  _(Choosing 10 because it's a nice, round number here.  Trying 3 permutations in case singular/plural matter.)_
2. Drag the item to sell _from_ the player sheet _to_ an Enhanced Journal Shop.
3. Observe that the "Quantity" is correct in the "Confirm Quantity" dialog.
4. Observe that the "Price" and "Total" fields in the "Confirm Quantity" dialog are both "0 caps".

**Expected behavior**
Expected that the Shop will denote a "Price" and "Total" field greater than "0" in the "Confirm Quantity" dialog.

**Screenshots**
I've attached a screenshot.

**Please complete as much of the following information as possible:**
 - Browser: Firefox 106.0.5, Chrome 107.0.5304.107
 - Foundry Version 10
 - System Fallout 2d20 v10.0.0
 - Module Monk's Enhanced Journal v10.4
 - Are there any errors in the console [e.g. press F12 and look for red text]

When opening the "Shop", I get:
`Uncaught (in promise) TypeError: this.subsheet.goToPage is not a function
[Detected 2 packages: monks-enhanced-journal, lib-wrapper]
    _render enhanced-journal.js:117
    promise callback*_render enhanced-journal.js:115
    render foundry.js:5026
    openJournalEntry monks-enhanced-journal.js:1562
    clickNote2 monks-enhanced-journal.js:903
    call_wrapper libWrapper-wrapper.js:591
    _onClickLeft2#0 libWrapper-wrapper.js:189
    callback foundry.js:27702
    _handleClickLeft2 foundry.js:27916
    _handleMouseDown foundry.js:27878
    emit index.js:181
    dispatchEvent interaction.min.mjs:8
    processPointerDown interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    findHit interaction.min.mjs:8
    processInteractive interaction.min.mjs:8
    onPointerDown interaction.min.mjs:8`

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. No.

**Additional context**

**Comment by theMagius0** [comment]
Picture of error attached:

![Monks-Enhanced-Journal-Fallout-2d20-Shop-SellingTrading-Error](https://user-images.githubusercontent.com/85370867/200900545-a4793571-9385-463a-9566-11f6c8475fc9.png)

**Comment by kristkos** [comment]
I can also replicate this in PF2e

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
