### ISSUE TITLE
Player preview with side menu

### ISSUE THREAD

**Issue by krysztalzg** [ironmonk88/monks-enhanced-journal#43]
Hello, I'm looking on transitioning from OneJournal (still not updated for 0.8) into this one and for now I have good experience. Although I've found one thing that annoys me (Foundry 0.8.8, module 1.0.15). 
When `Allow Players` option is disabled my players see only the entry that they open without the side menu. If I enable it, it opens journal with side menu, but they don't see the content when they are not owners of the entry. 

```
enhanced-journal.js:769 Uncaught (in promise) Error: User Player 2 lacks permission to update JournalEntry [6Q1UYKWr74cT9uSq]
```

Okay, so I've debugged it a bit and it looks like just this line needs additional permission check:
```javascript
if ((game.user.isGM || setting('allow-player')) && (pack == undefined || !pack.locked))
    await entity.setFlag("monks-enhanced-journal", "_viewcount", (parseInt(entity.getFlag("monks-enhanced-journal", "_viewcount")) || 0) + 1);"_viewcount")) || 0) + 1);
```

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
