### ISSUE TITLE
Potential conflict message displayed when Advanced Macros is enabled

### ISSUE THREAD

**Issue by T-Whiz** [ironmonk88/monks-enhanced-journal#431]
When launching Foundry with Monk's Enhanced Journal and Advanced Macros enabled, the following message is displayed: "libWrapper: Potential conflict detected between module Monk's Enhanced Journal and module Advanced Macros. (See JS Console)"
This occurs when using Foundry (through The Forge) in v10.290 (did not occur in v10.288).

**To Reproduce**
1. Launch a world in Foundry (or refresh) with Monk's Enhanced Journal, libWrapper, and Advanced Macros enabled.

**Expected behavior**
No potential conflicts are identified.

**Screenshots**
Attached example screen shots and log (libWrapper Verbosity set to All) along with settings.

**Please complete as much of the following information as possible:**
Foundry Version: 10.290
Game System: dnd5e, 2.0.3
Hosting: The Forge
Active Modules: Monk's Enhanced Journal 10.4, Advanced Macros 1.18.1, libWrapper 1.12.10.0, The Forge 1.10
OS: Windows 11
Browser: Microsoft Edge Version 107.0.1418.42 (Official build) (64-bit)

**Additional context**
I wasn't sure whether this could result in issues at some point so I wanted to provide the details here for analysis if needed. The Advanced Macros module is enabled as a dependency for 3 other modules (D&D Beyond Importer (spell active effects), Midi SRD, More Automated Spells Items and Feats).

![conflict message-1](https://user-images.githubusercontent.com/101904996/201489554-c440ed08-511b-4e5e-acac-d10f0f172286.png)

![conflict message-2](https://user-images.githubusercontent.com/101904996/201489555-b33170cf-5bb2-4e48-832c-eb6ad77a8f59.png)
[example-log.log](https://github.com/ironmonk88/monks-enhanced-journal/files/9995666/example-log.log)
[settings.pdf](https://github.com/ironmonk88/monks-enhanced-journal/files/9995667/settings.pdf)

**Comment by mclemente** [comment]
Advanced Macros dev here. Its latest release has added an override of the `TextEditor._createContentLink` function to make it possible to run macros with arguments directly from documents.
As it is right not, it overrides MEJ's implementation. I've run some tests and adding a libWrapper wrap with the WRAPPER type seems to solve this issue.

**Comment by T-Whiz** [comment]
Thanks for taking a look, should I log this over in Advanced Macros instead? I wasn't sure about which repository was more appropriate.

**Comment by ironmonk88** [comment]
It's an Enhanced Journals issue.
Already been fixed... just waiting for the next release.

**Comment by T-Whiz** [comment]
Wow thanks so much! 😀

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
