### ISSUE TITLE
[BUG] Can't Configure Page Permissions for a Book in Alien RPG

### ISSUE THREAD

**Issue by rdefendi** [ironmonk88/monks-enhanced-journal#432]
**Describe the bug**
In Alien RPG, if Enhanced Journal Module is enabled, can't right click on a page to open the context menu. Therefore can't do things like configure permission for a page in a book, delete a page, etc.

**To Reproduce**
1. Make sure Enhanced Journal Module is active.
2. Open a book.
3. Right click on a page on the left navigation pane.
4. No menu. In fact, the info the that pane goes away.

**Expected behavior**
You should get a context menu.

**Screenshots**
Before Right Clicking:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/11877369/201496936-4acf8f71-7411-453d-a00b-3ca24bc5b6a4.png">

After right clicking:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/11877369/201497002-2e0781f4-fc8b-41df-b6d1-c3190a3806bf.png">

It looks like it's just collapsing the info in that pane on a right click.

**Please complete as much of the following information as possible:**
 - Browser UR Browser
 - Foundry Version v10 288
 - System Alien RPS
 - Module version 10.4
 - Are there any errors in the console Not proximate to the event.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes.

**Additional context**
I can't think of anything. I can give you access to the game if you need it to test, although the base module is free.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
