### ISSUE TITLE
[BUG] Cannot open default class items from DnD5e system compendium

### ISSUE THREAD

**Issue by kuchrk24** [ironmonk88/monks-enhanced-journal#439]
FoundryVTT v10.290
DnD5e v2.0.3
Enhanced Journals v10.5

Posted in the discord and was asked to log as a bug here.

I am receiving an error when trying to open a class item from the default system compendium. Disabling Enhanced Journals resolves the error.
![image](https://user-images.githubusercontent.com/74018852/203134545-508a94c4-1325-457c-be0b-935f3d7f7f05.png)

Context from discord convo:
![image](https://user-images.githubusercontent.com/74018852/203134610-b9693423-eb77-41b6-be5d-a7b8e06e3f38.png)

**Comment by sharkbruhaha** [comment]
is there an interim fix we can do ourselves?

**Comment by BladeFireLight** [comment]
I rolled back to 10.4

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
