### ISSUE TITLE
Feature missing show only picture in journal entry

### ISSUE THREAD

**Issue by Shenanigan83** [ironmonk88/monks-enhanced-journal#44]
Hi, I started to use this module a bit more thoroughly now. 

When creating entries (person, quests, organizations, etc..) There's an option to only show the picture when you want to show to players.  On the journal entry though, this option is not present. 

I put most of my GM notes in journal entries, if I add a picture to a room description for example, I dont want my players to show briefly all my stuff when I switch to picture :)     

thanks

**Comment by ironmonk88** [comment]
Should be added to the new release.
Thanks for catching that.
