### ISSUE TITLE
Change Link behaviour in Relationships

### ISSUE THREAD

**Issue by Morrinn** [ironmonk88/monks-enhanced-journal#446]
**Is your feature request related to a problem? Please describe.**
Currently, when I view the Relationship tab in most Journals, and there is a linked article, you can hover the cursor over both the image icon as well as the name of the related Journal. Clicking on the name of the related items has no effect, clicking on the Icon does two things simultaneously ; It opens up the full scale image of the image, as well as the related journal.

**Describe the solution you'd like**
It would be great if clicking on the icon would open the full scale image whilst clicking on the name would link to the related article

**Additional context**
![Xample](https://user-images.githubusercontent.com/66957287/204107791-f7db0d63-582b-426c-98a0-97775a93af79.png)

**Comment by ironmonk88** [comment]
Should be added to the latest version.
