### ISSUE TITLE
[BUG] Players can't edit journals with Polyglot

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#447]
Players are unable to edit owned journals when Polyglot is active. (Just MEJ journals. No issues with multi-page types.)

![image](https://user-images.githubusercontent.com/99844555/204696095-6a99b055-867a-4c1e-9b68-8e382cd530ff.png)

MEJ 10.6
Polyglot 1.8.5

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
