### ISSUE TITLE
Bug journal stop responding if you close all tabs

### ISSUE THREAD

**Issue by Shenanigan83** [ironmonk88/monks-enhanced-journal#45]
If you close all tabs at the top and then close monk's journal. You won't be able to re-enter monk's journal from the regular journal tab in foundry. Nothing respond when you click any journal entries. You need to log out and log back in the game to reset the journal. Im running Pf2e game system and foundry 0.8.8

![image](https://user-images.githubusercontent.com/81721224/124395266-1693e980-dcd1-11eb-99a9-66cea995cbad.png)

**Comment by ironmonk88** [comment]
I'm unable to replicate that.
There's been a bunch of changes, can you see if it's still an issue, and if it is, can you check that it's still an issue when Enhanced Journal is the only active module?
I'm wondering if there's interference from another module.

**Comment by Shenanigan83** [comment]
the issue seem to be fixed now with all that couple of updates since 2 weeks.  thanks :)
