### ISSUE TITLE
Item Shop Not Working in P2E

### ISSUE THREAD

**Issue by SacredDenizen** [ironmonk88/monks-enhanced-journal#457]
**Describe the bug**
Items do not appear in player inventory after purchase from a shop. Shop settings do not seem to affect this but item type does. Armor, weapons, and equipment do not work while consumables do. Gold is calculated perfectly fine and consumables act as intended.

**To Reproduce**
1. Play a Game of P2E on Foundry
2. Try to Buy Something from any Shop made with MEJ
3. Be Sad as the Item Does Not Appear
4. Profit?

**Expected behavior**
I expect to have a player buy an item, gold is subtracted from their sheet, and then the item be added to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/57823276/208592478-6ea9feaa-d7cb-418e-890f-51999cb6ed80.png)
That is an image of two attempts to buy items.

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version V10 Build 291
 - System Pathfinder 2E Version 4.5.1
 - Module Version: 10.6
 - Are there any errors in the console: Yes
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Yes, issue persisted with just MEJ active

**Additional context**

**Comment by ironmonk88** [comment]
I suspect that PF2E changed its item data.
If you remove the item and add it back from Compendiums, does it still fail?

**Comment by SacredDenizen** [comment]
I just tested all item categories. They do work as intended once replaced.
I will be sure to test that with any future issues, sorry for wasting your
time!

**Comment by ironmonk88** [comment]
I've seen it before, PF2E has a bad habit of changing the data structure of items, and because Journal Entries don't have items, the data MEJ stores is never updated properly.
On the plus side... I did find and solve another issue while troubleshooting.
