### ISSUE TITLE
[BUG] Unable to Edit / Write Journal without Polyglot installed

### ISSUE THREAD

**Issue by Rubengam3r** [ironmonk88/monks-enhanced-journal#462]
**Describe the bug**
I open an existing journal using the D&D 5e system and I am unable to open the editor to write or edit a journal

**To Reproduce**
1. Go to an existing journal 
2. Click on the Edit button

**Expected behavior**
I should see the text editor show up as before so that I can edit or write a journal entry
**Screenshots**

![Screenshot_20221228_095347](https://user-images.githubusercontent.com/32652791/209907825-9caaece5-86a1-4944-8432-030f3ad51c33.png)
![Screenshot_20221228_095758](https://user-images.githubusercontent.com/32652791/209907834-587d11d3-142b-443b-bfcb-de8d09c2c011.png)

**Please complete as much of the following information as possible:**
 - Browser Opera GX ( Chromium browser)
 - Foundry Version V10 Build 291
 - System  D&D5e
 - Module version 10.7
 - Are there any errors in the console yes see screenshot
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes and I have had just MEJ active and the problem was present

**Additional context**
Note: I do not have Polyglot installed when I had this error. But when I installed it I was able to edit.

let polyglot = (isNewerVersion(game.modules.get("polyglot").version, "1.7.30") ? game.polyglot : polyglot.polyglot);

I think it is this line of code in EnhancedJournalSheet.js it should be game.version 
its line 356

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
