### ISSUE TITLE
[BUG] Shop Item edits do not save (Custom System Builder)

### ISSUE THREAD

**Issue by JaydHawk** [ironmonk88/monks-enhanced-journal#463]
**Shop Item edits do not save**
When going into a shop and clicking "Edit Item" on an EquippableItem, the fields/name of item can be changed, but the changes do not save.

**To Reproduce**
1. Create a Shop.
2. Add an EquppableItem to the shop
3. Click "Edit Item"
4. Change the name of the item, edit fields, or anything else that can be changed.
5. Close the Item Window
6. Click "Edit Item" again
7. Notice that none of the item edits are there

**Expected behavior**
When editing an item, the edits should be retained upon closing the item window.

**Screenshots**
![Shop item edits Foundry App Console errors](https://user-images.githubusercontent.com/121692476/210107795-ef76a97b-6754-49fd-8de5-14cd12fd1099.png)

**Please complete as much of the following information as possible:**
 - Foundry App
 - V10.291
 - Custom System Builder V2.1.0
 - 10.9 (noticed on an earlier module though, thought this bug was already written and was going to fixed)
 - Console Errors in Screenshot
 - I have not used `Find the Culprit` to make sure it isn't a module interaction. I am not sure where to find that.

**Additional context**
![image](https://user-images.githubusercontent.com/121692476/210107709-15ac550c-f4af-407d-8bc1-bc066c57a544.png)

**Comment by JaydHawk** [comment]
![image](https://user-images.githubusercontent.com/121692476/210108081-d87e7e1f-2391-4683-94a2-f1f992474ace.png)
Thought maybe some settings would be helpful

**Comment by willarich** [comment]
Sorry to jump in. I don't know about your bug, but can I ask how you got it to recognize your currency in custom system builder?

**Comment by JaydHawk** [comment]
> Sorry to jump in. I don't know about your bug, but can I ask how you got it to recognize your currency in custom system builder?

I didn't get it to. If you look at the screenshot with my settings, I don't have any currency set. I just told the players to subtract currency themselves

**Comment by willarich** [comment]
Okay, thank you!

**Comment by ironmonk88** [comment]
Fixed in latest version.
