### ISSUE TITLE
[BUG] right clicking certain journal text in long format results in pop out menu being at the top of the journal 

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/monks-enhanced-journal#465]
**Describe the bug**
Discovered by Moto Moto in MeJ discord channel. Long journals and odd formats tend to make areas unable to use show in chat and extract options

**To Reproduce**
1. Make a super long journal
2. High light large section
3. Right Click highlighted text
4. Scroll up to top
6. No console errors known 

**Expected behavior**
Should see pop out menu at current view

**Screenshots**

https://discord.com/channels/862414864692281386/862421185211924540/1059370784193249280

**Please complete as much of the following information as possible:**
 - Firefox 
 -I am on dnd5e 2.0.3, foundry build 290, and with just the very newest MEJ(though it was also happening on 10.5) 
 -
![](https://media.discordapp.net/attachments/862421185211924540/1059242658226241586/image.png)

 - still occurred with only MeJ

**Additional context**Tested by crow

**Comment by Crowguard** [comment]
Uploading chrome_EKE9bWkxXa.mp4…

Just to add, the recording was made on

Foundry 10.291
MEJ 10.8
5e 2.0.3

**Comment by ironmonk88** [comment]
Fixed in latest version.
