### ISSUE TITLE
[BUG] Shop Owner

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#467]
Dragging an actor to a shop fails to add that actor as the owner. No errors. (Also doesn't work with Person journals, but I don't remember if that was actually possible before).

https://user-images.githubusercontent.com/99844555/210613196-01051866-7a3a-4934-824e-8edbe1cbb128.mp4

MEJ 10.9
Foundry 10.291

**Comment by ironmonk88** [comment]
Fixed in latest version.
