### ISSUE TITLE
[Bug] TypeError when clicking item or monster image in encounter journal type

### ISSUE THREAD

**Issue by JorreDeschuyteneer** [ironmonk88/monks-enhanced-journal#47]
![image](https://user-images.githubusercontent.com/23340533/124639138-1724af80-de8c-11eb-9627-48d4e7aa1ba2.png)

**Comment by ironmonk88** [comment]
Looks lie foundry changed the name of a function.
Will be fixed in the next release.

**Comment by ironmonk88** [comment]
Should be fixed now.
