### ISSUE TITLE
[Feature Request] Make the Objective Tracker Pinable.

### ISSUE THREAD

**Issue by Grandsome** [ironmonk88/monks-enhanced-journal#470]
Allow the objective tracker to stay on even when switching from Journal Notes mode to Token Controls mode.
Thank you.

**Comment by ironmonk88** [comment]
Do you mean this setting?
![image](https://user-images.githubusercontent.com/75920956/210941648-189a6a5f-6989-43f0-b277-c63505ea8353.png)

**Comment by ironmonk88** [comment]
Closing this as it already exists.
