### ISSUE TITLE
[BUG] Item Price (D&D 5e)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#472]
The price in the item description now reads ``object:object`` in D&D 5e 2.1.1. 

![image](https://user-images.githubusercontent.com/99844555/211925679-c4f42b6b-3a15-4cf8-a9aa-c56c3aca829e.png)

MEJ 10.10
D&D 5e 2.1.1

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
