### ISSUE TITLE
[BUG] Actor Sheet Formating

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#476]
Really minor one; actor tabs have a slight issue right here when added to MEJ.

![image](https://user-images.githubusercontent.com/99844555/212763522-a591a4e2-3e0c-45bb-91a0-06feec42ff7f.png)

MEJ 10.12
D&D 5e 2.1.2

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
