### ISSUE TITLE
[BUG] Map pins won't open in a new tab with setting "Open in new tab" activated

### ISSUE THREAD

**Issue by DarKDinDoN** [ironmonk88/monks-enhanced-journal#478]
**Describe the bug**
Hello,

When you click on a map pin, the journal entry is displayed, but it does not open in a new tab.
Instead, it replaces the current tab content.

**To Reproduce**
1. Go to settings and activate the setting "Open in new tab"
2. Place simple journal entries on the canvas (creating a map pin)
3. Double click one map pin then the other
4. The second map pin will open the associated journal entry but also replaces the tab content instead of opening a new tab

**Expected behavior**
Clicking on a map pin should open the journal entry in a new tab

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser firefox
 - Foundry Version 10
 - Module version 10.12
 - Are there any errors in the console no error

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
