### ISSUE TITLE
[BUG] Entering Core Journal Name

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#479]
Hitting the `enter` key in the title field of a core journal type results in this; does not happen in MEJ type journals.

https://user-images.githubusercontent.com/99844555/213303056-8ee1576b-2e53-4541-97ba-5d9546c26f9b.mp4

Foundry 10.291
MEJ 10.12

**Comment by Montegomery** [comment]
I came here to report the same issue.
