### ISSUE TITLE
[Suggestion] Create token from person note type

### ISSUE THREAD

**Issue by JorreDeschuyteneer** [ironmonk88/monks-enhanced-journal#48]
Ability to quickly add a token to the map using the image in a person type journal (using default stats).

**Comment by ironmonk88** [comment]
If you drag an actor onto the Person entry, it will link to that actor.
Next release will let you drag that token onto the Scene.
Good suggestion.

**Comment by ironmonk88** [comment]
Dragging the token to the Scene will create that actor.
