### ISSUE TITLE
[BUG] Token Dialog

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#480]
## Token Dialog

Dialog button doesn't show on the token HUD. 

![image](https://user-images.githubusercontent.com/99844555/213330837-4b5cd058-e6aa-40fb-9fa6-8c11d2b65d70.png)

![image](https://user-images.githubusercontent.com/99844555/213331131-be05a3b5-6646-4dac-9a7f-2be842dc371d.png)

## Unmovable/undeleteable Token
![image](https://user-images.githubusercontent.com/99844555/213331429-3855cce0-a4b9-49d0-a0a2-c7c1206eba41.png)

I'm not sure how to 100% replicate it; just dropping tokens on the scene with this toggle active seems to be part of the issue. Turning the toggle off let's me move them, but still unable to delete them and results in this error.  

![image](https://user-images.githubusercontent.com/99844555/213331056-866b7e14-0d54-4f14-a4cc-e9ea402a23bb.png)

https://user-images.githubusercontent.com/99844555/213330946-7cfa6c8a-e8a2-4fa3-90f2-28b2143ada26.mp4

## Full steps to recreate

Create checklist. Add it to a prototype token's config.

Drag token out while the Token Chat Bubbles is enabled.

https://user-images.githubusercontent.com/99844555/213352963-663ad502-5e7c-4c4c-aafc-de6a89fe35a3.mp4

## Another Error

~~Different error, but I suspect its related to the previous ones; it's only occurring in the world I had this happen in.~~ Was able to replicate the above errors, but I can't replicate this ATM. I'll move it to it's own ticket when I figure out the cause.

Trying to open a different journal with the journal window already open fails.

![image](https://user-images.githubusercontent.com/99844555/213332900-09f7c512-f4f4-4c73-b80a-9ab497e2fe9d.png)

https://user-images.githubusercontent.com/99844555/213332865-c84fb40c-58fb-4b33-bcf7-3b89f6fe33a6.mp4

## Info
Foundry 10.291
MEJ 10.12
D&D 5e 2.1.2

**Comment by weepingminotaur** [comment]
Having a similar issue where the dialog chat bubble feature does not work. (Pf2e system). 
<img width="729" alt="Screen Shot 2023-01-24 at 10 26 26 PM" src="https://user-images.githubusercontent.com/90105219/214474839-771bb120-076c-4045-b065-9ae4c922b015.png">

**Comment by Kofi-L** [comment]
> Having a similar issue where the dialog chat bubble feature does not work. (Pf2e system). <img alt="Screen Shot 2023-01-24 at 10 26 26 PM" width="729" src="https://user-images.githubusercontent.com/90105219/214474839-771bb120-076c-4045-b065-9ae4c922b015.png">

Same issue with me

**Comment by Crowguard** [comment]
Fixed in MEJ 10.15
