### ISSUE TITLE
[BUG] Offering, Add an Item

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#482]
~~Adding an item to an offering fails; there's no error in 5e, but PF2e gives this one~~

I'm a moron and was dragging it from the item directory;, but I'll leave this here for now due to the PF2e error in case that's a problem. Works as expected when dragging it from an actor sheet.

![image](https://user-images.githubusercontent.com/99844555/213604499-efa36511-33ef-4294-ac90-111a575aaba6.png)

Foundry 10.291
5e 2.1.2
Pf2e 4.6.8

**Comment by ironmonk88** [comment]
Provided a notification to let you know that items need to come from an Actor.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
