### ISSUE TITLE
[BUG] Shop Owner

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#484]
The right-click menu on shop owners doesn't work besides the `delete` function. Items aren't added, and the sheet isn't opened.
No errors in either system.

https://user-images.githubusercontent.com/99844555/213776514-ea5ecbef-220c-4600-a3a1-c7de607fc3c5.mp4

Foundry 10.291
MEJ 10.12
5e 2.1.2
PF2 4.6.8

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
