### ISSUE TITLE
[BUG] Quest reward

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#485]
1. Click `Assign Items to Loot Entity` with no items in the rewards. 
2. Any attempts to add an item to the quest rewards will now fail and result in this error.

![image](https://user-images.githubusercontent.com/99844555/213791874-a1185ab7-5370-497b-8428-6945c2e1a204.png)

3. Adding currency to the reward and attempting to assign to loot entity will result in these errors.

![image](https://user-images.githubusercontent.com/99844555/213792313-c68899bd-9d35-4185-b02f-bc2e101dfc79.png)

Foundry 10.291
MEJ 10.12
PF2e 4.6.8

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
