### ISSUE TITLE
[BUG] Item Price removed after purchase from Shop (Warhammer 4th Edition)

### ISSUE THREAD

**Issue by arturkonczalski** [ironmonk88/monks-enhanced-journal#491]
**Describe the bug**
Item price gets removed from it after purchase.

In shop item (manually added or via RollTable) has a set price. When player presses Purchase, it provides current price and that works fine.
However, when the item reaches Character inventory, the price gets removed from it. So when player wants to sell it back it doesn't show a original price, only 0 GC (or sometimes shows really unreal - from 2 Silver Shillings to 480 Gold Crowns). 

**Screenshots**
![image](https://user-images.githubusercontent.com/67600219/215365449-c2ae467c-8980-4fa2-926d-aadc5d742f8e.png)

**Please complete as much of the following information as possible:**
Foundry Version v10 build 291
Browser: Chrome v109.0.5414.120
System: Warhammer Fantasy Roleplay 4th Eddition v6.3.1
Monk's Enchanced Journal v10.12

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.

**Comment by arturkonczalski** [comment]
I can confirm, tested after update and it works fine. Thank you!
