### ISSUE TITLE
Add rarity as a column in shops item tab

### ISSUE THREAD

**Issue by MotoMoto1234** [ironmonk88/monks-enhanced-journal#495]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like to be able to see the rarity detail of the items in a shop in the shop rather than having to edit them to see.  

**Additional context**
I have shops that keep specific numbers of each rarity in stock at any given day.

**Comment by ironmonk88** [comment]
Should be added to the latest version
