### ISSUE TITLE
Error on dragging items in an encounter journal

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#5]
tested on foundry 0.8.5, DnD5e 1.3.2.

In an Encounter Journal, if you try to add a DC Configuration, but then close the window without adding it, it is no longer possible to drag items due to an error:

![CleanShot 2021-05-31 at 10 49 02](https://user-images.githubusercontent.com/6490765/120167525-21ed8400-c1fe-11eb-9ef2-050fda08a52b.png)
![CleanShot 2021-05-31 at 10 47 06](https://user-images.githubusercontent.com/6490765/120167539-25810b00-c1fe-11eb-8b37-ada0986f59aa.png)

**Comment by ironmonk88** [comment]
New Release has been uploaded, should be fixed.
