### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by Tam1974** [ironmonk88/monks-enhanced-journal#50]
Forge
0.8.8
All Modules up to date.
When the GM runs a slideshow, it works fine and the Players can see it fine.
When the GM runs a 2nd slideshow, the music can be heard by everyone, but the slideshow itself cannot be seen by Players, (in window or canvas setting), but the GM can see it. Then, when the GM stops this slideshow, the music carries on playing, for everyone, and there is no way of stopping it.
Thanks

**Comment by ironmonk88** [comment]
Is there an error in the console?
It sounds like there's an issue.  And its "crashed" the slideshow.  I tried to replicate it, got an error, but couldn't replicate that error again.

**Comment by Tam1974** [comment]
No error in the console. And it bugs out when you play different slideshows, not the same slideshow twice, I don't think I made that clear in the original comment.

**Comment by ironmonk88** [comment]
I think I figured it out, should be fixed in the next release.

**Comment by ironmonk88** [comment]
Should be fixed with the latest release.
