### ISSUE TITLE
[BUG]Loot sheet still showing Identified names on items instead of unidentified for pl1e

### ISSUE THREAD

**Issue by NorEtoc** [ironmonk88/monks-enhanced-journal#501]
When adding an item (Even an item that is marked as unidentified in the item details) the item shows in the list with the identified name.  It should be showing the unidentified name in the item list.   
It does show the unidentified description though.

Item screen shot.  You can see the identified name and unidentified name.  Also it shows the item marked as unidentified.
![image](https://user-images.githubusercontent.com/93835536/217716687-a90145cb-6184-45ff-b059-5952ae3d19db.png)
![image](https://user-images.githubusercontent.com/93835536/217716793-fb44454d-dd25-490e-8d27-bd9cdb383bb6.png)

Loot sheet screen shot from player view
![image](https://user-images.githubusercontent.com/93835536/217716978-b737a7d4-dfb7-4a02-a504-a8860b05fc50.png)

**Comment by ironmonk88** [comment]
Fixed in the latest release
