### ISSUE TITLE
[BUG] Opening a map not when the Enhanced is empty throws an error

### ISSUE THREAD

**Issue by DarKDinDoN** [ironmonk88/monks-enhanced-journal#502]
**Describe the bug**
Hello, when opening a map note with an empty enhanced journal, it throws an error instead of opening the journal entry.

**To Reproduce**
1. Load the world
2. Create a map note
3. Open the journal and close all tabs (the journal window should be emptied, and no journal entries should be previewed)
4. Double-click the map pin
5. An error is thrown

**Expected behavior**
The journal entry attached to the map note should open up
Note that "Open in a new tab" option is activated

**Screenshots**
![image](https://user-images.githubusercontent.com/1687854/218280610-d1ec9d3b-2b17-4327-86d2-aac01a43792c.png)

**Please complete as much of the following information as possible:**
 - Browser Firefox
 - Foundry Version V10
 - System Chroniques Oubliées Contemporain
 - Module version 10.14
 - Are there any errors in the console yes, see screenshot
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. -> no need, only this module is activated

**Comment by MotoMoto1234** [comment]
I think my issue is directly linked to this so I'm piggy backing on:

This error only occurs if you have this setting on:
![image](https://user-images.githubusercontent.com/116308065/218328627-1d130e88-e90a-4ba9-91c2-8b8e276dd2c1.png)

Once its on, right click the journal tab to open the journal up generally, close all existing tabs so you only have a new one open.  Then go to a map witha map pin that is properly setup.  Double click it, it opens the journal, throws the below error, and doesn't open anything.  If you double click again, same result.  The only way to open a journal entry is to use the right hand MEJ menu inside the journal window.  If you click off the setting above, the journal begins working right.  

![image](https://user-images.githubusercontent.com/116308065/218328601-caf5aa91-d746-414f-9cea-3e444485ce76.png)

**Comment by ironmonk88** [comment]
Fixed in the latest release
