### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set property 'menuItems' of undefined

### ISSUE THREAD

**Issue by WereDev** [ironmonk88/monks-enhanced-journal#51]
FoundryVTT: 0.8.8
MEJ: 1.0.17

Issue: When right-clicking on the Journal icon to open MEJ, the console is flooded with the error "Uncaught (in promise) TypeError: Cannot set property 'menuItems' of undefined".  This continues until a different journal entry is selected.  After closing the journal and reopening it the same way, this error does not reappear.  This only occurs the very first time when loading MEJ if that first time is via right-clicking on the journal icon.  It does reappear if you refresh the browser and try the steps over again. 
 The error count will get into the hundreds and just keep going until a different journal entry is selected.

![Screenshot from 2021-07-13 16-07-29](https://user-images.githubusercontent.com/16233329/125526216-fe16e8ef-9d6f-4104-a808-8d8f88dc8d5e.png)
![Screenshot from 2021-07-13 16-02-59](https://user-images.githubusercontent.com/16233329/125526232-aaace44c-a6f1-4546-8f07-b4b6cc826417.png)
![Screenshot from 2021-07-13 16-03-04](https://user-images.githubusercontent.com/16233329/125526239-a22af6a8-d60b-47df-864a-d9bc0a78b975.png)

**Comment by ironmonk88** [comment]
I'm having issues replicating it.
Does this still happen with Enhanced Journal as the only active module?

This is "sort of" happening because I have to create a dummy Journal Entry to open when right-clicking.  Since you're not clicking on anything, it doesn't know what to open yet.  But it's trying to load the temporary Journal Entry, and it shouldn't get that far.

And I'm unsure what's causing it to get into the loop.

**Comment by WereDev** [comment]
I created a brand new game with nothing loaded except the necessary DND 5e game system.  Enabled only MEJ. When right clicking I got 2 errors (need to reproduce to get details again) but not the long chain.  After that, I created a journal at root, a folder, and a journal entry within that folder.  Refreshing everything, then right clicking on the journal icon, I was NOT albe to reproduce this error.  I will do some testing to see what other module might because causing this issue.  Only thing I can think of at the moment is maybe Trigger Happy which has a journal entry the is used to link an actor to a scene so that you can create links from one scene to the next.  Handy for making maps that link to other maps.  Anyway, not sure if that's the culprit or not, but will do more testing as time allows to see if I can figure out the conflict.

**Comment by WereDev** [comment]
Turns out it's an issue with GM Screen.  It might be what #14 was referring to.

Just enabling GM Screen isn't enough.  If you add a journal entry to it, refresh the browser, then right click on the journal icon, I can reproduce this issue.  If I clear out GM Screen and leave nothing there, but the module still enabled, refresh the browser, and right click the journal icon then no error.  Not sure if this is something you can work around or if the developer of GM Screen needs to fix something on his end.

**Comment by WereDev** [comment]
GM Screen module for reference: https://foundryvtt.com/packages/gm-screen/

**Comment by ironmonk88** [comment]
Thank you so much for researching this!  I'll have a look at it.

**Comment by ironmonk88** [comment]
Issue with GM screen should be fixed in the latest release.
