### ISSUE TITLE
[BUG] Table cutoff in store items

### ISSUE THREAD

**Issue by MaineKnight** [ironmonk88/monks-enhanced-journal#510]
The items table seems to be extending beyond the frame so that the last item in the table is cut off. I was able to correct by adding a holder item "zzzzzz" to force the last item in the list to be visible.

** Found the issue, if the general settings>font is increased above the default "5" then this happens. ** 

![MonksEnhanced](https://user-images.githubusercontent.com/125476146/219060748-1fe45753-6818-4989-9d31-8f44f5ec8831.JPG)

**Comment by ironmonk88** [comment]
Fixed in the latest release
