### ISSUE TITLE
[BUG] Compendium Embeds not functioning in Objectives tab of Quest Journal Entry

### ISSUE THREAD

**Issue by AlexanderHardiek** [ironmonk88/monks-enhanced-journal#518]
**Describe the bug**
To start, the examples I give come from a D&D 5e configuration of Foundry. Compendium Embeds (such as those found for actor "Water Elemental" and the spell item "Conjure Elemental" in the description of the item "Bowl of Commanding Water Elementals") do not embed at all.

**To Reproduce**
1. Create New Quest
2. Add Objective
3. Edit Objective, Edit Objective Description, then use the "<>" in the toolbar to open the HTML for the description.
4. Paste in "<em>@Compendium[dnd5e.monsters.namJz755U1EhvEJa]{Water Elemental}</em>", which gives a correctly embedding embed in a vanilla text journal entry.
5. Save description HTML, save Description, close Edit Objective window.
6. The objective should now read "@Compendium[dnd5e.monsters.namJz755U1EhvEJa]{Water Elemental}"

**Expected behavior**
The embed should work just like in a vanilla text journal Entry.

**Screenshots**
See Attached Screenshots
![Screenshot_20230224_033436](https://user-images.githubusercontent.com/34132569/221297812-95c1fe87-9011-4cbb-be79-bf9c85a0ee5d.png)
![Screenshot_20230224_033454](https://user-images.githubusercontent.com/34132569/221297814-adaa4071-949c-4de0-8a8b-1e693e510fc7.png)
![Screenshot_20230224_033508](https://user-images.githubusercontent.com/34132569/221297817-be36bacc-cebd-46e2-bf64-3f155b370753.png)
![Screenshot_20230224_033515](https://user-images.githubusercontent.com/34132569/221297818-dfd2f91d-f3ce-4bc3-ac86-66765f0e0767.png)
![Screenshot_20230224_033537](https://user-images.githubusercontent.com/34132569/221297819-0fa53ee5-7d10-4910-90a1-ce802c831501.png)
![Screenshot_20230224_033546](https://user-images.githubusercontent.com/34132569/221297821-f3403939-01cf-4ccd-8209-9104053a1085.png)
![Screenshot_20230224_033554](https://user-images.githubusercontent.com/34132569/221297823-49629d24-224a-496a-b7af-8773dea7faee.png)

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version 10
 - 5e
 - Module version 10.14
 - No Console Errors that I saw
 - I don't know what `Find the Culprit` is

**Comment by AlexanderHardiek** [comment]
Let me know if this should be changed to a feature request.

**Comment by ironmonk88** [comment]
Fixed in the latest release
