### ISSUE TITLE
Ability to drag item into Journal entries not working

### ISSUE THREAD

**Issue by WereDev** [ironmonk88/monks-enhanced-journal#52]
Foundry: 0.8.8
MEJ: 1.0.17

When MEJ is disabled, I can drag actors, scenes, other journal entries, etc. onto a journal I'm editing to create a link.  That appears to be broken when MEJ is enabled.  Is this something that can be added back?

**Comment by WereDev** [comment]
This appears to be working at times when the journal entry is saved correctly.  Likely not a direct issue with drag/drop but more related to saving journals.

**Comment by ironmonk88** [comment]
I'm getting it intermittently too.
It looks like the code to set up the drag/drop functionality is not finding the correct window.  Or something is preventing the drag action.
I'm actually going to re-open it because I'm wondering if it's part of a larger problem.

**Comment by WereDev** [comment]
Since you reopened it, I did a bit more digging and I think I found a pattern.  When in edit mode of a section (duh) and you drag an actor/journal/etc. to any old open spot, it won't drop the item.  However, if there is text on the area, and you drag it to some spot over the text, you can kind of see that a cursor (|) appears in the text.  At that point, you and drop it and it will place the link.  On a completely empty journal entry, you have to get this all the way to the few pixels at the beginning of the entry to see the cursor and then it will drop it there.  So I think the pattern is that you have to drop it to some place where there is text.  I had sort of assumed that if I dragged it anywhere in the edit panel, it would just drop it to the end of the text block.

**Comment by ironmonk88** [comment]
Well... so it is.  I don't think I've ever tried to drop on a blank journal entry.
That is also my issue, as the core journal entry lets you drop anywhere.  I'll investigate what's going on.

**Comment by ironmonk88** [comment]
Not sure I can fix that.
Because I've added the option of a background I need to let the html and body tags expand so that the background shows on the entire screen.  But I can't set the min-height on html, and setting the height property prevents it from expanding.
So I'm kind of stuck.  The body can't be the full height because it has to expand with its contents.

**Comment by ironmonk88** [comment]
Closing this as I believe it has been fixed.
