### ISSUE TITLE
[BUG] Error when navigating between pages of enhanced journal

### ISSUE THREAD

**Issue by homiedion** [ironmonk88/monks-enhanced-journal#520]
Attempting to navigate between a Place and the embedded embedded Shops causes the following error

Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'shiftKey')
[Detected 1 package: monks-enhanced-journal]
    at PlaceSheet.open (modules/monks-enhanced-journal/sheets/EnhancedJournalSheet.js:958)
    at PlaceSheet.openRelationship (modules/monks-enhanced-journal/sheets/EnhancedJournalSheet.js:2283)

**Edit:** Occurs in both web browser and FoundryVTT browser.
The event value is being output as null.

**Foundry Version:** 10 build 291
**Module Version:** 10.14

**Comment by darkoutcast** [comment]
Receiving the same error when attempting to navigate between pages on Relationship tab.

Foundry Version: 10 build 291
Module Version: 10.14

**Comment by mcdaddytalk** [comment]
EnhancedJournalSheet.js

`line 2283:  this.open(journal)`
seems to be missing the passing of event
`line 2283: this.open(journal, event);`
corrects

**Comment by ironmonk88** [comment]
Fixed in the latest release
