### ISSUE TITLE
[BUG] libWrapper detect a Potential conflict detected with Starfinder system

### ISSUE THREAD

**Issue by coboye** [ironmonk88/monks-enhanced-journal#526]
**Describe the bug**
 libWrapper: Potential conflict detected between system Starfinder and module Monk's Enhanced Journal. (See JS Console))

**To Reproduce**
1. Install libWrapper (module) conflict checker
2. Open a Starfinder based world
3. Open chrome console or libWrapper settings

**Expected behavior**
no conflict between module and system

**Screenshots**
![image](https://user-images.githubusercontent.com/3914689/222472428-a652abd9-3462-43eb-a96f-5b4686668ed8.png)

**Please complete as much of the following information as possible:**
 - Browser: Chrome 110.0.5481.178
 - Foundry: Version v10.291 on Forge-VTT
 - System: Starfinder
 - Module version: (last 10.14)
 - Are there any errors in the console: (see screenshot)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: no need

**Comment by ironmonk88** [comment]
Nothing much I can do about the conflict but I'll add it to the ignore list so it doesn't get shown.

**Comment by ironmonk88** [comment]
Closing this ticket, added to the ignore list.
