### ISSUE TITLE
Entries need to auto-save if you switch while there are unsaved changes

### ISSUE THREAD

**Issue by GameMaker** [ironmonk88/monks-enhanced-journal#529]
**Is your feature request related to a problem? Please describe.**
I just lost an hour and half of writing because I went to look something up in another journal entry, and didn't hit Save first. I keep getting bitten by this.

**Describe the solution you'd like**
If you are editing a journal entry and have unsaved changes, and do ANY action that would close the entry or cause you to lose work (click on another entry, close the journal, etc.), automatically save it.

Some people might not want this behavior, so you could add a setting specifying whether to auto-save or not.

I'll see if I can take a look at it and maybe send you a pull request.

**Comment by ironmonk88** [comment]
That's a bug.
It does warn you... but Foundry changed the editor id, and I didn't notice that happened.
Fixed for the next release.

**Comment by GameMaker** [comment]
Ah, awesome - thank you! Look forward to the next release.
Just in case it matters, a little more info: It didn't warn me at all. I was in Journal entry A with unsaved edits. I clicked on entry B in the Enhanced Journal ToC, and it switched to Entry B without saving and without warning. Windows 11, V10 Build 291 of Foundry, V10.12 of Enhanced Journal.

**Comment by LukasDJacobs** [comment]
Can confirm, didn't warn me as well. Just lost almost two hours as well. Glad to see this fixed in the next release!

**Comment by ironmonk88** [comment]
Fixed in the latest release
