### ISSUE TITLE
"You have unsaved changes..."

### ISSUE THREAD

**Issue by WereDev** [ironmonk88/monks-enhanced-journal#53]
Foundry: 0.8.8
MEJ: 1.0.17

When editing a journal entry and then trying leave, I get presented with a popup saying that I have unsaved changes and do I wish to leave.  When clicking yet, all changes appear to be saved.  Also, there doesn't appear to be a save button that prevent this popup from appearing.

**Comment by WereDev** [comment]
Whether or not items save appears to be intermittent.  I haven't found the pattern yet.

**Comment by ironmonk88** [comment]
This should be updated.  Honestly it was just a blanket "is the editor open" for this message, but I've gone back and updated the code so it will check to see if the editor is active and if changes have been made.  Should work a little smoother now.

**Comment by WereDev** [comment]
I actually just figured it out.  I can get stuff to save and not get that popup if I click the pencil icon near the top of the MEJ window.  You know, where the other icons (eye, pencil, clipboard, etc) are.  I had been thinking I could click on the kind of greyed out pencil in the edit area to get that to change, or thought there would be save button near the bottom as on other Foundry pages.  Since discovering that I could use the pencil near the top to jump into and out of edit mode, and that it would save changes, I can avoid the popup message.  It might be worth it to make a more obvious save button near the bottom. At least for idiots like me. :)

**Comment by ironmonk88** [comment]
And I've been using it for forever so don't think twice about that button.
I'll see if I can change the pencil to a save icon while editing.
If the icon changes, that should make more sense.

**Comment by WereDev** [comment]
My thought was something like a Save button at the bottom like here.  But your stuff is awesome so I leave it all up to you. :)

![Screenshot from 2021-07-13 20-38-42](https://user-images.githubusercontent.com/16233329/125547149-2e1f627f-4ef8-49d2-b698-29db1d7dc4e4.png)

**Comment by WereDev** [comment]
Since I'm being nitpicky, I thought I would also say thank you for all your hard work.  I'm impressed with how much you've done in the Foundry space and with how quickly you respond to questions and issues.  Sent you a thank you on your Patreon.  You really should advertise that more. :)

**Comment by ironmonk88** [comment]
I'd thought about the save button at the bottom... but, I opted for more vertical space while editing.
Those other pages are mostly forms, with a lot of input controls.  But, Journal Entries tend to be a bit more free form.
I know it's a bit of a departure from the standard (and I'm a big fan of standards) but I felt the extra screen space was worth it.

Saw the Patreon!  Thank you very much.  It's appreciated.
I always worry about advertising more coming across as being too pushy.
Where do module developers tend to advertise these days?

**Comment by ironmonk88** [comment]
Also... have I invited you to my Discord server yet?
Send me an IM on Discord if I havn't.  Makes it easier to update people on changes.
