### ISSUE TITLE
[BUG] Players cannot drag items to Loot sheet without GM and Items lost

### ISSUE THREAD

**Issue by bkvam** [ironmonk88/monks-enhanced-journal#530]
Players cannot add items to Loot journal entries that they are the owner of if the GM is not logged in. 

If they drag an item into a loot sheet it disappears from the character sheet inventory, but does not appear in the journal entry. The Player Receiving setting for the loot entry is Anyone. 

The players can set the Currency values while the GM is not logged in. The players have permission to create new actors and new items.

If the player is not the owner of a journal it makes sense that a GM should be present, but if the player is the owner of the journal entry no GM should be required and they should be able to modify it freely, as if it were any text journal entry that they owned.

To reproduce:
Log in a player while no GM is logged in.
Open a character sheet.
Open a loot journal entry.
Make the player the owner of the loot sheet and set Player Receiving to Anyone so that no confirmation is required.
Drag something from the player inventory into the loot sheet.
It disappears from the inventory but does not appear in the loot journal entry.

If the GM is logged in it works as expected.

If you agree that players should be able to add and remove items from loot journal entries that they own, then it should allow these transactions to take place.

If you think that GM presence is required for all loot journal entry interactions regardless of ownership and Player Receiving settings, then the bug is that items dragged from character inventory to the loot journal entry are simply lost. In this case a notification should appear saying that GM presence is required and the item should be left in the character inventory.

System:
Foundry v. 10.291
DnD5e 2.1.5
Monk's Enhanced Journal 10.14
Same issue on Chrome and Edge

The console (F12) gets a 404 (Not found) error for the icon associated with the dragged item all the time, whether the GM is logged in or not. The icon appears in the entries anyway, so this appears to be a spurious error.

**Comment by ironmonk88** [comment]
Fixed in the latest release
