### ISSUE TITLE
Feature Request: Add image from Actor when linking to Person

### ISSUE THREAD

**Issue by RyanD** [ironmonk88/monks-enhanced-journal#533]
**Is your feature request related to a problem? Please describe.**
If I have to use actors for some features (shopkeepers) and Person journals for others, it'd be great if when I make a person journal and link a person, it'd be great if it would use the image assigned to the actor to skip a repetitive copy-paste (especailly since at least with Tokenizer addon, it's not straightforward to get path of an actor's image in the UI)

**Describe the solution you'd like**
When I drag and drop an actor onto a Person journal entry, I'd like it to use the same image for the Person entry.  Whether its automatic, a pop-up (not ideal from UX standpoint but may be most appropriate given context) or maybe even a toggle to enable it to be automatic.. anything that prevents me from having to find the actor's image path and apply it to the Person journal.

**Additional context**

**Comment by ironmonk88** [comment]
Added to the latest release.
