### ISSUE TITLE
Macro Command

### ISSUE THREAD

**Issue by GarebearNF** [ironmonk88/monks-enhanced-journal#536]
This item may be more out of my own ignorance, but with the function to right-click the journal tab and open the Enhanced Journal, I was hoping to make a macro to mimic this function. Unfortunately, I haven't been able to zero in on the proper function being called here.

Can someone point me in the right direction to create this macro?

Thanks!

**Comment by ironmonk88** [comment]
`game.MonksEnhancedJournal.openJournalEntry(document, options)`
Both document and options are optional.
Document is the Journal Entry document.
Options can have a bunch of things in it, but `pageId` and `anchor` would be the most used.

**Comment by ironmonk88** [comment]
Closing this as the question has been answered.
