### ISSUE TITLE
Links between journals are broken

### ISSUE THREAD

**Issue by mabbott093** [ironmonk88/monks-enhanced-journal#539]
**Describe the bug**
Links in the Townsfolk or Relationships tab no longer work. I can place a Person into a Place or Shop journal but when I go to the Townsfolk or Relationship tab I can no longer click on the name of that Person to bring up their journal. It still shows the linked journal (Person name, picture, relationship if added) but to open the Person journal I have to look it up using the search journal search bar.

**To Reproduce**
1. Go to a place journal that has a linked person journal
2. Go to Townsfolk tab
3. Click on the name of the linked Person journal
4. Nothing happens

**Expected behavior**
It should bring up the Persons journal

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version 10.291
 - System Pathfinder 2e - 4.9.3
 - Module version - Monk's Enhanced Journal 10.14
 - Are there any errors in the console No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. No

**Additional context**
This started happening about 30 days ago, I have not figured out why.

**Comment by mabbott093** [comment]
Sorry, I don't understand what I have to do to fix this.

**Comment by weepingminotaur** [comment]
You don't have to fix it. I was just adding a screenshot of the console error for Monk's benefit so he can fix it. Basically, I'm experiencing the same issue as you are.

**Comment by mabbott093** [comment]
Got it, thanks for adding to the post. I was not sure if it was only me becasue I was not seeing anyone with quite the same issue.

**Comment by Syrious** [comment]
Same here but with System DnD 5e

**Comment by mabbott093** [comment]
I am the original poster, I just ran all the updates on my mods and still no luck. Hope this gets fixed soon, it was a huge help when it worked.

**Comment by ironmonk88** [comment]
Fixed in the latest release
