### ISSUE TITLE
Feature Request: Exempt Locked Items in Shops from Easy Deletion

### ISSUE THREAD

**Issue by harrisog** [ironmonk88/monks-enhanced-journal#542]
**Is your feature request related to a problem? Please describe.**
When using rollable tables to populate shops, it would be nice to be able to pick and choose particular items to "rollover" while still clearing out and replacing the rest of the shop's inventory.

**Describe the solution you'd like**
Possibly the Lock Item functionality could be extended to designate items as exempt from casual deletion, or an option to this effect could be added to the Populate From Rollable Table dialog.

**Comment by weepingminotaur** [comment]
Absolutely seconding this request.

**Comment by ironmonk88** [comment]
Added to the latest release.
