### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by fischecj** [ironmonk88/monks-enhanced-journal#543]
**Describe the bug**
Shops throw an error to the console when attempting to purchase an item/actors cannot purchase

**To Reproduce**
Create shop, attempt to buy item

**Expected behavior**
Actor can buy item/shop subtracts currency and adds item to actors inventory sheet

**Screenshots**
![image](https://user-images.githubusercontent.com/84974011/229852187-7ff1056d-a54f-429d-9db6-3be5a9328502.png)

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version V10
 - System Level Up Advanced 5e
 - Module version 
 - Are there any errors in the console [e.g. press F12 and look for red text]:  Yes, included as screenshot
 - Have you tried using `Find the Culprit` Yes

**Additional context**

**Comment by ironmonk88** [comment]
Fixed in the latest release
