### ISSUE TITLE
Include "Jump to HTML Slug" for Journal Entries

### ISSUE THREAD

**Issue by azarius74** [ironmonk88/monks-enhanced-journal#544]
**Is your feature request related to a problem? Please describe.**
Mr. Primate uses "Jump to HTML Slug" (see Screenshot) in his DNDBEYOND IMPORTER mode, which, when PINS are created from dragging Journal HEADINGS onto the canvas, it creates direct links to that Page/Header.  

Unforunately using the Importer & MEJ, MEJ seems to override the HTML Slug and when I drag journal headings to the canvas, it only goes to the journal page (the PAGE heading in the screenshot provided)

**Describe the solution you'd like**
Add "Jump to HTML Slug" to MEJ

**Additional context**
![image](https://user-images.githubusercontent.com/54143707/230454441-d5d57781-5beb-4749-966a-46612627f001.png)

**Comment by MrPrimate** [comment]
Context, this is what it's doing:
https://github.com/MrPrimate/ddb-importer/blob/main/src/hooks/ready/anchorInjection.js

**Comment by ironmonk88** [comment]
Added to the latest release.
