### ISSUE TITLE
[BUG] Line going through float tables

### ISSUE THREAD

**Issue by Kharmans** [ironmonk88/monks-enhanced-journal#548]
**Describe the bug**
When a header text 1 or 2 is next to a float table, the line bellow the text go right through the table.

**To Reproduce**
Just create a header text 1 or 2 and a float table next to it.

**Expected behavior**
The line don't go through the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/112586547/230538895-cbb00dff-7610-4b7c-ab12-28ba0370b6ab.png)

**Please complete as much of the following information as possible:**
 - Browser: Opera GX LVL4 (core: 96.0.4693.127)
 - Foundry Version: v10.291
 - System: D&D5e
 - Module version: v10.14
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No.

**Comment by WizardForHire123** [comment]
What type of journal are you using to achieve this?

**Comment by Crowguard** [comment]
Could you export the journal JSON and share it please?

**Comment by ironmonk88** [comment]
Closing this as there's been no response to asking for the journal JSON, and the line through the float tables isn't really a MEJ issue and more the formatting of the document.
