### ISSUE TITLE
Conflict between module "Collapsible journal" and "MEJ"

### ISSUE THREAD

**Issue by guifa11** [ironmonk88/monks-enhanced-journal#55]
Foundry 0.8.8 
MEJ 1.0.17
It seems there is a problem with LibWrapper + MEJ + Collapsible journal sections. When the 3 are activated every journal I open makes my game extremely slow to the point of crashing.
Images showing the problem:
https://i.imgur.com/0GUpw8c.png
https://i.imgur.com/Gwht3oa.png

**Comment by ironmonk88** [comment]
Closing this as the ticket is old and I can't replicate.
Assuming it's been fixed.
