### ISSUE TITLE
Add ability to "Save" notes in "Quest" journals.

### ISSUE THREAD

**Issue by devteamplus** [ironmonk88/monks-enhanced-journal#553]
**Problem:** 
When users/players enter notes into a Quest Journal notes area, the information typed does not save unless the focus leaves the text area.  This can be quite frustrating when a player makes copious notes, and then leaves/closes the journal - not knowing their information will not be saved.

**Suggestion:**
Add an obvious way for entered information to be saved (button), or have it "auto-save" as they type.

**Comment by ironmonk88** [comment]
Fixed in the latest release
