### ISSUE TITLE
[BUG] Offerings Issues

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#555]
Not sure if these are all symptoms of the same issue or not; let me know and I can split this up.

## Extra Blank Icon for PF2 Currency
Currencies seem to having a blank icon added above them in PF2. 

![image](https://user-images.githubusercontent.com/99844555/235251281-10a44e5b-502f-4a9d-8bce-b03d8861f38c.png)

## Savage Worlds Icons

User is reporting that all item icons are blank after being accepted or rejected in SWADE 2.2.5. Can't confirm due to issues with the SWADE system currently. (Currency is always blank there apparently.)

![image](https://user-images.githubusercontent.com/99844555/235253008-0144ede0-5252-4370-af99-c494da678fb5.png)

## Can't See Quantity Column

Doesn't seem to be showing quantity.

PF2 4.11.0
SWADE 2.2.5
MEJ 10.14

**Comment by ironmonk88** [comment]
There is no quantity column, it gets prepended to the item text.
