### ISSUE TITLE
Shop "Refresh"

### ISSUE THREAD

**Issue by zeldafreak6245** [ironmonk88/monks-enhanced-journal#556]
Good afternoon,

I was wondering if it would be possible to add some new functionality to the shops- specifically by either allowing a "preset" to be created, using multiple rolltables if desired, as well as a "refresh" button, which removes all items from the shop and re-adds them using the rolltables previously assigned. 

It is important for multiple rolltables to be usable as many DMs sort their rolltables based on item types, armor, melee weapons, ect. 

Feel free to reach out for any clarification- thank you!

**Comment by ironmonk88** [comment]
You can already do that.

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/75920956/bf37c108-f9cd-4e02-b9f7-235dbd3ee7dc)
There's a clear button that will remove all items.
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/75920956/a030ce15-f82c-4caf-81e1-05c1794b75ed)
And a checkbox when adding items from a rolltable to clear out the current items with the new ones.

You can create a rolltable with other rolltables as entries.
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/75920956/22f8ed8d-0bc4-4c14-a626-52decb73fa6d)
That way you can have a shop with items of multiple different types from multiple roll tables.

If you need a specific number of items from each shop, then you'd have to do that individually where you have more control.

MEJ does store the last roll table that was used to populate the shop, so the next time you click on the roll table button it will automatically select that one.

And if you need to create a "preset" then I'd suggest creating your shop, and exporting it to a compendium.  That way you can drag and drop one of those shops into your world whenever you need it.

also if you're using 5e, I do have a module called Monks Shops that's a compendium of pre-generated shops you can use.

**Comment by zeldafreak6245** [comment]
Thank you, I was unaware of that ability. This allowed me to do what I was looking for, thank you!

**Comment by ironmonk88** [comment]
Also... I added the ability to drag and drop another shop onto a current shop's items to "fill" the shop with those items.  That way if you have a shop already set up, you only have to drag and drop to refill it.
But that's for the next version.
![AddToShop](https://github.com/ironmonk88/monks-enhanced-journal/assets/75920956/24f8f3ef-3c39-4ded-a34b-1d3c5f066e54)
