### ISSUE TITLE
Logging all purchases

### ISSUE THREAD

**Issue by myrduende** [ironmonk88/monks-enhanced-journal#558]
(Using Monks Enhanced Journal in pathfinder 1e)

When an item is purchased with GM approval, the request is posted into chat, creating an artifact showing item was purchased.  If the shop is set to allow Anyone to buy, when an item is bought or sold, no chat entry is generated and there is no notification from a GM perspective that the event occurred.  For a general store, not a big deal.  But for specialty shops or when buying selling/magic items, the GM would usually like to know such transactions occurred, but without having to impose an "approval" step.

1) At a minimum, it would be useful if any purchase or sell from the shop posted into the chat window, providing at least notice to a GM that a transaction has occurred.

2) Even better, if each shop generated a log of purchase and sell (in a new tab in the shop) history, that would be very useful over time.  (But likely a lot of additional coding?)  Something like "character x bought item y for z price" or similar.   Perhaps, as a GM selectable option, the notes Tab could be used to record this information (appending to existing Notes), but a new tab would be optimal.

**Comment by ironmonk88** [comment]
Added to the latest release.
