### ISSUE TITLE
[BUG] Open one Picture with right click, opens several clones

### ISSUE THREAD

**Issue by LEronsn** [ironmonk88/monks-enhanced-journal#56]
When you open a picture from the journal with the RMB, it will open several clones of this picture. Maybe this affects me because of other modules. But when I deactivate Monks Enhanced Journal, the program acts normally and only one picture will open.

**Comment by ironmonk88** [comment]
Can you send me a screenshot of what you mean?

**Comment by ironmonk88** [comment]
I think this should be fixed in the latest version.
Can you let me know if this is still an issue?

**Comment by ironmonk88** [comment]
Closing as there's been no response and I'm tidying up tickets.
