### ISSUE TITLE
[BUG] My Players can read Journal entries but I (the GM) cannot

### ISSUE THREAD

**Issue by verrillion** [ironmonk88/monks-enhanced-journal#561]
**Describe the bug**
I loaded up this module in the 'Simple World Building' system and can create journal entries of all types, the browser works well and navigates fine, but for whatever reason the actual contents of the page does not show when I attempt to open them. This seems to only affect me (the GM) and not my players, even notes I edited they can see fine. I thought it might an incompatibility with another module so I turned off every module I have and reloaded with only Monk's Enhanced Journal and I was still having this problem.

**To Reproduce**
Open up a world on 'Simple World Building' create a journal entry, type something in, I wasn't able to see it after done editing, and the pages seem to wig out, although from the 'player' view it should still work and be fine.

**Expected behavior**
To some extent this is a minor issue because a lot of my journaling is actually for my players but I would like to be able to see my own notes. 

**Screenshots**
This Image is what MY screen (the GM) looks like.
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/118383693/0db881b5-b709-4d78-92ca-a9e87ddbe726)

This Image is what one of my Players see.
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/118383693/9340f1e5-8d3e-4adf-8fa2-e63e703e6f14)

**Please complete as much of the following information as possible:**
 - I'm using the Foundry program it self
 - Foundry stable version 10.
 - System: Simple World Building

**Additional context**
Just to reiterate, when I was testing I disabled ALL my modules except Monk's enhanced journal, the only thing I could think of is if it was was with the System and it does seem to work for my players so it IS being edited, just in my personal browser of the Enhanced journal the pages do not display one last little thing, is that when I first enter a section it looks *fairly* normal but when I attempt to click into a page there is a small glitch that appears that seems to give feedback to it not working.

This is what it looks like when I haven't clicked anything, just simply opening the journal:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/118383693/207127e3-a267-451e-9617-77a3ad6b819c)

This is what it looks like when I attempt to click a journal entry:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/118383693/227c57a5-1dda-49f3-9783-91f7af753931)
As you can see the left bar lifts up slightly and out of place, but it becomes unresponsive past this.

**Comment by ironmonk88** [comment]
Fixed in the latest release
