### ISSUE TITLE
[BUG] Polyglot Conflict

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#565]
Unable to edit MEJ journals with Polyglot active.
https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/0c4e0d5f-319e-48c1-9268-acacb7cf99a9

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/181676ef-d8bd-49f6-8a1b-1d6a19e261ee)
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/b04bf31a-5405-4375-8e33-ccb9b0cb8712)

**Comment by jfrazierjr** [comment]
I have been getting this for a while.    Looks like there is a case change issue in Polyglot???:

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/2130984/22c0e05b-8cee-4e54-ab9f-32e9745a97de)

**Comment by Didou518** [comment]
Got the same issue,
replacing `LanguageProvider` by `languageProvider` in both `monks-enhanced-journal.js` and `sheets/EnhancedJournalSheet.js` solved the problem.
There are a total of 6 occurencies across both files.
