### ISSUE TITLE
[BUG] All journals are blank after update

### ISSUE THREAD

**Issue by XiaoKe89** [ironmonk88/monks-enhanced-journal#568]
**Describe the bug**
All journals open blank

**To Reproduce**
1. Open any journal that was previously an enhanced journal entry

**Expected behavior**
The journal entry opens like normal

**Screenshots**
![Screenshot 2023-06-03 233118](https://github.com/ironmonk88/monks-enhanced-journal/assets/86465316/41bf42af-26d7-43b8-9eb3-0e1852affa6b)

![Screenshot 2023-06-03 232930](https://github.com/ironmonk88/monks-enhanced-journal/assets/86465316/3ca69236-ab2b-43a9-aadd-0dae51c71f55)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version 10.291
 - System DnD5e v 2.2.1
 - Module version 10.15
 - Are there any errors in the console? Yes, Included the error in the screenshot above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes issue still persists with only enhanced journal active

**Additional context**
I wasn't having this issue with the previous version, however I was having the polyglot bug where you couldn't edit anything so I was hoping the new version would have resolved that bug

**Comment by XiaoKe89** [comment]
Just adding to this, I rolled the mod back to 10.14 and everything opens like normal, it only does this in 10.15

**Comment by ironmonk88** [comment]
Fixed in the latest release
