### ISSUE TITLE
[BUG] Visual UI bug

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/monks-enhanced-journal#570]
**Describe the bug**
When using a journal while Monks journal sidebar is enabled in mej the sidebar drops below the journal instead of scaling down or hiding. May be intended

**To Reproduce**
1. open a  journal 
2. Click on the collapse sidebar menu to disable then reenable
3. shrink the size of the journal window  
4. scroll down to see the sidebar below the text. 

**Expected behavior**
I would expect it to hide or scale the sidebar rather than have set size boundaries

**Screenshots**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/98988680/dba4df36-98a7-4cc6-9f15-0aea5753b808).

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/98988680/9359d1e3-51a7-476e-98aa-e2789b7c8f7e)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version 10.291
 - System PF2e
 - Module version  10.015
 - Are there any errors in the console [
 
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/98988680/9ee15088-0434-4e3f-9042-e93640662f84)

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yep
 - 
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/98988680/ecb87447-38f3-4b55-8296-c52ed44e053c)

**Additional context**

**Comment by ironmonk88** [comment]
Fixed in the latest release
