### ISSUE TITLE
Import from RollTable no longer seems to work

### ISSUE THREAD

**Issue by geoidesic** [ironmonk88/monks-enhanced-journal#572]
Selected 12 blacksmith items
![Screenshot 2023-06-05 at 10 02 56](https://github.com/ironmonk88/monks-shops/assets/4637995/7123a721-ffc2-4d66-ac7f-f716f5876d40)
Got only one unrelated item
![Screenshot 2023-06-05 at 10 03 05](https://github.com/ironmonk88/monks-shops/assets/4637995/f2d7ce4a-48e5-446c-93a6-ffbff34e96d4)

On further investigation it looks like this happened because I opened two instances of the `Populate from Rolltable table` dialog. And it seems to have been taking the settings from the instance that was hiding behind the shop's dialog (that I couldn't see) rather than from the instance upon which I had made my selections and clicked the `Yes` button.

**Comment by ironmonk88** [comment]
Closing this as it seems like it was an issue with a second sheet being opened at the same time.
