### ISSUE TITLE
[BUG] Note Journal Entry Sorting

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#576]
The folder view of journal entries in the note configuration seems to always show the journals in the `Manual Sort` order they're in, even if the folder is currently set to alphabetical.

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/ef0efb88-3075-47b5-b02a-0f53517586d1)

MEJ 10.16
Foudry 10.291

**Comment by ironmonk88** [comment]
Fixed in the latest release.
