### ISSUE TITLE
[BUG] module is blocking core editing button and other modules

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk88/monks-enhanced-journal#578]
**Describe the bug**
when I try to edit another textbox (character sheet or descriptions from other modules) that use the prose Mirror box, it blocks the save button from the core and from other modules (like item piles description)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version V10.291
 - System DND5e 2.2.1
-Last MEJ;

**Comment by ironmonk88** [comment]
Fixed in the latest release
