### ISSUE TITLE
Open in New Tab context menu option

### ISSUE THREAD

**Issue by MrZwij** [ironmonk88/monks-enhanced-journal#584]
Using imported DDB adventures, which have a lot of nested folders and journal entries, it's sometimes hard to navigate to the right one inside the multilayer folder structure. Tabs are great for helping with this, but they are not as easy to use as they could be.

The existing workflow, as I understand it, is to open a new tab, then find the entry I want. When I do that, I have to navigate all over again to the right folder, which adds time and is tough for my already-overloaded DM brain, especially during sessions.

**Context menu: "Open in New Tab"**
I would like to have the option to right-click on a journal entry and get an "open in new tab" option.

**Comment by ironmonk88** [comment]
Added to the latest release.
