### ISSUE TITLE
Impossible to create a checklist journal [Foundry v10]

### ISSUE THREAD

**Issue by PaukPeck** [ironmonk88/monks-enhanced-journal#586]
Hello,
i wanted to try the check list journal but when i create an entry, it opens a box where i can only write a title and save. No edit button at all :
![monks enhanced](https://github.com/ironmonk88/monks-enhanced-journal/assets/46634593/bd584e9e-0330-4897-a5ba-d1bf1398b61f)
After that, if i double click on my new entry, it opens a box WITH the edit button this time. But in the end, no box to tick
![monks enhanced2](https://github.com/ironmonk88/monks-enhanced-journal/assets/46634593/f050c66d-ab27-4d38-8c89-aa4e2b3fad57)

Am i missing something ?
Thank you

**Comment by ironmonk88** [comment]
Fixed in the latest release
