### ISSUE TITLE
Turning off inline roll styling only changes the style instead of removing all styling.

### ISSUE THREAD

**Issue by TheAlexPlus** [ironmonk88/monks-enhanced-journal#588]
**Describe the bug**
When I uncheck the Inline roll styling option, it removes the orange link style, but adds a bold white style with a drop shadow.

**To Reproduce**
1. Go to Game Settings
2. Click on Inline roll styling option and disable it.
3. Open a journal with a link of some sort.

**Expected behavior**
I had expected that removing styling to leave no styling instead of a different styling.  It's possible that the bold white with drop shadow is just the standard enhanced journal style and instead of this being a bug report it's actually a feature request to add the option for no styles at all.

**Screenshots**
Example of Link Styles with Enhanced Journal turned off:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/92690290/f42ec2e5-7ebc-453e-b916-21bc3ed79248)
Example of Link Styles with Enhanced Journals turned on but Inline Roll Styling turned off:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/92690290/d1b29058-11e1-4cab-8967-bb0898a1253c)
Example of Link Styles with Enhanced Journals turned on but Inline Roll Styling turned on:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/92690290/fb970990-9042-41f6-85b5-90e5dfa870cb)

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: 10 (291)
 - System: DnD5e
 - Module version: 10.17
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes

**Additional context**

**Comment by ironmonk88** [comment]
Added to the latest release.
