### ISSUE TITLE
[BUG] Compendium Errors

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#591]
### 1 

Shows up when creating a journal inside a compendium with MEJ active.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/eea8002c-55c4-4f1a-b3f9-301191099799

### 2

Only shows up when opening a journal that was created inside a compendium's folder.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/2882175e-3967-4bca-8128-617adee23231

MEJ 11.01
Foundry 11.304
FTC

**Comment by Crowguard** [comment]
Still an issue in MEJ 11.02.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
