### ISSUE TITLE
[BUG] Players Unable to Sell

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#594]
No errors.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/118c4fe9-1843-4608-a44b-bbd53e8436d6

Foundry 11.304
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/85d3e5cc-5e3c-4489-a8b5-56aab6504936)

**Comment by ironmonk88** [comment]
Should be fixed in the latest
