### ISSUE TITLE
[BUG] MATT Create Encounter

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#595]
Doesn't work when using a coordinate; works as expected when using an entity or Tagger.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/06c74ef8-aef1-40b4-baca-5aedcf5d04e1

MATT 11.01
MEJ 11.02

**Comment by ironmonk88** [comment]
Fixed in the latest release.
