### ISSUE TITLE
[BUG] Player Console Warnings

### ISSUE THREAD

**Issue by ottyn** [ironmonk88/monks-enhanced-journal#599]
**Describe the bug**
Player sees the following warnings in the console when clicking on their character token on the scene.  No errors or warnings on GM console when this happens.

**Screenshots**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/97130150/5cb059a2-1be3-4edb-a460-472b5c54c3fd)

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: v11.305
 - System: PF2E
 - Module version: MEJ 11.02
 - Are there any errors in the console: No errors, just warnings

**Comment by ironmonk88** [comment]
Fixed in the latest release
