### ISSUE TITLE
Removing an entry doesn't refresh the left panel

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#6]
tested on foundry 0.8.5, DnD5e 1.3.2.

After removing an entry on the right list, if that entry was displayed on the left panel, it remains visible causing some confusion as it is still editable:

![CleanShot 2021-05-31 at 10 54 50](https://user-images.githubusercontent.com/6490765/120168655-69284480-c1ff-11eb-9605-d11659267c63.png)
![CleanShot 2021-05-31 at 10 55 24](https://user-images.githubusercontent.com/6490765/120168669-6d546200-c1ff-11eb-9700-c25f26a28750.png)

**Comment by ironmonk88** [comment]
Fixed and should be in the next release.

**Comment by ironmonk88** [comment]
New Release has been uploaded.
