### ISSUE TITLE
[BUG] Players can't edit journals (maybe due to polyglot)

### ISSUE THREAD

**Issue by Elthair** [ironmonk88/monks-enhanced-journal#600]
Since update to 10.17, all my players are unable to edit their journals, they can create new ones and save, but after closing the page, they can't edit it either. As a GM, I don't have this issue.

 - Browser Chrome
 - Foundry Version [v10 - patch 7 build 303]
 - System [D&D5e 2.2.1]
 - Module version 10.17

sounds like there's an issue with polyglot module as console shows:
monks-enhanced-journal |  rendering journal directory JournalDirectory {options: {…}, appId: 63, _element: S.fn.init(1), position: {…}, _dragDrop: Array(1), …} S.fn.init [section#journal.tab.sidebar-tab.journal-sidebar.directory.flexcol] {cssId: 'journal', cssClass: 'tab sidebar-tab journal-sidebar', tabName: 'journal', user: User, tree: {…}, …}
EnhancedJournalSheet.js:389 Uncaught TypeError: undefined. polyglot.known_languages is not iterable
[Detected 1 package: monks-enhanced-journal]
    at TextEntrySheet.activateEditor (EnhancedJournalSheet.js:389:47)
    at subsheet.activateEditor (enhanced-journal.js:423:42)
   at HTMLAnchorElement.activate (foundry.js:6131:12)

EDIT: confirmed issue with Polyglot 1.9.3 as disabling it fix the issue for the players.

**Comment by Airwrecker** [comment]
Chrome
Foundry v11. build 306
System D&D 5E 2.2.2
Monk's Enhanced Journal 11.03
Polyglot 1.9.4

I've encounter this issue as well. My players can't edit and save a journal entry but as DM I can. 

It looks like it's not necessarily a Polyglot bug but either Monk's Enhanced Journal mod issue or a conflict between that and Polyglot.
1. Disabling one or the other will allow the players to modify and save a journal entry.
2. If both mods are enabled, the players can't modify and save a journal entry.
3. Disabling Polyglot and enabling Monk's Enhanced Journal allows the players to modify and save a journal entry.
4. Disabling Monk's Enhanced Journal and enabling Polyglot allows the players to modify and save a journal entry.

```
Uncaught TypeError: polyglot.known_language is undefined
[Detected 1 package: monks-enhanced journal]
  activateEditor http://xxx.xxx.xxx.xxx/modules/monks-enhanced-journal/sheets/EnhancedJournalSheet.js:406
  activateEditor http://xxx.xxx.xxx.xxx/scripts/foundry.js:6761

**Comment by mclemente** [comment]
I fixed the issue on Polyglot. I refactored `known_languages` and `literate_languages` in a release. I've now added new getters to have legacy support for these. So you can consider this issue fixed.

---

I'd like to point out the next Polyglot release will have more refactoring that will break [this code](https://github.com/ironmonk88/monks-enhanced-journal/blob/a347e5737accd3f2f65d488cc49e11d44d3ca6f6/sheets/EnhancedJournalSheet.js#L414-L424), so I'm wondering how to avoid more breakage between the modules.

I'm wondering if moving Polyglot's wrapper to a method that could be called by MEJ would be better for you, you'd just call it instead of having to keep up with Polyglot's code.

Anyway, here is how the new code will be, I suggest you add an if-condition to check if Polyglot's version is newer than 1.9.4.

```js
const languages = Object.entries(langs).map(([key, lang]) => {
	return {
		title: lang.label || "",
		inline: "span",
		classes: "polyglot-journal",
		attributes: {
			title: lang.label || "",
			"data-language": key || "",
		},
	};
});
```

**Comment by Elthair** [comment]
Sounds like it has been fixed in polygot, thanks.

**Comment by mclemente** [comment]
Hey, Monk, just passing by to say you can remove the Polyglot stuff from `EnhancedJournalSheet.activateEditor`. I've figured out how to add the Polyglot menus to TinyMCE without a wrapper.

Anyway, it won't break anything if you don't remove it, so no big deal.


---

Also, I found an issue on `EnhancedJournalSheet.renderPolyglot` where the language's label is being shown as [object object]. It's a simple fix.

```diff
- languages[lang] : 'Unknown'
+ languages[lang].label : 'Unknown'
```

Btw, would you prefer if I opened an issue to remind you of it instead?
