### ISSUE TITLE
[BUG] Opening journal from macro bar doesn't work

### ISSUE THREAD

**Issue by uniwars** [ironmonk88/monks-enhanced-journal#601]
**Describe the bug**
After draging a module's journal type on the macro bar to easily access it, when clicking on it in the macro bar it will open a standard foundry journal type which will not show many info of the journal and without its normal UI. For example a "picture" journal will only show its title without the actual picture, music or enhanced journal UI.

**To Reproduce**
1. Create a monk's enhanced journal type like picture for example
2. Add info like an image for picture
3. Drag the journal into the macro bar
4. Open it with the macro bar

**Expected behavior**
Journal should open like if opened from the journal tab.

**Screenshots**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/65986545/e91e897b-491b-4d00-8de6-36a33ff65a4c)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version 11 305
 - System Pathfinder 2 v5.1.2
 - Module version 11.03
 - Are there any errors in the console > No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. > Yes

**Comment by SwordofSpirit** [comment]
I noticed that, in addition to this, if you drag a standard journal (not enhanced) to the Macro Bar it will only open as a standard journal without the enhanced journal interface. It would be nice if standard journals on the macro bar could also open up the enhanced journal interface.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
