### ISSUE TITLE
[BUG] SW5E & Ernie's UI Conflict

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#604]
User reported that when using Ernie's UI & SW5E's dark mode, MEJ replaces the dark mode background with the core Foundry background.

Neither the module nor the system has been updated to V11 compatible yet.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/a4559456-0243-4bed-b7f9-36ffc1571f1f

MEJ 11..03
Ernie 0.5.7
SW5E 2.1.5.2.4.7
Foundry 11.305

**Comment by ironmonk88** [comment]
Fixed in the latest release.
At least that part is.
