### ISSUE TITLE
[BUG] Checkbox "Show to players" not work properly

### ISSUE THREAD

**Issue by kai-nashi** [ironmonk88/monks-enhanced-journal#608]
**Describe the bug**
Quest type of journal. Checkbox "Show to players" not work properly. If you want to show it to players you must set checked "Show to players" and then uncheck and check again "Display in notification". To hide quest from players objectives list all steps is same.

**To Reproduce**
1. Create any journal with quest type
2. Set checked "Display in notification"
3. Join to game as user in private tab of browser
4. As player you see objectives list is empty - correct
5. As GM: for quest check "Show to players"
6. As player: you don't see new quest
7. As GM: uncheck and check "Display in notification" ("Show to players" still checked and hasn't touched)
8. As player: new quest is showing

**Expected behavior**
Checking "Show to players" should instantly show quest's in player's objectives list.

**Screenshots**
—

**Please complete as much of the following information as possible:**
 - Browser: firefox 115.0.3
 - Foundry Version: 11.306
 - D&D5e: 2.2.2
 - Monk's Enchanced Journal: 11.03
 - Are there any errors in the console: no
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: no

**Additional context**
—

**Comment by ironmonk88** [comment]
That was just an issue refreshing the notifications list.
The show button was acting correctly.
Fixed in the latest release
