### ISSUE TITLE
[BUG] The description tab is not working properly.

### ISSUE THREAD

**Issue by Ikeoh** [ironmonk88/monks-enhanced-journal#611]
**Describe the bug**
After updating Foundry, the description tab is no longer working as it should. When clicking on the icon to edit the text field, the contents that were already in the journal disappear, and the menu bar also does not appear, making it impossible to save. This happens for all variations of the journal (place, person, point of interest, etc.)

**To Reproduce**
1. Go to Journal tab and create a Journal entry;
2. Click on description tab;
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/34623527/96e26496-ba6a-4dc5-9e82-0103f26306e8)
3. Click on edit icon;
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/34623527/c2b739c0-7576-421f-8490-eb0221dcedd7)
5. See error;
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/34623527/37dc5d16-45ee-43c8-8a5c-cf05bc39a5af)

**Please complete as much of the following information as possible:**
Foundry Virtual Tabletop: Version 11 Stable, 11.307
Game System: dnd5e, 2.2.2
Active Modules: 86
Performance Mode: 2

OS: Unknown
Client: FLC/2.0 (Foundry Lightweight Client)
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 6000 x 4600 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 16 | Ambient Lights: 1 | Ambient Sounds: 0 | Tiles: 15 | Tokens: 11

Actors: 26 | Items: 26 | Journal Entries: 76 | Rollable Tables: 50 |
Playlists: 2 | Compendium Packs: 77 | Chat Messages: 0

**Comment by Ikeoh** [comment]
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/34623527/946567ca-eec6-4310-a99f-58cf0d90264d)

**Comment by ironmonk88** [comment]
That's an update from Polyglot.  Working on the update, but in the meantime, reverting to a previous version of that module will help.

**Comment by ironmonk88** [comment]
Fixed in the latest release

**Comment by Ikeoh** [comment]
Perfect! I appreciate the work and dedication. Congratulations on the module, it's fantastic!
