### ISSUE TITLE
[BUG] Entries Added to the Relationship Tab Overlap on Each Other

### ISSUE THREAD

**Issue by MEK98-DEV** [ironmonk88/monks-enhanced-journal#612]
**Describe the bug**

When dragging and dropping any enhanced journal entry (person, quest, and etc.) onto the relationship tab, the images for all the entries overlap and make it hard to see the images underneath for the previously added entries. This issue also creates further issues in displaying the entries once you begin to add additional journal entry types to the tab.

**To Reproduce**
1. Go to Journal.
2. Create an entry with a relationship tab.
3. From the journal, drag multiple entries onto the relationship tab of the previously created journal.
4. Notice how most images overlap on each other.

**Expected behavior**
The images for the entries on the relationship tab should not overlap.

**Screenshots**
Example 1 (Using actual journal entries from my on-going game)
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/58311857/b76e35b6-8d21-43c1-a98c-106b85bbe76e)

Example 2 (Using default journal entries with nothing configured)
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/58311857/f2d871d5-7f19-4b3c-a84c-28c3d3a5a602)

**Please complete as much of the following information as possible:**
 - Browser: Firefox 115.0.3
 - Foundry Version: 11.307
 - System: GURPS
 - Module version: 11.03
 - Are there any errors in the console: None that I can see.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No.

**Comment by ironmonk88** [comment]
Fixed in the latest release
