### ISSUE TITLE
[BUG] Header 1 over Blockquote

### ISSUE THREAD

**Issue by Deadlyexodus** [ironmonk88/monks-enhanced-journal#618]
**Describe the bug**
Pf2e fumble cards descriptions overflow and have near unreadable chat hooks, Happens to all my players on different browsers

**Expected behavior**
Font should be clear and header should not float over the blockquote

**Screenshots**
[image](https://i.imgur.com/dmD1N86.png)

**Please complete as much of the following information as possible:**
 - Browser [chrome]
 - Foundry Version [v11]
 - System [Pathfinder 2e]
 - Module version 11.07
 - Are there any errors in the console [no]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. [Culprit](https://i.imgur.com/84oT3Gr.png)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
