### ISSUE TITLE
[BUG] Create Journal in Compendium Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#621]
Journal is created, but it results in these errors.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/1affb65b-6b24-4467-838f-b53fc76fcfc2

MEJ 11.07
FTC (Libwrapper, Socketlib, and Tagger)
Foundry 11.308
Pf2 5.4.4

**Comment by ironmonk88** [comment]
Fixed in the latest release.
