### ISSUE TITLE
[BUG] cant make offerings if the players is just observer of an organization journal

### ISSUE THREAD

**Issue by tirzah2** [ironmonk88/monks-enhanced-journal#622]
**Describe the bug**
Players can't make an Offering to a organization journal unless they are owners of the journal.

**To Reproduce**
create an organization journal
set it observer for the player
try to make an offering

**Expected behavior**
to be able to make offering even if the player is just an observer

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version Latest
 - System 5e latest
 - Module version latest
 - no errors
 - yes, i tried with find a culprit

**Comment by ironmonk88** [comment]
Fixed in the latest release.
