### ISSUE TITLE
[BUG] Unable to see items added to the shops

### ISSUE THREAD

**Issue by nursenick** [ironmonk88/monks-enhanced-journal#624]
**Describe the bug**
when adding gear to a shop it askes how many do you want to add then adds it but its not showing up on the list

**Please complete as much of the following information as possible:**
 - Foundry Version [v11
 - System [starfinder]
 - 11.07

**Additional context**

**Comment by Q-efx** [comment]
Same on loot sheet. Error message from console:

`<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="https://vtt.ediyemade.com/systems/sfrpg/maps/module/item/item/item.js:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">item.js:18</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'pack')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at new ItemSFRPG (<span class="devtools-link" role="link" tabindex="-1" title="https://vtt.ediyemade.com/systems/sfrpg/maps/module/item/item/item.js:18:21" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">item.js:18:21</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at LootSheet.getDocument (<span class="devtools-link" role="link" tabindex="-1" title="https://vtt.ediyemade.com/modules/monks-enhanced-journal/sheets/EnhancedJournalSheet.js:1364:24" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EnhancedJournalSheet.js:1364:24</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at LootSheet.getDocument (<span class="devtools-link" role="link" tabindex="-1" title="https://vtt.ediyemade.com/modules/monks-enhanced-journal/sheets/EnhancedJournalSheet.js:1397:33" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EnhancedJournalSheet.js:1397:33</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at LootSheet.addItem (<span class="devtools-link" role="link" tabindex="-1" title="https://vtt.ediyemade.com/modules/monks-enhanced-journal/sheets/LootSheet.js:501:31" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">LootSheet.js:501:31</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at LootSheet._onDrop (<span class="devtools-link" role="link" tabindex="-1" title="https://vtt.ediyemade.com/modules/monks-enhanced-journal/sheets/LootSheet.js:318:30" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">LootSheet.js:318:30</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async EnhancedJournal._onDrop (<span class="devtools-link" role="link" tabindex="-1" title="https://vtt.ediyemade.com/modules/monks-enhanced-journal/apps/enhanced-journal.js:1258:22" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">enhanced-journal.js:1258:22</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas,lucida console,courier new,monospace; --source-code-font-size: 12px; --source-code-font-family: consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | ItemSFRPG | @ | item.js:18
-- | -- | -- | --
  | getDocument | @ | EnhancedJournalSheet.js:1364
  | getDocument | @ | EnhancedJournalSheet.js:1397
  | addItem | @ | LootSheet.js:501
  | _onDrop | @ | LootSheet.js:318
  | await in _onDrop (async) |   |  
  | _onDrop | @ | LootSheet.js:318
  | await in _onDrop (async) |   |  
  | _onDrop | @ | enhanced-journal.js:1255
  | callback | @ | foundry.js:65529
  | _handleDrop | @ | foundry.js:65580

</span></div>
</body>
</html>`

**Comment by ironmonk88** [comment]
Looks like it's an issue with Starfinder not defaulting a value.
I'll see what I can do to compensate for it in MEJ.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
