### ISSUE TITLE
[BUG] Quest Objective Descriptions are Overlapping

### ISSUE THREAD

**Issue by MEK98-DEV** [ironmonk88/monks-enhanced-journal#628]
**Describe the bug**
Objective descriptions are overlapping with other entries within the objectives tab for quests.

**To Reproduce**
1. Go to _Journal_
2. Create a _Quest_.
3. Go to the _Objectives_ tab and create multiple objectives with descriptions.
4. See that the objective descriptions are overlapping with the other objective entries and are making it nearly impossible to read the descriptions.

**Expected behavior**
That the entries would automatically space out so you can read the descriptions.

**Screenshots**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/58311857/7829a1fd-1a1d-4dac-b801-7cc9ff0fe25b)

**Please complete as much of the following information as possible:**
 - Browser - Firefox 118.0.1
 - Foundry Version - 11.381
 - System - GURPS
 - Module version - 11.07
 - Are there any errors in the console - None that I can see.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. - No

**Comment by ironmonk88** [comment]
Fixed in the latest release.
