### ISSUE TITLE
[BUG] Populate from Rolltable, PF1

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#629]
No items are added, nothing in the console. User reports that items do rarely get added, but I can't replicate that.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/4144bc43-9467-49a1-bac8-b7e261c650f0

PF1 9.4
MEJ 11.07
Foundry 11.313

**Comment by ironmonk88** [comment]
Looks like the Roll Tables in question are just populated with Text.
Unfortunately MEJ can't really do much with just text in place of actual Items.
And I suspect that it occasionally works, because a Roll Table was populated with actual Items.
