### ISSUE TITLE
Make slideshows able to have a transparent matte

### ISSUE THREAD

**Issue by zxaos** [ironmonk88/monks-enhanced-journal#630]
**Is your feature request related to a problem? Please describe.**
It'd be really interesting to be able to play a slideshow that has transparency _over_ the existing canvas

**Describe the solution you'd like**
When selecting a canvas color, add an alpha channel.

**Additional context**
Examples of things this could do, just by playing a gif with transparency over the map:
* Flash the borders of the player viewport red when an alert is triggered
* Display a distorted image as a "dream sequence"
* Play a series of faded images over the scene as someone tells a story
* Play an animation of a clock when someone invokes a Flashback (for forged in the dark)

Edit: Apparently this might be possible with Sequencer, but I still think doing it with the ease of the slideshow UI would be neat

**Comment by ironmonk88** [comment]
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/75920956/4abbd42d-2a02-455e-b21a-49893f01cf98)

**Comment by ironmonk88** [comment]
Closing this as the feature already exists.
