### ISSUE TITLE
[BUG] Unable to make an offer to selling player

### ISSUE THREAD

**Issue by Urkaz** [ironmonk88/monks-enhanced-journal#637]
**Describe the bug**
When a player tries to sell an item, the GM has the option to make an offer. Currently, the text fields that allow that in the chat window automatically reset to their default values after losing the focus, making impossible to make an offer.

**To Reproduce**
1. [GM] Create a shop.
2. [Player] Drag an item from the inventory into the shop to sell it.
3. [GM] Try to change the "Quantity" and "Price" values in the chat window.

**Expected behavior**

**Screenshots**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/521864/63616df5-8e6c-417a-833b-65d830bcea20)
Note: The "0 sp" price in the screenshot is not related to the issue.

**Please complete as much of the following information as possible:**
 - Browser: Chrome 119.0.6045.105
 - Foundry Version: v11.313
 - System: DnD5e 2.3.1
 - Module version: 11.07
 - Are there any errors in the console: No errors are displayed.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Yes, I thought it was a problem with another module, but `Find the Culprit` pointed to Monk's Enhanced Journal. I also reproduced the issue in an empty world with only Monk's Enhanced Journal enabled.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
