### ISSUE TITLE
[BUG] Shops & Folders

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#638]
Drag & dropping a folder of items is not adding them to the shop's inventory.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/00e2a78e-21d2-48e4-a966-a5a4fb72926d

Foundry 11.314
MEJ 11.07

**Comment by ironmonk88** [comment]
Fixed in the latest release.
