### ISSUE TITLE
[BUG] Encounter, Location Dupes

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#644]
Adding multiple of the same actor and inputting a location results in weirdness in the location & quantity fields.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/a0218160-911f-43fe-b111-f7aee004fa77

Foundry 11.315
MEJ 11.07

**Comment by ironmonk88** [comment]
Fixed in the latest release.
