### ISSUE TITLE
[BUG] Can't edit images.

### ISSUE THREAD

**Issue by CrazierIvan** [ironmonk88/monks-enhanced-journal#648]
**Describe the bug**
Can't edit images. Observe the screenshot.

**To Reproduce**
Open any enhanced journal, try to right click at the image. See the pop-up disappear immediately. If you do manage to click it, the button doesn't do anything.

**Expected behavior**
I'm supposed to be able to change the image.

**Screenshots**
https://i.imgur.com/QxBuoLc.gif
In this case I've used "Text and Image" journal variant. If I use just "Picture" instead, the menu doesn't even disappear - the button just does nothing.

**Please complete as much of the following information as possible:**
Foundry version 11.308, system version 49, module version 11.07. Google Chrome.
I've tested the issue with just Enhanced Journal and no other modules installed, the issue persists.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
