### ISSUE TITLE
Players see empty journals

### ISSUE THREAD

**Issue by Nedrapter** [ironmonk88/monks-enhanced-journal#65]
I had an incident today with players seeing empty journals. After checking the module's setting I enabled the "Allow players to use the enchanced journal" (which I'm not sure what exactly it allows them to do, but still enabled it). After that, they could see the layout of the journals but not the description/text of the journal. Had to disable the module during the game, so they can access the journals.
Now it gets more strange. After logging into one of my players' clients to test it (after the session), my client could see everything normally. I asked one of them to log back in, and he couldn't see anything. Bottom line: I could see things, regardless of GM or player client, they couldn't. Is there some setting, some browser setting or some other thing we're missing here?

**Comment by WompyTree** [comment]
You should double-check the permissions of the folder which your Journal Entries are in.
Whenever I make new things I always double-check to see if they're hidden or visible to players.

**Comment by Nedrapter** [comment]
It got fixed with one of the latest updates that Ironmonk released.
