### ISSUE TITLE
Broken Thumbnail Image

### ISSUE THREAD

**Issue by sevrick** [ironmonk88/monks-enhanced-journal#654]
**Describe the bug**
The thumbnail when looking at Journal Pages from the Compendium the thumbnail is broken. I haven't change or deleted the default image. As you can see in the picture it doesn't seem to have that problem with the foundry text version.

**To Reproduce**
1. Create a Journal Entry and name it.
2. Drag it to a compendium.
3. See error

**Expected behavior**
I should see the icon and not a broken image

**Screenshots**
![Thumbnail bug](https://github.com/ironmonk88/monks-enhanced-journal/assets/2902311/716fb6f2-8da4-46ce-8ca5-6540ab6bb88b)

**Please complete as much of the following information as possible:**
 - Browser [N/A]
 - Foundry Version [v11]
 - System [Hero System 6E (Unofficial)v2]
 - Module version [Latest]
 - Are there any errors in the console
Found this Red Error when I opened the said compendium: to load resource: the server responded with a status of 404 (Not Found)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
 As far as I can tell no mod conflicts with it.

**Additional context**

**Comment by dodds-steven** [comment]
any word on when the next release will arrive with this fix?

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
