### ISSUE TITLE
[BUG] Inline LInk Styling & Content Link Matching

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#663]
Links are nearly unreadable when this setting is on MEJ.

https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/bf911f83-e7a5-4d66-a4c3-c45b3e20618c

Foundry 11.315
MEJ 11.09

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
