### ISSUE TITLE
[BUG] Journal entries re-appear for all viewers when a relationship changes

### ISSUE THREAD

**Issue by EmmiaSilk** [ironmonk88/monks-enhanced-journal#668]
**Describe the bug**
Editing relationship data for the journal entry will cause it to pop up for anyone who has seen it before.

**To Reproduce**
1. Setup: Create a Foundry world with a Gamemaster user and a Player user.
2. Enable the module (Monk's Enhanced Journals)
3. Create two journal entries which can have relationships (ex: a "Person" and a "Place")
4. Link the two journal entries together in the Relationships tab
5. Share the journal entries to the Player user.
6. The Player is logged in, and has opened (then closed) the Journal Entry since the start of their current Foundry session.  
7. **Execution**: The game master edits the the relationship field in the journal entry, or relationships change for the entry in any other way
8. **Effect**: The window for the journal entry will reappears on the player's screen.

**Expected behavior**
The journal entry should remain closed.

**Screenshots**
(not applicable)

**Please complete as much of the following information as possible:**
 - Browser: Firefox
 - Foundry: v11.315
 - System: Pathfinder 2e
 - Module version: 11.09
 - No error messages (but debug message `monks-enhanced-journal |  Subsheet rendering` appears)
 - Occurs when 

**Additional context**
(none so far)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
