### ISSUE TITLE
[Request] Add ability to disable Loot dialog at end of combat

### ISSUE THREAD

**Issue by zk-sn** [ironmonk88/monks-enhanced-journal#669]
Please add the ability to disable the Loot dialog pop-up after a fight.

**Comment by ironmonk88** [comment]
That's a Tokenbar setting.
And already exists.

**Comment by zk-sn** [comment]
Thank you, I looked everywhere (I thought) but missed the "Do not convert" setting

**Comment by ironmonk88** [comment]
Closing as the issue has been resolved
