### ISSUE TITLE
Lines do not adjust to window size

### ISSUE THREAD

**Issue by TrikyEMF** [ironmonk88/monks-enhanced-journal#67]
In some cases, text lines do not adjust to the window size, nor a horizontal bar appears
![image](https://user-images.githubusercontent.com/8931258/126631579-b0dce51e-24f7-4c17-af35-ea9aed206b9e.png)

**Comment by ironmonk88** [comment]
Is this still an issue?
A lot of changes have been made and it's possible this was fixed.

**Comment by TrikyEMF** [comment]
It seems fine now, thanks!
