### ISSUE TITLE
[BUG] Players cannot toggle between Rewards set to visible

### ISSUE THREAD

**Issue by messiahcide** [ironmonk88/monks-enhanced-journal#670]
**Describe the bug**
Players cannot toggle between 'Rewards' set to visible

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/25340188/cd1feca5-7f9f-47e4-b384-0c26da9812f1)

**To Reproduce**
1. Create a Quest journal entry
2. Create multiple Rewards, set to visible. 
3. Set Quest to Show to Players
4. Log in as Player, and try to toggle between the rewards

**Expected behavior**
Expected behavior is that players will be able to see any rewards created by the GM and set to visible. 

**Screenshots**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/25340188/cd1feca5-7f9f-47e4-b384-0c26da9812f1)

**Please complete as much of the following information as possible:**
 - Browser [Attempted on Chrome, Edge, and Firefox]
 - Foundry Version [V11]
 - System [D&D5e, Imperium Maledictum]
 - Module version [11.09]
 - Are there any errors in the console [e.g. press F12 and look for red text] 
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/25340188/7401a396-d0b1-4482-ab06-04a09fb8edac)

**Comment by messiahcide** [comment]
Additional issues with the quest sheet include:

clicking on the edit button for an attached item under the rewards tab doesn't open the item to be edited. 

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/25340188/9a27a640-8273-4077-85d5-559037df6856)

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/25340188/ee2a99e2-2b3f-450d-958d-1c7c7c9555ee)

When clicking on 'Open Actor Sheet' drop down menu option, it generates a similar error as well

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/25340188/bcaa75c6-fa26-4ef3-bca3-66c200a0501f)
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/25340188/e5a2339b-6de3-4bcf-a66f-41a842f86dc0)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
