### ISSUE TITLE
[BUG] Toggle Objective not resizeable or scroll option.

### ISSUE THREAD

**Issue by BenNelsonNeb** [ironmonk88/monks-enhanced-journal#679]
I allow my players to choose from many open quests like a quest board. The problem is that the "Toggle Objective" popout on the left-side menu cannot be resized (except sideways) and doesn't appear to have a scroll option. Players with laptops, tablets with small screen can only see the top items.

**To Reproduce**
1. Add multiple quests with multiple objectives.
2. Click on the Toggle Objectives icon in the left menu. 
3. Try to resize or scroll. 

**Expected behavior**
Should be able to resize this window vertically. Once resized if details are larger than the area, allow scrolling and a side scroll option.

**Please complete as much of the following information as possible:**
 - Browser - Edge and Firefox
 - Foundry Version 11 315
 - System D&D5e 2.4.1
 - Module version 11.09
 - Are there any errors in the console - None

**Additional context**
None that I can think of.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
