### ISSUE TITLE
Table Size

### ISSUE THREAD

**Issue by rednek74** [ironmonk88/monks-enhanced-journal#682]
**Is your feature request related to a problem? Please describe.**
Table in a journal entry 

**Describe the solution you'd like**
Autofit the text in the table.

**Additional context**
For example, in excel you can auto fit the text in the cells so they either take up more or less space depending on what is in the cell.
I have a lot of tables that take up more space than needed and would like to have the ability to auto size them.

**Comment by ironmonk88** [comment]
This isn't something that Enhanced Journal does.
That's completely dependent on the way you format the table in the editor.
So it's nothing MEJ can control and up to whoever created the table to do that.
