### ISSUE TITLE
[BUG] shared page linked monster actor whitout permission

### ISSUE THREAD

**Issue by Hazuma81** [ironmonk88/monks-enhanced-journal#684]
**Describe the bug**
Hi everyone, I have a problem regarding the monk journal. I shared a blank page where my players can write information. By pure chance one of my players noticed that by selecting the name of an npc, a tab appeared showing the links to that name, stat block, handout etc.etc. I checked the permissions and none of the players have permission to see anything about the monster in question, yet they manage to open the card
**To Reproduce**
1. create new page
2. write monster name
3. select all name
4. automatic windows appear and show the GM content to the player

**Expected behavior**
Aif the player writes the name of an NPC or monster he should not be able to view his status block without permissions

https://github.com/ironmonk88/monks-enhanced-journal/assets/161341335/7114cc08-a6fd-4174-9c01-37194f2223eb

**Screenshots**
video attached

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version 11.315
 - System  D&D5e
 - Module version 11.10
 

**Additional context**

**Comment by Crowguard** [comment]
This is a core issue, not a MEJ issue. Bring it up with Foundry.



https://github.com/ironmonk88/monks-enhanced-journal/assets/99844555/7993d6de-93a1-40a1-96dc-e215d0a4152c

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
