### ISSUE TITLE
[BUG] Changing sheet via sheet settings not possible

### ISSUE THREAD

**Issue by ZeroXNoxus** [ironmonk88/monks-enhanced-journal#685]
**Describe the bug**
Changing the actor sheet via the sheet setting in the dragable header will not change the sheet configuration. It just loads the v2 sheet and the setting to e.g. Legacy Sheet is not saved:

Current Settings:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/29397572/08497173-1e3a-4a21-92af-b3615c1e3ef8)

Attempted Change:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/29397572/f1d2e5c9-db76-4595-9c22-ada7f665f7d1)

Result Settings after save:
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/29397572/8538581f-74c5-4571-a40b-03f0cb81236d)

The only change applied to these settings is via the Game Configurations. This issue seems to only apply when the v2 sheet is currently set for the to-be changed sheet.

I have already run through my 80+ modules and only "Monk's Enhanced Journal" causes this issue on DnD 5th Edition v3.1.X

**To Reproduce**
1. Enable "Monk's Enhanced Journal"
2. Open character sheet
3. Attempt to change from DnD 5th Edition Sheet v2 to any other sheet

**Please complete as much of the following information as possible:**
 - Browser: Chrome (current)
 - Foundry Version: v11.315
 - System: D&D5e v3.1.X
 - Module version: 11.10

**Comment by hatakemaara** [comment]
I came here to report this bug as I am also experiencing it as the DM and my players get it as well on their browsers. 

As a workaround, I disable "Monk's Enhanced Journal" so my players can change their sheet and then when I renable the module it remembers the sheet change (in this case they want to use the "Tidy 5e sheet" module). However, if they change back to the "default 5e sheet" the bug occurs again, and they can't switch back to the "legacy sheet" or any custom sheets.

Browser: Firefox
Foundry Version: v11.315
System D&D 5E v3.1.1
Module v11.10

**Comment by YenBenGrey** [comment]
I am also getting this problem, same set up as the OP. Following.

**Comment by Dyrnwyrm** [comment]
Same issue here, cant change sheets, tested with tidy sheet, disabling the module fixes the issue

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
