### ISSUE TITLE
[BUG] Loot type journal converts descriptions of items to identfied description

### ISSUE THREAD

**Issue by ghost00-Ricgames** [ironmonk88/monks-enhanced-journal#686]
The Loot journals when receiving an item that is unidentified, rather than showing that it shows the core item name. When the item transfers to an Actor or even the item tab, it goes back to its normal behavior.

**To Reproduce**
1. Add an item that you have designated as unidentified in any way, and when it goes to the loot journal it shows the identified information.

**Expected behavior**
Should show the same "Unidentified Trinket etc. Also, the description shown should only be what is in the unidentified description blocks.

**Screenshots**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/122754683/32a5f224-52d5-474d-ac5b-0de62487e0b1)

**Please complete as much of the following information as possible:**
 - Chrome/edge/firefox
 - Foundry Version 315.11
 - System D&D5e 3.1
 - Module version 11.10
 - Are there any errors in the console No

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
