### ISSUE TITLE
Feature Request - Next / Previous Journal entry within compendium/world

### ISSUE THREAD

**Issue by baileymh** [ironmonk88/monks-enhanced-journal#69]
Fantastic module! Incredibly impressive. 

I previously ran on Fantasy Grounds, and one of the features I miss from it is the ability to go to the next or previous journal (story) based on ordering (as opposed to Forward and Back in History)

While this might not be useful for everyone, for GMs who are making / running an AP, it could be incredibly useful. 

Use Case:
As I set up and create my journals, I number them so that they are in sequential order. 1.0.1 The Area, 1.0.2. Sub Area
Being able to click a Next button or so, and move the journal to the next in sequence (potentially respecting sorting order in world or manual vs alphabetical) would be quite nice, and save me a lot of time in Linking.

**Comment by ironmonk88** [comment]
Good suggestion.
The buttons have been added to the bottom of the journal entry.
