### ISSUE TITLE
Support [[/award ...]] currency syntax in RollTables

### ISSUE THREAD

**Issue by NeilWhite** [ironmonk88/monks-enhanced-journal#693]
**Is your feature request related to a problem? Please describe.**
DND5E v 3.0.0 introduces an enricher for currency that uses the syntax `[[/award {formula}{currency}]]` ie: `[[/award 20gp 2d4sp 2d6*10cp]]`. It would be great if the "Populate from roll table" option in loot windows supported this format as well as the current `{formula[coin],...}` syntax.

**Describe the solution you'd like**
When I create a Text row in a rolltable, where the text starts with `[[/award` and ends with `]]` use parsing similar to the dnd5e award enricher to work out how much currency to add to loot table.

**Additional context**
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/1827852/c7deda51-9d6a-4000-a02a-d5f04345a9c3)

**Comment by ironmonk88** [comment]
Should be added to the latest release.
