### ISSUE TITLE
Inconsistent refresh when dropping items on an encounter journal

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#7]
tested on foundry 0.8.5, DnD5e 1.3.2:

When dragging items on an encounter journal the result of the drag is displayed when the next item is dragged

![2021-05-31 11 10 14](https://user-images.githubusercontent.com/6490765/120172498-69c2da00-c203-11eb-9e7b-2c434db22e3f.gif)

**Comment by ironmonk88** [comment]
Could you check this one again?  I think some of the other code I changed may have fixed this.

**Comment by riccisi** [comment]
Ok, I'll check it

**Comment by riccisi** [comment]
I checked with your last version. Unfortunately the issue is still there. It seems that every time I add an item the refresh reveals the previous one, as if it were 1 back...

**Comment by ironmonk88** [comment]
Needed to wait for a save to complete before refreshing.
Hopefully this time it's fixed.

**Comment by riccisi** [comment]
Yes, now it seem ok!

**Comment by ironmonk88** [comment]
Yayyy.  Closing the ticket.
