### ISSUE TITLE
Incompatibility with Kanka module

### ISSUE THREAD

**Issue by MiracleKnows** [ironmonk88/monks-enhanced-journal#70]
There appears to be an incompatibility between this module and the Kanka module. I'm not really sure what's causing them to clash, but when both modules are loaded, the game's scenes vanish, you can't edit the modules to remove either of them, nor can you exit to setup (though you can exit by logging out and exiting to setup that way).

![image](https://user-images.githubusercontent.com/53079915/126976068-aecde7c6-be2a-450e-8667-2b56454dac85.png)

**Comment by ironmonk88** [comment]
That was an ugly one!
I finally managed to track this down.
It's fixed.  How badly do you need the world that's currently inaccessible?
I can help walk you through getting it back... otherwise I'm hoping to have a release of Enhanced Journal sometime later this week.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
