### ISSUE TITLE
Monk Shops - Shop purchase filters.

### ISSUE THREAD

**Issue by ChobitsCrazy** [ironmonk88/monks-enhanced-journal#703]
Would be nice to see an option to limit what a shop can buy based on the item type. i.e. weapon shops are only interested in purchasing weapons. And the players would not have to get approval to sell weapons to a weapons shop.

**Comment by ironmonk88** [comment]
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/75920956/aa3980ce-3bf2-4c9a-ad56-c4905eb56433)

**Comment by ChobitsCrazy** [comment]
Oh I never saw this! You are fantastic!
