### ISSUE TITLE
[Feature Request] Shops to have Services

### ISSUE THREAD

**Issue by Havoclivekiller** [ironmonk88/monks-enhanced-journal#704]
The ability to add services to the shop floor, so that players just pay for something and not get an item in return - food/drinks to eat at tavern or bar, rooms to rest, magical services to cast a spell, etc.

**Comment by ironmonk88** [comment]
You mean the consumable button?
![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/75920956/44e91f34-b6f1-4d91-88dd-e0f69d834455)

**Comment by Havoclivekiller** [comment]
Oh, like that, sure. I was thinking of having a different 'table' in the shop, atop Services and below Items. This can work, thanks.
