### ISSUE TITLE
Suggestion: Add Option to have simpler person journal.

### ISSUE THREAD

**Issue by ghrimn** [ironmonk88/monks-enhanced-journal#71]
Hey, with the new update it seems the person entries have a lot of more fields, which is great if they are used. However, imo the previous version was perfect for simpler NPCs that don't have flaws, bonds, etc all fleshed out. I was wondering if it was possible to have the option to have both, that way it would be possible to still use the person field without having all those fields in blank, if they aren't used.

**Comment by ironmonk88** [comment]
You know, after making the changes... I have to agree.  It got busy fast.
I think the intention next release is to add the option to customize which fields are shown.

**Comment by ironmonk88** [comment]
Editing the fields should now be available.
