### ISSUE TITLE
Undefined folder error for those who don't use Farien Quest Log

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#76]
If you do not use the Farien Quest Log module, an error is thrown due to the lack of check of the presence 
of this folder:

![CleanShot 2021-07-31 at 15 06 01](https://user-images.githubusercontent.com/6490765/127740956-a503e80b-a537-490d-95a0-c13785cfde8b.png)

**Comment by ironmonk88** [comment]
Should be fixed now.
Thank you for catching that.
