### ISSUE TITLE
[Bug] Changes to Location -> City. All old Location JE fail to open.

### ISSUE THREAD

**Issue by typhonrt** [ironmonk88/monks-enhanced-journal#77]
Greets.. Just a heads up... 

It looks like you added data fields to the `location` now apparently city MEJ type. 

The changes unfortunately aren't guarded and apparently no data migration step offered. All old location MEJ journal entries will fail to load. 

Stack trace:
![image](https://user-images.githubusercontent.com/311473/127754743-f66a237a-70ff-410f-b887-d7556a1370ed.png)

Offending code is in EnhancedJournalEntry.js `getData` where you reference the new fields without data migration of old data or optional chaining. 
![image](https://user-images.githubusercontent.com/311473/127754758-f8128c27-eaa0-4a18-a1c8-d243d78ceb9c.png)

**Comment by ironmonk88** [comment]
Closing as I believe this is fixed.
