### ISSUE TITLE
Misaligned "Extract to New Entry" Icon

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-enhanced-journal#78]
Really nothing major. Just tickles my OCD that the icon is not centered. ;)

![image](https://user-images.githubusercontent.com/44159008/127784366-64134b76-dcc9-4a66-b3b9-e136104f3995.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
Let me know if it's still an issue.

**Comment by ironmonk88** [comment]
Closing as I believe this is fixed.
