### ISSUE TITLE
[BUG] Prompt "Unsaved Changes"

### ISSUE THREAD

**Issue by WompyTree** [ironmonk88/monks-enhanced-journal#79]
I usually receive this prompt when I have been working on a journal entry and I switch to another tab I receive the prompt "Unsaved changes will be lost", no matter which option I click, (OK/Cancel, even the X on the top right of the prompt) from that point onwards, I'm no longer able to type -- Even for the names of new items, journal entries, etc.

The only workaround I've found is closing FoundryVTT which is super frustrating.

I love this add-on and the functionality it adds but I end up losing my train of thought every time this happens :(

**Comment by HowFortuitous** [comment]
Just adding that I've also had this issue. Unfortunately I have no additional information to contribute.

**Comment by ironmonk88** [comment]
I think this has been fixed in the latest version.
Could you let me know if it's still an issue?

**Comment by ironmonk88** [comment]
Closing as I believe this has been fixed.
