### ISSUE TITLE
Error creating a new slideshow

### ISSUE THREAD

**Issue by riccisi** [ironmonk88/monks-enhanced-journal#8]
tested on foundry 0.8.5, DnD5e 1.3.2

After creating a new slideshow journal entry, viewing it gives an error:

![CleanShot 2021-05-31 at 14 42 16](https://user-images.githubusercontent.com/6490765/120195094-a94aef80-c21e-11eb-8c98-f6c4db131e12.png)

**Comment by ironmonk88** [comment]
Fixed, will be in the next release.

Also... thank you for all the debugging!  I swear I checked it before releasing, but there's so much to cover with this module.

**Comment by riccisi** [comment]
no problem, I love the idea of ​​your new module, so I thought I'd tell you the things I gradually found to simplify the testing phase

**Comment by ironmonk88** [comment]
New Release has been uploaded.
