### ISSUE TITLE
Allow multiple windows

### ISSUE THREAD

**Issue by baileymh** [ironmonk88/monks-enhanced-journal#84]
Need to say again how amazing this module is, it has so many great features! Amazing work! 

I do however, find myself wishing I could open multiple windows. The tabs are great, but when preparing as a GM its useful to be able to reference other entries without having to save, switch, read, switch back, edit. 

Perhaps CTRL + click or Shift + clicking an entry could open it in a new window?

**Comment by ironmonk88** [comment]
Ctrl+click opens in a new tab.
Added dragging the tab off the journal to open that entry as a regular Journal Entry without the browser part.
