### ISSUE TITLE
Does not work with Module creation

### ISSUE THREAD

**Issue by Freewolf2000** [ironmonk88/monks-enhanced-journal#86]
I have created some content for an adventure module within my local version of Foundry. When I export the data to a compendium, the batch that compendium into a module. I require Monk's enhanced Journal for the module to work.

When i pull the module into a fresh world (with MHJ loaded and enabled) none of the MHJ content shows up for any of the journal entires. All of the Journal Entries appears as just standard journal entries, if I set one to a person, or shop or whatever.

Is there something that I am missing?

**Comment by Freewolf2000** [comment]
Am I missing something with this?

Not being able to use this with created modules, essentially makes this unusable for me.

**Comment by Snake-Venom** [comment]
This sounds like the same as https://github.com/ironmonk88/monks-enhanced-journal/issues/61 , where data is lost when entering compendiums (which is fixed, awaiting release)

**Comment by Freewolf2000** [comment]
Yes it does thank you.
