### ISSUE TITLE
"Convert" botton missing in journal type: "Picture"

### ISSUE THREAD

**Issue by Snake-Venom** [ironmonk88/monks-enhanced-journal#87]
I was testing out the "Convert" functionality using a test journal in order to go through the various types in order to see what I want to use.

Then I got to the "Picture" type and that button is no longer available, making it impossible to convert back to something else. This is also the case when creating a Journal of that type using "Create Entry" in the sidebar.

Before converting to picture:
![Screenshot from 2021-08-17 12-01-01](https://user-images.githubusercontent.com/16118725/129707695-1f0f2882-36a5-4613-859a-ec904a8e8dea.png)
After converting to Picture:
![Screenshot from 2021-08-17 12-01-23](https://user-images.githubusercontent.com/16118725/129707699-3d78a202-60cb-40ef-bb3a-8905060bc39b.png)

If this is the intended behavior, say because there is an issue/conflict/etc behind the scenes, please at the very least provide a popup warning that this conversion is permanent.

Note: While slideshows also don't have a "Convert" button, it is not an issue there because you can't convert _to_ a slideshow.

**Comment by Snake-Venom** [comment]
Forgot to say:

- Tested with all other modules turned off
- Module version: 1.0.21
- dnd 5e version: 1.4.2
- Foundry version: 0.8.8

**Comment by ironmonk88** [comment]
Latest version should allow you to convert a picture.  
Forgot to add the convert menu to the Picture type.

Slideshows don't have a convert because none of the information really converts to any of the other types.  It doesn't really make much sense to allow that one to convert, so by design it's been left off.
