### ISSUE TITLE
Feature Suggestion: Refresh Journal tab when a Journal Type is changed

### ISSUE THREAD

**Issue by flamewave000** [ironmonk88/monks-enhanced-journal#88]
Currently if you change the type of a journal, the icon for that journal is updated in the Enhanced Journal window, but not on the system Journal tab. After a journal's type is changed a call like the following would allow the journals tab to update with the new icons.
```javascript
await ui.sidebar.tabs.journal.render(true)
```

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
