### ISSUE TITLE
Shop Journal Type breaking

### ISSUE THREAD

**Issue by ghrimn** [ironmonk88/monks-enhanced-journal#89]
It seems that it isn't possible to change an already existing journal, to the SHOP type. This actually ends up breaking the entry as then it appears completely blank and without the option to revert or change type.

It's only possible to create a shop entry by creating one directly as such. However, when adding items to the shop list, if the item is removed from the world, the journal entry breaks and shows empty again.
![image](https://user-images.githubusercontent.com/26261352/130645748-070233ab-7d22-405f-96bd-c7b584c17bf2.png)

**Comment by hburnett** [comment]
I'm also getting very similar behaviour with the 'Shop' category for Journal entries.
Trying to open a Shop journal entry just gives a blank page.
![image](https://user-images.githubusercontent.com/9428903/132146730-f7f9a0e3-67d8-41e4-8d29-5742ad08b437.png)

However if you open another journal entry from the enhanced journal browser and then go back to the entry that wasn't working, it will now be visible.
Unfortunately the browser still thinks you're on the old page, so if you click Edit it will start changing the previous journal entry.
In the example below, Book Wyrm's Treasure is a 'Shop' and Corellon's Crown is a 'Journal Entry'. Going from Corellon's to Book Wyrm, the navigator at the bottom doesn't update and the heading towards the top doesn't either.
Also has the side effect of not being images not being able to 'Show Players' on these bugged pages.
![image](https://user-images.githubusercontent.com/9428903/132146529-f4668790-d4ff-462b-9aa7-096db7b92bc3.png)

As a workaround, if you Duplicate the journal entries, the duplicate is categorised as 'Journal Entry' and works normally, saves you rewriting everything.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
