### ISSUE TITLE
[Suggestions] Quest Journal Improvements

### ISSUE THREAD

**Issue by megahead11** [ironmonk88/monks-enhanced-journal#9]
Hi! Really love the fact you implemented a quest journal! I can see this easily replacing Forien's Quest Log (which is now nonfunctional as of 0.8.x and effectively abandoned) with a few features.

 Some suggestions or features I'd like to see:

* Add an indicator or different quest icon to differentiate completed quests from the directory
* An "objectives" tab that can easily add check box or numbered objectives; this is different and more streamlined (objectives only) from using the journal itself, which may be better for quest details.
* Maybe a way for players to set a quest or two as the actively tracked one, with an overlay of the above objectives for the HUD.

**Comment by ironmonk88** [comment]
I like those suggestions!
I'll see about getting them implemented.

**Comment by Turqueso** [comment]
Adding reference to an actor in Person type journals would be nice to

**Comment by ironmonk88** [comment]
Indicators have been added to the directory.  On the left side of the entry will be a colored bar indicating the quest's status.
Objectives have been added.
There's now an objectives HUD that appears when the notes tool is selected.  Provided there is an "In Progress" Quest.

**Comment by ironmonk88** [comment]
> 
> 
> Adding reference to an actor in Person type journals would be nice to

I've added this as a separate enhancement.
