### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by Luisphigor** [ironmonk88/monks-enhanced-journal#90]
Pls find attached italian translation file.
[it.zip](https://github.com/ironmonk88/monks-enhanced-journal/files/7047639/it.zip)

Code to include in module.json file:

` { "lang": "it", "name": "Italiano", "path": "lang/it.json" },`

I hope you'll include il in your next release. Thanks

In addiction pls let me report that I was not able to translate following entries because corresponding json keys are missing:
![entries mej](https://user-images.githubusercontent.com/85732446/130807594-1a534dd0-b78a-47ba-a297-12b074031c24.jpg)

thanks

**Comment by ironmonk88** [comment]
Italian translation should be added now.
And I've gone through the code and added any missing texts I could find.  Those should be added to the latest English version.

**Comment by ironmonk88** [comment]
Added to the latest release.
