### ISSUE TITLE
Unable to add "Townsfolk" or "Shops" entries when editing a "Place" type journal entry

### ISSUE THREAD

**Issue by Asherlock** [ironmonk88/monks-enhanced-journal#91]
Editing the description works fine.
![image](https://user-images.githubusercontent.com/15909275/131236999-dea2b489-6a73-4f1b-a88e-55c35c9b806c.png)

But there is no option to add townsfolk or shops as shown below.
![image](https://user-images.githubusercontent.com/15909275/131237010-24f0c3bc-0ed9-44b9-98b7-650ed6c35a81.png)

![image](https://user-images.githubusercontent.com/15909275/131237037-9895ef51-3cab-4da4-a8af-fe0d0e5cf68b.png)

Also GM notes have no formatting at all :(
![image](https://user-images.githubusercontent.com/15909275/131237078-3469aa83-71a9-4b28-8524-820e09fb216c.png)

Its gonna be a huge help in the end. Thanks for all the hard work! :)

**Comment by hburnett** [comment]
I'm also getting very similar behaviour with the 'Shop' category for Journal entries.
Trying to open a Shop journal entry just gives a blank page.
![image](https://user-images.githubusercontent.com/9428903/132146730-f7f9a0e3-67d8-41e4-8d29-5742ad08b437.png)

However if you open another journal entry from the enhanced journal browser and then go back to the entry that wasn't working, it will now be visible.
Unfortunately the browser still thinks you're on the old page, so if you click Edit it will start changing the previous journal entry.
In the example below, Book Wyrm's Treasure is a 'Shop' and Corellon's Crown is a 'Journal Entry'. Going from Corellon's to Book Wyrm, the navigator at the bottom doesn't update and the heading towards the top doesn't either.
Also has the side effect of not being images not being able to 'Show Players' on these bugged pages.
![image](https://user-images.githubusercontent.com/9428903/132146529-f4668790-d4ff-462b-9aa7-096db7b92bc3.png)

**Comment by ironmonk88** [comment]
Townsfolk and shop are drag and drop from other journal entries.  So a Person dragged onto a Place will create Townsfolk.  A Shop dragged on will be added as a shop.
I've added a message when there are no items to make it clearer how to add items.
Currently there's no formatting on the Notes for a variety of reasons.  
It's been added as it's own ticket as it comes up fairly often.

**Comment by ironmonk88** [comment]
This should be cleared up in the latest release.
Still no formatting for Notes yet.
