### ISSUE TITLE
Remove hardcoded css color

### ISSUE THREAD

**Issue by erithtotl** [ironmonk88/monks-enhanced-journal#97]
.monks-journal-sheet.sheet .items-list .item .item-name

is set in the CSS to a basically black color.  In systems that use a 'dark' theme, it means that these items are invisible (like the 'townsfolk' tab on a settlement.

I don't know if there are additional situations where this would be a problem, but clearing this CSS element fixes it for that screen.

**Comment by ironmonk88** [comment]
This needs to be there due to system inconsistencies with their styling.
I'd rather MEJ provide a consistent interface and provide customization on a per system/request basis.
