### ISSUE TITLE
"limited" Permissions for players

### ISSUE THREAD

**Issue by bmgraves** [ironmonk88/monks-enhanced-journal#98]
In default journal for foundry, assigning limited permissions for journal entries allows you to place a pin on the map that the players can see, but when they open the journal they do not see the text itself. When using enhanced journal types such as Points of Interest, or Places, this functionality breaks down. Limited permissions allow players to view the entirety of the entry(minus the notes section, which is something but not altogether convenient for all use cases).

Would be great if you could have limited permission journal pins on the map that players couldn't see the details of.

**Comment by webmaster94** [comment]
This is a serious problem. I am using these for my own organization and my players can now see all of my notes if they double click on map icons. It has been a long time since this has been reported. I don't know if this has any priority.

**Comment by ironmonk88** [comment]
This should be fixed.  In v10, pictures can be opened, but Journal Entries won't.
